import type { GeneratedFile } from './engines';
import type { HandoffIR, IrScene } from './ir';
import { MAIL_ON_CLIPBOARD, MAILTO_LIMIT, NOTES_PRINT_STYLE } from '../play';

/**
 * Placeholder Godot scenes (.tscn): one per story scene, ready to run. Each
 * holds the scene's flow controller, a labelled placeholder for everything
 * in it (the location, characters, objects wired to their interactable
 * scripts, items, cinematics, puzzles and logic), and a plain on-screen
 * player, so pressing Play in Godot plays the scene before any art or UI
 * exists. play_story.tscn plays the whole story from the Beginning.
 *
 * They are rewritten on each export: real art goes in a scene inherited from
 * one (Scene › New Inherited Scene), which keeps working as long as the
 * story's element names do.
 */

export const RUNTIME = 'addons/vcgs_runtime';

const COLORS: Record<string, string> = {
  scene: '#4fa39a',
  cinematic: '#9a7fc0',
  choice: '#f2c230',
  object: '#4a86d8',
  environment: '#6fae5e',
  inventory: '#6cc4d6',
  puzzle: '#e07bb0',
  trigger: '#c8bfae',
  gate: '#c8bfae',
  state: '#c8bfae',
  character: '#d9607a',
};

const str = (v: string) => JSON.stringify(v);
const color = (hex: string): string => {
  const m = /^#?([0-9a-f]{6})$/i.exec(hex.trim());
  const n = m ? parseInt(m[1]!, 16) : 0xc8bfae;
  const c = (shift: number) => (((n >> shift) & 255) / 255).toFixed(3).replace(/\.?0+$/, '') || '0';
  return `Color(${c(16)}, ${c(8)}, ${c(0)}, 1)`;
};

// ---------------------------------------------------------------- the runtime pieces

export const sceneRuntime = (): GeneratedFile[] => {
  const file = (name: string, lines: string[]): GeneratedFile => ({ path: `${RUNTIME}/${name}`, content: `${lines.join('\n')}\n`, kind: 'runtime' });
  return [
    file('placeholder.gd', [
      '@tool',
      '# VCGS Runtime for Godot 4.',
      'class_name VCGSPlaceholder',
      'extends Node2D',
      '## Stands in for an element\'s art until the real thing arrives: a shape in',
      '## its type\'s colour with its name. Replace it in an inherited scene.',
      '',
      '@export var kind := "object":',
      '\tset(value):',
      '\t\tkind = value',
      '\t\tqueue_redraw()',
      '@export var label := "":',
      '\tset(value):',
      '\t\tlabel = value',
      '\t\tqueue_redraw()',
      '@export var color := Color.WHITE:',
      '\tset(value):',
      '\t\tcolor = value',
      '\t\tqueue_redraw()',
      '@export var size := Vector2(96, 72):',
      '\tset(value):',
      '\t\tsize = value',
      '\t\tqueue_redraw()',
      '',
      'func _draw() -> void:',
      '\tvar font := ThemeDB.fallback_font',
      '\tvar h := size * 0.5',
      '\tif kind == "environment":',
      '\t\tdraw_rect(Rect2(Vector2.ZERO, size), Color(color, 0.08), true)',
      '\t\tdraw_rect(Rect2(Vector2.ZERO, size), Color(color, 0.6), false, 2.0)',
      '\t\tdraw_string(font, Vector2(14, 26), label, HORIZONTAL_ALIGNMENT_LEFT, -1, 16, color)',
      '\t\treturn',
      '\tif kind == "character":',
      '\t\tdraw_colored_polygon(PackedVector2Array([Vector2(0, -h.y), Vector2(h.x * 0.6, h.y), Vector2(-h.x * 0.6, h.y)]), color)',
      '\telif kind == "trigger" or kind == "gate" or kind == "state":',
      '\t\tvar r := h.y * 0.6',
      '\t\tdraw_colored_polygon(PackedVector2Array([Vector2(0, -r), Vector2(r, 0), Vector2(0, r), Vector2(-r, 0)]), color)',
      '\telif kind == "inventory":',
      '\t\tdraw_circle(Vector2.ZERO, h.y * 0.5, color)',
      '\telif kind == "cinematic":',
      '\t\tdraw_rect(Rect2(-h, size), Color(color, 0.25), true)',
      '\t\tdraw_rect(Rect2(-h, size), color, false, 2.0)',
      '\telif kind == "choice":',
      '\t\tdraw_circle(Vector2.ZERO, h.y * 0.55, color)',
      '\telse:',
      '\t\tdraw_rect(Rect2(-h * 0.7, size * 0.7), color, true)',
      '\tdraw_string(font, Vector2(-h.x - 20, h.y + 18), label, HORIZONTAL_ALIGNMENT_CENTER, size.x + 40, 13, Color(0.95, 0.9, 0.8))',
    ]),
    file('debug_player.gd', [
      '# VCGS Runtime for Godot 4.',
      'class_name VCGSDebugPlayer',
      'extends CanvasLayer',
      '## A plain on-screen player: shows each line, action and cinematic, the',
      '## options of a choice, and the objects to use in free play, so a scene',
      '## plays before the game has its own UI. Enter presses the first button,',
      '## 1-9 the others. C opens the codex (/ searches it, Tab picks a section, S sorts it, the arrows and B bookmark an entry, N writes a note on it, E saves every note as a text file, I reads them back, Y copies them to share, V takes in shared ones, M emails them, T texts them, P opens them as a page to print). F5 saves the game and F9 loads it (save_game / load_game): the quest log, the characters met, the locations visited, the items found, the objects used, the mechanics, the encounters met and the lore found so far. Take it out',
      '## (or keep it for testing) when the game has its own dialogue box, choice',
      '## menu and codex.',
      '',
      '@export var flow_path: NodePath',
      '@export var scene_title := ""',
      '@export var generated_root := "res://vcgs/generated"',
      '@export var autostart := true',
      '## With no flow: play the whole story from its Beginning, scene after scene.',
      '@export var whole_story := false',
      '## Where the codex notes sync: the notes are merged with this file (the newer note wins)',
      '## when the codex opens, every few seconds while it is open, and after each note.',
      '## Put it in a folder that syncs (a cloud drive, Steam Cloud) to share them across devices;',
      '## empty turns syncing off.',
      '@export var codex_sync_path := "user://codex_notes_sync.json"',
      '',
      'var flow: VCGSSceneFlow',
      '## What the player is doing: "wait", "choice", "free", "story" or "end".',
      'var mode := ""',
      'var _title: Label',
      'var _text: Label',
      'var _buttons: HFlowContainer',
      'var _labels: Array[String] = []',
      'var _actions: Array[Callable] = []',
      'var _ends := ""',
      'var _set_up := false',
      'var _codex: PanelContainer',
      'var _codex_label: Label',
      'var _codex_button: Button',
      'var _codex_search: LineEdit',
      'var _codex_filters: HBoxContainer',
      '## The entry the cursor is on (its key, "lore:…"), for bookmarking with B; and the entries shown, in order.',
      'var _codex_cursor := ""',
      'var _codex_shown: Array = []',
      '## The box for the player\'s note on the entry under the cursor (N opens it, Enter keeps it).',
      'var _codex_note_edit: LineEdit',
      '## Each entry shown, by key: "SECTION · its first line", for the notes export.',
      'var _codex_titles: Dictionary = {}',
      '## A line under the codex saying what just happened (the notes saved, say).',
      'var _codex_status: Label',
      '## What the last save or load did (F5 saves, F9 loads).',
      'var _save_status: Label',
      '## The section the codex is filtered to ("" for all of them).',
      'var _codex_section := ""',
      '## How each section is ordered: "found" (as found), "newest" or "name" (A–Z).',
      'var _codex_sort := "found"',
      'var _codex_sort_button: OptionButton',
      'const CODEX_SORTS := ["found", "newest", "name"]',
      `const NOTES_PRINT_STYLE := ${JSON.stringify(NOTES_PRINT_STYLE)}`,
      `const MAILTO_LIMIT := ${MAILTO_LIMIT}`,
      `const MAIL_ON_CLIPBOARD := ${JSON.stringify(MAIL_ON_CLIPBOARD)}`,
      '## Every section a codex can have, in the order it shows them.',
      'const CODEX_SECTIONS := ["quests", "characters", "locations", "items", "objects", "mechanics", "encounters", "lore"]',
      '## Codex updates (quests, characters, locations, items, objects, mechanics, encounters, lore) since it was last opened.',
      'var _codex_new := 0',
      '',
      'func _game() -> VCGSGameState:',
      '\tvar tree := get_tree() if is_inside_tree() else Engine.get_main_loop() as SceneTree',
      '\treturn tree.root.get_node_or_null("GameState") as VCGSGameState if tree else null',
      '',
      'func _ready() -> void:',
      '\t_setup()',
      '\tif autostart:',
      '\t\tstart_now.call_deferred()',
      '',
      '## Build the panel and listen to the flow, once, whenever it is first needed.',
      'func _setup() -> void:',
      '\tif _set_up:',
      '\t\treturn',
      '\t_set_up = true',
      '\t_build()',
      '\t_title.text = scene_title',
      '\tif not flow_path.is_empty():',
      '\t\tflow = get_node_or_null(flow_path) as VCGSSceneFlow',
      '\tvar game := _game()',
      '\tif game == null:',
      '\t\t_show("Add res://addons/vcgs_runtime/game_state.gd as an autoload named GameState, then run this scene again.", [])',
      '\t\treturn',
      '\tgame.changed.connect(_on_game_changed)',
      '\tgame.lore_discovered.connect(_on_codex_news)',
      '\tgame.quest_started.connect(_on_codex_news)',
      '\tgame.quest_completed.connect(_on_codex_news)',
      '\tgame.mechanic_available.connect(_on_codex_news)',
      '\tgame.encounter_met.connect(_on_codex_news)',
      '\tgame.encounter_won.connect(_on_codex_news)',
      '\tgame.character_met.connect(_on_character_met)',
      '\tgame.item_found.connect(_on_item_found)',
      '\tgame.location_visited.connect(_on_location_visited)',
      '\tgame.object_used.connect(_on_object_used)',
      '\tif flow:',
      '\t\tflow.event_started.connect(_on_event)',
      '\t\tflow.choice_requested.connect(_on_choice)',
      '\t\tflow.free_play_started.connect(_on_free_play)',
      '\t\tflow.encounter_requested.connect(_on_encounter)',
      '\t\tflow.game_over.connect(_on_game_over)',
      '\t\tflow.scene_finished.connect(_on_finished)',
      '',
      '## Begin: this scene\'s timeline, or the story from its Beginning.',
      'func start_now() -> void:',
      '\t_setup()',
      '\tvar game := _game()',
      '\tif game == null:',
      '\t\treturn',
      '\t_codex_new = 0',
      '\t_refresh_codex_button()',
      '\tif flow:',
      '\t\tif game.flags.is_empty() and game.object_states.is_empty() and not game.loaded:',
      '\t\t\tVCGSRules.reset(game)',
      '\t\tgame.loaded = false',
      '\t\tflow.start()',
      '\telif whole_story:',
      '\t\tVCGSRules.reset(game)',
      '\t\tgo_to(VCGSStory.START)',
      '',
      '## Save the game (F5): as the scene being played began, so loading plays it again from its',
      '## start. Returns where it was saved, or "" if it could not.',
      'func save_game(path := "user://savegame.json") -> String:',
      '\tvar game := _game()',
      '\tif game == null:',
      '\t\treturn ""',
      '\tvar file := FileAccess.open(path, FileAccess.WRITE)',
      '\tif file == null:',
      '\t\treturn ""',
      '\tfile.store_string(game.save_text(VCGSStory.NAME))',
      '\tfile.close()',
      '\treturn path',
      '',
      '## Load a saved game (F9; one from any engine\'s VCGS runtime) and, with play, play on from the',
      '## start of the scene it was saved in. Returns that scene\'s key ("" for the story\'s beginning),',
      '## or null when there is no save to load.',
      'func load_game(path := "user://savegame.json", play := true) -> Variant:',
      '\tvar game := _game()',
      '\tif game == null or not FileAccess.file_exists(path):',
      '\t\treturn null',
      '\tvar at = game.load_text(FileAccess.get_file_as_string(path))',
      '\tif at == null or not play:',
      '\t\treturn at',
      '\tvar node: Dictionary = VCGSStory.NODES.get(at, {})',
      '\tif str(node.get("file", "")) != "":',
      '\t\t(Engine.get_main_loop() as SceneTree).change_scene_to_file.call_deferred(str(node["file"]))',
      '\telse:',
      '\t\tgo_to(VCGSStory.START if at == "" else at)',
      '\treturn at',
      '',
      '## What the buttons say now, and what the text says (for tests and tools).',
      'func labels() -> Array[String]:',
      '\treturn _labels',
      '',
      'func text() -> String:',
      '\t_setup()',
      '\treturn _text.text',
      '',
      '## Press the i-th button.',
      'func press(i: int) -> void:',
      '\tif i >= 0 and i < _actions.size():',
      '\t\t_actions[i].call()',
      '',
      'func _unhandled_input(event: InputEvent) -> void:',
      '\tvar key := event as InputEventKey',
      '\tif key == null or not key.pressed or key.echo:',
      '\t\treturn',
      '\tif key.keycode == KEY_F5:',
      '\t\tvar saved := save_game()',
      '\t\t_save_status.text = ("Saved (F9 loads it): " + ProjectSettings.globalize_path(saved)) if saved != "" else "Could not save the game."',
      '\t\treturn',
      '\tif key.keycode == KEY_F9:',
      '\t\tvar at = load_game()',
      '\t\t_save_status.text = "No saved game at " + ProjectSettings.globalize_path("user://savegame.json") if at == null else "Loaded: playing on from " + (str(VCGSStory.NODES.get(at, {}).get("name", at)) if at != "" else "the beginning") + "."',
      '\t\treturn',
      '\tif key.keycode == KEY_C:',
      '\t\ttoggle_codex()',
      '\t\treturn',
      '\tif codex_open():',
      '\t\tif key.keycode == KEY_SLASH:',
      '\t\t\t_codex_search.grab_focus()',
      '\t\telif key.keycode == KEY_DOWN or key.keycode == KEY_UP:',
      '\t\t\tmove_codex_cursor(1 if key.keycode == KEY_DOWN else -1)',
      '\t\telif key.keycode == KEY_ESCAPE and _codex_note_edit.has_focus():',
      '\t\t\t_close_note()',
      '\t\telif key.keycode == KEY_E:',
      '\t\t\tvar path := export_codex_notes()',
      '\t\t\t_codex_status.text = ("Notes saved to " + ProjectSettings.globalize_path(path)) if path != "" else "Could not save the notes."',
      '\t\telif key.keycode == KEY_I:',
      '\t\t\tvar read := import_codex_notes()',
      '\t\t\t_codex_status.text = _say_taken(read) if not read.is_empty() else "No notes file at " + ProjectSettings.globalize_path("user://codex_notes.txt")',
      '\t\telif key.keycode == KEY_Y:',
      '\t\t\tshare_codex_notes()',
      '\t\t\t_codex_status.text = "Notes copied: paste them to share them (V takes them in, in another codex)."',
      '\t\telif key.keycode == KEY_P:',
      '\t\t\tvar page := print_codex_notes()',
      '\t\t\t_codex_status.text = ("Notes page opened to print: " + ProjectSettings.globalize_path(page)) if page != "" else "Could not save the notes page."',
      '\t\telif key.keycode == KEY_M:',
      '\t\t\t_codex_status.text = "Opening your mail app with the notes." if email_codex_notes()["whole"] else "The notes are too long for a mail link: they are on the clipboard. Paste them into the mail."',
      '\t\telif key.keycode == KEY_T:',
      '\t\t\t_codex_status.text = "Opening your messages app with the notes." if text_codex_notes()["whole"] else "The notes are too long for a text link: they are on the clipboard. Paste them into the message."',
      '\t\telif key.keycode == KEY_V:',
      '\t\t\t_codex_status.text = _say_taken(paste_codex_notes())',
      '\t\telif key.keycode == KEY_N:',
      '\t\t\tedit_codex_note()',
      '\t\telif key.keycode == KEY_B:',
      '\t\t\ttoggle_codex_bookmark()',
      '\t\telif key.keycode == KEY_S:',
      '\t\t\tset_codex_sort(CODEX_SORTS[(CODEX_SORTS.find(_codex_sort) + 1) % CODEX_SORTS.size()])',
      '\t\telif key.keycode == KEY_TAB:',
      '\t\t\tvar options := _codex_filter_options()',
      '\t\t\tvar step := -1 if key.shift_pressed else 1',
      '\t\t\tset_codex_section(options[(options.find(_codex_section) + step + options.size()) % options.size()])',
      '\t\telif key.keycode == KEY_ESCAPE and _codex_search.has_focus() and _codex_search.text != "":',
      '\t\t\tset_codex_search("")',
      '\t\telif key.keycode == KEY_ESCAPE or key.keycode == KEY_ENTER:',
      '\t\t\tclose_codex()',
      '\t\tget_viewport().set_input_as_handled()',
      '\t\treturn',
      '\tif key.keycode == KEY_ENTER or key.keycode == KEY_KP_ENTER or key.keycode == KEY_SPACE:',
      '\t\tpress(0)',
      '\telif key.keycode >= KEY_1 and key.keycode <= KEY_9:',
      '\t\tpress(key.keycode - KEY_1)',
      '',
      'func _build() -> void:',
      '\tvar panel := PanelContainer.new()',
      '\tpanel.set_anchors_preset(Control.PRESET_BOTTOM_WIDE)',
      '\tpanel.offset_top = -230',
      '\tadd_child(panel)',
      '\tvar box := VBoxContainer.new()',
      '\tpanel.add_child(box)',
      '\tvar head := HBoxContainer.new()',
      '\tbox.add_child(head)',
      '\t_title = Label.new()',
      '\t_title.modulate = Color(0.91, 0.78, 0.45)',
      '\t_title.size_flags_horizontal = Control.SIZE_EXPAND_FILL',
      '\thead.add_child(_title)',
      '\t_save_status = Label.new()',
      '\t_save_status.modulate = Color(0.91, 0.78, 0.45)',
      '\t_save_status.tooltip_text = "F5 saves the game, F9 loads it"',
      '\thead.add_child(_save_status)',
      '\t_codex_button = Button.new()',
      '\t_codex_button.focus_mode = Control.FOCUS_NONE',
      '\t_codex_button.pressed.connect(toggle_codex)',
      '\t_codex_button.visible = not (VCGSRules.LORE.is_empty() and VCGSRules.QUESTS.is_empty() and VCGSRules.CHARACTERS.is_empty() and VCGSRules.LOCATIONS.is_empty() and VCGSRules.ITEMS.is_empty() and VCGSRules.OBJECT_ENTRIES.is_empty() and VCGSRules.MECHANICS.is_empty() and VCGSRules.ENCOUNTERS.is_empty())',
      '\thead.add_child(_codex_button)',
      '\t_refresh_codex_button()',
      '\t_text = Label.new()',
      '\t_text.autowrap_mode = TextServer.AUTOWRAP_WORD_SMART',
      '\t_text.custom_minimum_size = Vector2(0, 120)',
      '\tbox.add_child(_text)',
      '\t_buttons = HFlowContainer.new()',
      '\tbox.add_child(_buttons)',
      '\t# The codex: over the scene, until closed.',
      '\t_codex = PanelContainer.new()',
      '\t_codex.set_anchors_preset(Control.PRESET_FULL_RECT)',
      '\t_codex.offset_left = 80',
      '\t_codex.offset_right = -80',
      '\t_codex.offset_top = 60',
      '\t_codex.offset_bottom = -260',
      '\t_codex.visible = false',
      '\tvar style := StyleBoxFlat.new()',
      '\tstyle.bg_color = Color(0.09, 0.08, 0.06, 0.97)',
      '\tstyle.border_color = Color(0.91, 0.78, 0.45)',
      '\tstyle.set_border_width_all(1)',
      '\tstyle.set_content_margin_all(18)',
      '\t_codex.add_theme_stylebox_override("panel", style)',
      '\tadd_child(_codex)',
      '\tvar pages := VBoxContainer.new()',
      '\t_codex.add_child(pages)',
      '\t# Search: only the entries that match (/ to type, Enter to stop typing).',
      '\t_codex_search = LineEdit.new()',
      '\t_codex_search.placeholder_text = "Search the codex  ( / )"',
      '\t_codex_search.clear_button_enabled = true',
      '\t_codex_search.text_changed.connect(func(_t: String) -> void: _refresh_codex())',
      '\t_codex_search.text_submitted.connect(func(_t: String) -> void: _codex_search.release_focus())',
      '\tpages.add_child(_codex_search)',
      '\t# Filter by section: All, or one of those this story has (Tab for the next).',
      '\t_codex_filters = HBoxContainer.new()',
      '\tpages.add_child(_codex_filters)',
      '\tvar group := ButtonGroup.new()',
      '\tfor key in _codex_filter_options():',
      '\t\tvar chip := Button.new()',
      '\t\tchip.text = "★ Bookmarks" if key == "bookmarks" else (key.capitalize() if key != "" else "All")',
      '\t\tchip.toggle_mode = true',
      '\t\tchip.button_group = group',
      '\t\tchip.focus_mode = Control.FOCUS_NONE',
      '\t\tchip.button_pressed = key == ""',
      '\t\tchip.pressed.connect(set_codex_section.bind(key))',
      '\t\t_codex_filters.add_child(chip)',
      '\t_codex_filters.visible = codex_section_keys().size() > 1',
      '\t# Sort each section: as found, newest first, or A–Z (S for the next).',
      '\t_codex_sort_button = OptionButton.new()',
      '\t_codex_sort_button.focus_mode = Control.FOCUS_NONE',
      '\tfor label in ["Order found", "Newest first", "A–Z"]:',
      '\t\t_codex_sort_button.add_item(label)',
      '\t_codex_sort_button.item_selected.connect(func(i: int) -> void: set_codex_sort(CODEX_SORTS[i]))',
      '\tpages.add_child(_codex_sort_button)',
      '\t_codex_note_edit = LineEdit.new()',
      '\t_codex_note_edit.placeholder_text = "Your note (Enter to keep it, Esc to leave it)"',
      '\t_codex_note_edit.visible = false',
      '\t_codex_note_edit.text_submitted.connect(func(t: String) -> void: set_codex_note(t))',
      '\tpages.add_child(_codex_note_edit)',
      '\tvar sync_timer := Timer.new()',
      '\tsync_timer.wait_time = 3.0',
      '\tsync_timer.autostart = true',
      '\tsync_timer.timeout.connect(_sync_tick)',
      '\tadd_child(sync_timer)',
      '\t_codex_status = Label.new()',
      '\t_codex_status.modulate = Color(0.91, 0.78, 0.45)',
      '\tpages.add_child(_codex_status)',
      '\tvar scroll := ScrollContainer.new()',
      '\tscroll.size_flags_vertical = Control.SIZE_EXPAND_FILL',
      '\tpages.add_child(scroll)',
      '\t_codex_label = Label.new()',
      '\t_codex_label.autowrap_mode = TextServer.AUTOWRAP_WORD_SMART',
      '\t_codex_label.size_flags_horizontal = Control.SIZE_EXPAND_FILL',
      '\tscroll.add_child(_codex_label)',
      '\tvar close := Button.new()',
      '\tclose.text = "Close"',
      '\tclose.pressed.connect(close_codex)',
      '\tpages.add_child(close)',
      '',
      '## The codex in words: the quest log (under way, each with its goal, then done, in',
      '## the order started), the characters met, locations visited, items found and',
      '## objects used (those with a codex entry), the mechanics available, the',
      '## encounters met (each with its enemies and weakness, and whether it was won)',
      '## and every lore entry found, in order. With a search (query), only the entries',
      '## it finds, ignoring case, in the sections that have any; headings still count everything.',
      '## With a section ("quests", "lore"…, as codex_section_keys() lists them), only that one.',
      '## With a sort ("found", the default; "newest"; "name", A–Z ignoring case), each section in that order.',
      '## Bookmarked entries end their first line with ★; the section "bookmarks" shows only them.',
      '## An entry the player has a note on ends with it ("Note: …"); a search looks in the notes too.',
      '## With a cursor (an entry key, "lore:…"), that entry starts with ▶.',
      'func codex_text(query := "", section := "", sort := "", cursor := "") -> String:',
      '\tvar game := _game()',
      '\tvar parts: Array[String] = []',
      '\t_codex_shown = []',
      '\t_codex_titles = {}',
      '\tvar q := query.strip_edges().to_lower()',
      '\tif not VCGSRules.QUESTS.is_empty():',
      '\t\tvar active: Array = []',
      '\t\tvar done: Array = []',
      '\t\tfor key in (game.quests.keys() if game else []):',
      '\t\t\tvar quest: Dictionary = VCGSRules.QUESTS.get(key, {})',
      '\t\t\tvar title := str(quest.get("name", key))',
      '\t\t\tif game.quest_state(key) == "done":',
      '\t\t\t\tdone.append(["quests:" + key, "• %s (done)" % title])',
      '\t\t\telse:',
      '\t\t\t\tvar goal := str(quest.get("goal", ""))',
      '\t\t\t\tactive.append(["quests:" + key, "• %s%s" % [title, (" — " + goal) if goal != "" else ""]])',
      '\t\t_section(parts, "quests", section, "QUESTS · %d under way, %d done" % [active.size(), done.size()], _sorted(active, sort) + _sorted(done, sort), "\\n", "None yet.", q, cursor)',
      '\tif not VCGSRules.CHARACTERS.is_empty():',
      '\t\tvar cast: Array = []',
      '\t\tfor key in (game.met_characters() if game else []):',
      '\t\t\tif VCGSRules.CHARACTERS.has(key):',
      '\t\t\t\tvar who: Dictionary = VCGSRules.CHARACTERS[key]',
      '\t\t\t\tcast.append(["characters:" + key, "%s\\n%s" % [str(who.get("name", key)).to_upper(), str(who.get("codex", ""))]])',
      '\t\t_section(parts, "characters", section, "CHARACTERS · %d of %d met" % [cast.size(), VCGSRules.CHARACTERS.size()], _sorted(cast, sort), "\\n\\n", "None yet.", q, cursor)',
      '\tif not VCGSRules.LOCATIONS.is_empty():',
      '\t\tvar places: Array = []',
      '\t\tfor key in (game.visited_locations() if game else []):',
      '\t\t\tif VCGSRules.LOCATIONS.has(key):',
      '\t\t\t\tvar place: Dictionary = VCGSRules.LOCATIONS[key]',
      '\t\t\t\tplaces.append(["locations:" + key, "%s\\n%s" % [str(place.get("name", key)).to_upper(), str(place.get("codex", ""))]])',
      '\t\t_section(parts, "locations", section, "LOCATIONS · %d of %d visited" % [places.size(), VCGSRules.LOCATIONS.size()], _sorted(places, sort), "\\n\\n", "None yet.", q, cursor)',
      '\tif not VCGSRules.ITEMS.is_empty():',
      '\t\tvar things: Array = []',
      '\t\tfor key in (game.items_found() if game else []):',
      '\t\t\tif VCGSRules.ITEMS.has(key):',
      '\t\t\t\tvar item: Dictionary = VCGSRules.ITEMS[key]',
      '\t\t\t\tvar count := int(game.items.get(key, 0))',
      '\t\t\t\tvar carried := (" (carried ×%d)" % count) if count > 1 else (" (carried)" if count == 1 else "")',
      '\t\t\t\tthings.append(["items:" + key, "%s%s\\n%s" % [str(item.get("name", key)).to_upper(), carried, str(item.get("codex", ""))]])',
      '\t\t_section(parts, "items", section, "ITEMS · %d of %d found" % [things.size(), VCGSRules.ITEMS.size()], _sorted(things, sort), "\\n\\n", "None yet.", q, cursor)',
      '\tif not VCGSRules.OBJECT_ENTRIES.is_empty():',
      '\t\tvar props: Array = []',
      '\t\tfor key in (game.objects_used() if game else []):',
      '\t\t\tif VCGSRules.OBJECT_ENTRIES.has(key):',
      '\t\t\t\tvar thing: Dictionary = VCGSRules.OBJECT_ENTRIES[key]',
      '\t\t\t\tvar now := str(game.object_states.get(key, ""))',
      '\t\t\t\tprops.append(["objects:" + key, "%s%s\\n%s" % [str(thing.get("name", key)).to_upper(), (" (" + now + ")") if now != "" else "", str(thing.get("codex", ""))]])',
      '\t\t_section(parts, "objects", section, "OBJECTS · %d of %d used" % [props.size(), VCGSRules.OBJECT_ENTRIES.size()], _sorted(props, sort), "\\n\\n", "None yet.", q, cursor)',
      '\tif not VCGSRules.MECHANICS.is_empty():',
      '\t\tvar usable: Array = []',
      '\t\tfor key in (game.mechanics.keys() if game else []):',
      '\t\t\tvar mechanic: Dictionary = VCGSRules.MECHANICS.get(key, {})',
      '\t\t\tvar controls := str(mechanic.get("details", {}).get("controls", ""))',
      '\t\t\tusable.append(["mechanics:" + key, "%s%s\\n%s" % [str(mechanic.get("name", key)).to_upper(), ("\\nControls: " + controls) if controls != "" else "", str(mechanic.get("text", ""))]])',
      '\t\t_section(parts, "mechanics", section, "MECHANICS · %d of %d available" % [usable.size(), VCGSRules.MECHANICS.size()], _sorted(usable, sort), "\\n\\n", "None yet.", q, cursor)',
      '\tif not VCGSRules.ENCOUNTERS.is_empty():',
      '\t\tvar faced: Array = []',
      '\t\tvar beaten := 0',
      '\t\tfor key in (game.met_encounters() if game else []):',
      '\t\t\tvar encounter: Dictionary = VCGSRules.ENCOUNTERS.get(key, {})',
      '\t\t\tvar details: Dictionary = encounter.get("details", {})',
      '\t\t\tvar enemies := str(details.get("enemies", ""))',
      '\t\t\tvar weakness := str(details.get("weakness", ""))',
      '\t\t\tif game.was_won(key):',
      '\t\t\t\tbeaten += 1',
      '\t\t\tfaced.append(["encounters:" + key, "%s%s%s%s\\n%s" % [str(encounter.get("name", key)).to_upper(), " (won)" if game.was_won(key) else "", ("\\nEnemies: " + enemies) if enemies != "" else "", ("\\nWeak to: " + weakness) if weakness != "" else "", str(encounter.get("text", ""))]])',
      '\t\t_section(parts, "encounters", section, "ENCOUNTERS · %d met, %d won" % [faced.size(), beaten], _sorted(faced, sort), "\\n\\n", "None yet.", q, cursor)',
      '\tif not VCGSRules.LORE.is_empty():',
      '\t\tvar found: Array = []',
      '\t\tfor key in (game.known_lore() if game else []):',
      '\t\t\tvar entry: Dictionary = VCGSRules.LORE.get(key, {})',
      '\t\t\tfound.append(["lore:" + key, "%s\\n%s" % [str(entry.get("name", key)).to_upper(), str(entry.get("text", ""))]])',
      '\t\t_section(parts, "lore", section, "LORE · %d of %d found" % [found.size(), VCGSRules.LORE.size()], _sorted(found, sort), "\\n\\n", "Nothing found yet.", q, cursor)',
      '\tif q != "" and parts.is_empty():',
      '\t\tvar within := (" in " + section.capitalize()) if CODEX_SECTIONS.has(section) or section == "bookmarks" else ""',
      '\t\treturn "CODEX\\n\\nNothing matches \\"%s\\"%s." % [query.strip_edges(), within]',
      '\tif section == "bookmarks" and parts.is_empty():',
      '\t\treturn "CODEX\\n\\nNo bookmarks yet."',
      '\treturn "CODEX\\n\\n" + "\\n\\n".join(parts)',
      '',
      '## Entries in a sort\'s order: as found, newest first, or by name (A–Z, ignoring case).',
      'func _sorted(entries: Array, sort: String) -> Array:',
      '\tvar out := entries.duplicate()',
      '\tif sort == "newest":',
      '\t\tout.reverse()',
      '\telif sort == "name":',
      '\t\tout.sort_custom(func(a: Array, b: Array) -> bool: return str(a[1]).to_lower() < str(b[1]).to_lower())',
      '\treturn out',
      '',
      '## One section of the codex: its heading, then each entry ([key, text]; only those the',
      '## search finds, if any, and only bookmarks for the section "bookmarks").',
      'func _section(parts: Array[String], key: String, only: String, heading: String, entries: Array, sep: String, empty: String, q: String, cursor: String) -> void:',
      '\tvar marks: Dictionary = _game().bookmarks if _game() else {}',
      '\tvar notes: Dictionary = _game().codex_notes if _game() else {}',
      '\tif only == "bookmarks":',
      '\t\tentries = entries.filter(func(e: Array) -> bool: return marks.has(e[0]))',
      '\t\tif entries.is_empty():',
      '\t\t\treturn',
      '\telif only != "" and only != key:',
      '\t\treturn',
      '\tvar shown: Array = []',
      '\tfor entry in entries:',
      '\t\tif q == "" or str(entry[1]).to_lower().contains(q) or str(notes.get(entry[0], "")).to_lower().contains(q):',
      '\t\t\tshown.append(entry)',
      '\tif q != "" and shown.is_empty():',
      '\t\treturn',
      '\tvar text := heading',
      '\tif shown.is_empty():',
      '\t\ttext += "\\n" + empty',
      '\tfor entry in shown:',
      '\t\tvar words := str(entry[1])',
      '\t\tif marks.has(entry[0]):',
      '\t\t\tvar nl := words.find("\\n")',
      '\t\t\twords = words.insert(nl, " ★") if nl >= 0 else words + " ★"',
      '\t\tif entry[0] == cursor:',
      '\t\t\twords = "▶ " + words',
      '\t\tif str(notes.get(entry[0], "")) != "":',
      '\t\t\twords += "\\nNote: " + str(notes[entry[0]])',
      '\t\ttext += sep + words',
      '\t\t_codex_shown.append(entry[0])',
      '\t\t_codex_titles[entry[0]] = "%s · %s" % [key.to_upper(), str(entry[1]).get_slice("\\n", 0).trim_prefix("• ")]',
      '\tparts.append(text)',
      '',
      '## Search the codex (what the search box holds); "" shows everything.',
      'func set_codex_search(query: String) -> void:',
      '\t_setup()',
      '\t_codex_search.text = query',
      '\t_refresh_codex()',
      '',
      '## The sections this story\'s codex has (those with anything to find), in order.',
      'func codex_section_keys() -> Array[String]:',
      '\tvar tables := [VCGSRules.QUESTS, VCGSRules.CHARACTERS, VCGSRules.LOCATIONS, VCGSRules.ITEMS, VCGSRules.OBJECT_ENTRIES, VCGSRules.MECHANICS, VCGSRules.ENCOUNTERS, VCGSRules.LORE]',
      '\tvar keys: Array[String] = []',
      '\tfor i in CODEX_SECTIONS.size():',
      '\t\tif not tables[i].is_empty():',
      '\t\t\tkeys.append(CODEX_SECTIONS[i])',
      '\treturn keys',
      '',
      '## Filter the codex to one section ("" for all of them).',
      'func set_codex_section(key: String) -> void:',
      '\t_setup()',
      '\t_codex_section = key',
      '\tvar options := _codex_filter_options()',
      '\tfor i in _codex_filters.get_child_count():',
      '\t\t(_codex_filters.get_child(i) as Button).set_pressed_no_signal(options[i] == key)',
      '\t_refresh_codex()',
      '',
      '## What the filter row offers: All, the bookmarks, then each section this story has.',
      'func _codex_filter_options() -> Array[String]:',
      '\tvar options: Array[String] = ["", "bookmarks"]',
      '\toptions.append_array(codex_section_keys())',
      '\treturn options',
      '',
      'func _refresh_codex() -> void:',
      '\t_codex_label.text = codex_text(_codex_search.text, _codex_section, _codex_sort, _codex_cursor)',
      '',
      '## The entries shown now, in order, by key ("lore:…").',
      'func codex_entry_keys() -> Array:',
      '\t_setup()',
      '\t_refresh_codex()',
      '\treturn _codex_shown.duplicate()',
      '',
      '## Move the cursor (▶) to the next entry shown (step 1) or the one before (-1).',
      'func move_codex_cursor(step: int) -> void:',
      '\tvar keys := codex_entry_keys()',
      '\tif keys.is_empty():',
      '\t\t_codex_cursor = ""',
      '\telse:',
      '\t\tvar at := keys.find(_codex_cursor)',
      '\t\t_codex_cursor = keys[0 if at < 0 else clampi(at + step, 0, keys.size() - 1)]',
      '\t_refresh_codex()',
      '',
      'func codex_cursor() -> String:',
      '\treturn _codex_cursor',
      '',
      '## The player\'s notes in words, to export: each entry with a note, in the codex\'s order, under',
      '## "SECTION · the entry\'s first line" (the same as the studio\'s play-through exports).',
      'func codex_notes_text() -> String:',
      '\tvar game := _game()',
      '\tcodex_text()',
      '\tvar parts: Array[String] = ["CODEX NOTES · " + VCGSStory.NAME]',
      '\tfor key in _codex_shown:',
      '\t\tif game and game.note_for(key) != "":',
      '\t\t\tparts.append(str(_codex_titles[key]) + "\\n" + game.note_for(key))',
      '\tif parts.size() == 1:',
      '\t\tparts.append("No notes yet.")',
      '\t_refresh_codex()',
      '\treturn "\\n\\n".join(parts)',
      '',
      '## Save the notes as a text file (E); returns where, or "" if it could not.',
      'func export_codex_notes(path := "user://codex_notes.txt") -> String:',
      '\tvar file := FileAccess.open(path, FileAccess.WRITE)',
      '\tif file == null:',
      '\t\treturn ""',
      '\tfile.store_string(codex_notes_text())',
      '\tfile.close()',
      '\treturn path',
      '',
      '## The notes as a page to print: the story\'s name, then each section\'s notes under its',
      '## name, entry by entry (the same page as the studio\'s play-through prints).',
      'func codex_notes_page() -> String:',
      '\tvar blocks := codex_notes_text().split("\\n\\n")',
      '\tvar name := blocks[0].trim_prefix("CODEX NOTES · ")',
      '\tvar body: Array[String] = []',
      '\tvar section := ""',
      '\tfor i in range(1, blocks.size()):',
      '\t\tvar lines := blocks[i].split("\\n")',
      '\t\tvar at := lines[0].find(" · ")',
      '\t\tif at < 0:',
      '\t\t\tbody.append("<p>" + blocks[i].xml_escape() + "</p>")',
      '\t\t\tcontinue',
      '\t\tvar s := lines[0].substr(0, at)',
      '\t\tif s != section:',
      '\t\t\tbody.append("<h2>" + (s.substr(0, 1) + s.substr(1).to_lower()).xml_escape() + "</h2>")',
      '\t\tsection = s',
      '\t\tvar rest: Array[String] = []',
      '\t\tfor j in range(1, lines.size()):',
      '\t\t\trest.append(lines[j].xml_escape())',
      '\t\tbody.append("<div class=\\"note\\"><h3>" + lines[0].substr(at + 3).xml_escape() + "</h3><p>" + "<br>".join(rest) + "</p></div>")',
      '\treturn "<!doctype html>\\n<html><head><meta charset=\\"utf-8\\"><title>" + name.xml_escape() + " · codex notes</title><style>" + NOTES_PRINT_STYLE + "</style></head>\\n<body><h1>" + name.xml_escape() + "</h1><p class=\\"sub\\">Codex notes</p>\\n" + "\\n".join(body) + "\\n</body></html>\\n"',
      '',
      '## Print the notes (P): save them as a page and open it, to print from the browser.',
      '## Returns where, or "" if it could not.',
      'func print_codex_notes(path := "user://codex_notes.html", open := true) -> String:',
      '\tvar file := FileAccess.open(path, FileAccess.WRITE)',
      '\tif file == null:',
      '\t\treturn ""',
      '\tfile.store_string(codex_notes_page())',
      '\tfile.close()',
      '\tif open:',
      '\t\tOS.shell_open(ProjectSettings.globalize_path(path))',
      '\treturn path',
      '',
      '## The notes as a mail link, for the mail app: "<story> codex notes" and the notes (the same',
      '## link as the studio\'s). { "url": …, "whole": false } when they are too long for a link:',
      '## then the mail says they are on the clipboard.',
      'func codex_notes_mailto() -> Dictionary:',
      '\tvar text := codex_notes_text()',
      '\tvar head := "mailto:?subject=" + (text.get_slice("\\n", 0).trim_prefix("CODEX NOTES · ") + " codex notes").uri_encode() + "&body="',
      '\tvar url := head + text.replace("\\n", "\\r\\n").uri_encode()',
      '\tif url.length() <= MAILTO_LIMIT:',
      '\t\treturn { "url": url, "whole": true }',
      '\treturn { "url": head + MAIL_ON_CLIPBOARD.uri_encode(), "whole": false }',
      '',
      '## Email the notes (M): open the mail app with them; too long for a link, they go on the',
      '## clipboard first. Returns the mail, as codex_notes_mailto() does.',
      'func email_codex_notes(open := true) -> Dictionary:',
      '\tvar mail := codex_notes_mailto()',
      '\tif not mail["whole"]:',
      '\t\tDisplayServer.clipboard_set(codex_notes_text())',
      '\tif open:',
      '\t\tOS.shell_open(mail["url"])',
      '\treturn mail',
      '',
      '## The notes as a text-message link (sms:), for the messages app: the notes as the message',
      '## (the same link as the studio\'s). Too long for a link, as codex_notes_mailto().',
      'func codex_notes_sms() -> Dictionary:',
      '\tvar url := "sms:?&body=" + codex_notes_text().uri_encode()',
      '\tif url.length() <= MAILTO_LIMIT:',
      '\t\treturn { "url": url, "whole": true }',
      '\treturn { "url": "sms:?&body=" + MAIL_ON_CLIPBOARD.uri_encode(), "whole": false }',
      '',
      '## Text the notes (T): open the messages app with them; too long for a link, they go on the',
      '## clipboard first. Returns the message, as codex_notes_sms() does.',
      'func text_codex_notes(open := true) -> Dictionary:',
      '\tvar sms := codex_notes_sms()',
      '\tif not sms["whole"]:',
      '\t\tDisplayServer.clipboard_set(codex_notes_text())',
      '\tif open:',
      '\t\tOS.shell_open(sms["url"])',
      '\treturn sms',
      '',
      '## An entry\'s name as notes are matched by: its first line without the quest bullet,',
      '## a quest\'s goal, or states in brackets ("(won)", "(carried ×2)"), ignoring case.',
      'static func codex_name_of(first_line: String) -> String:',
      '\tvar name := first_line.strip_edges().trim_prefix("• ")',
      '\tvar dash := name.find(" — ")',
      '\tif dash >= 0:',
      '\t\tname = name.substr(0, dash)',
      '\tvar state := RegEx.create_from_string(" \\\\([^()]*\\\\)$")',
      '\twhile state.search(name):',
      '\t\tname = state.sub(name, "")',
      '\treturn name.strip_edges().to_lower()',
      '',
      '## Read notes exported from a codex (this one\'s, the studio\'s or another engine\'s):',
      '## each "SECTION · entry" block is matched to an entry in this codex by section and',
      '## name. Returns { "notes": { key: note }, "skipped": [headings that match nothing here] }.',
      'func codex_notes_from(text: String) -> Dictionary:',
      '\tcodex_text()',
      '\tvar by_name := {}',
      '\tfor key in _codex_titles:',
      '\t\tvar title := str(_codex_titles[key])',
      '\t\tvar at := title.find(" · ")',
      '\t\tby_name[title.substr(0, at).to_lower() + "|" + codex_name_of(title.substr(at + 3))] = key',
      '\t_refresh_codex()',
      '\tvar notes := {}',
      '\tvar skipped: Array[String] = []',
      '\t# Blocks: lines between blank lines.',
      '\tvar blocks: Array = [[]]',
      '\tfor line in text.replace("\\r\\n", "\\n").replace("\\r", "\\n").split("\\n"):',
      '\t\tif line.strip_edges() == "":',
      '\t\t\tblocks.append([])',
      '\t\telse:',
      '\t\t\tblocks[-1].append(line)',
      '\tfor lines in blocks:',
      '\t\tif lines.is_empty():',
      '\t\t\tcontinue',
      '\t\tvar head := str(lines[0])',
      '\t\tvar at := head.find(" · ")',
      '\t\tif at < 0 or head.begins_with("CODEX NOTES"):',
      '\t\t\tcontinue',
      '\t\tvar note := "\\n".join(PackedStringArray(lines.slice(1))).strip_edges()',
      '\t\tif note == "":',
      '\t\t\tcontinue',
      '\t\tvar key: String = by_name.get(head.substr(0, at).strip_edges().to_lower() + "|" + codex_name_of(head.substr(at + 3)), "")',
      '\t\tif key != "":',
      '\t\t\tnotes[key] = note',
      '\t\telse:',
      '\t\t\tskipped.append(head.strip_edges())',
      '\treturn { "notes": notes, "skipped": skipped }',
      '',
      '## Import notes from a text file (I): the notes matched are set (the others stay).',
      '## Returns what codex_notes_from() does, or {} if the file could not be read.',
      'func import_codex_notes(path := "user://codex_notes.txt") -> Dictionary:',
      '\tvar game := _game()',
      '\tif game == null or not FileAccess.file_exists(path):',
      '\t\treturn {}',
      '\treturn take_codex_notes(FileAccess.get_file_as_string(path))',
      '',
      '## Take in notes from exported or shared text: the notes matched are set (the others stay).',
      'func take_codex_notes(text: String) -> Dictionary:',
      '\tvar game := _game()',
      '\tvar read := codex_notes_from(text)',
      '\tif game:',
      '\t\tfor key in read["notes"]:',
      '\t\t\tgame.set_note(key, read["notes"][key])',
      '\t_refresh_codex()',
      '\treturn read',
      '',
      '## Sync the notes with the sync file: merge it in (the newer note wins), and write the',
      '## result back. Returns how many notes the file changed here, or -1 when it could not sync.',
      'func sync_codex_notes(path := "") -> int:',
      '\tvar game := _game()',
      '\tvar where := path if path != "" else codex_sync_path',
      '\tif game == null or where == "":',
      '\t\treturn -1',
      '\tvar changed := 0',
      '\tif FileAccess.file_exists(where):',
      '\t\tchanged = maxi(0, game.sync_notes(FileAccess.get_file_as_string(where)))',
      '\tvar text := game.notes_sync_text(VCGSStory.NAME)',
      '\tif not FileAccess.file_exists(where) or FileAccess.get_file_as_string(where) != text:',
      '\t\tvar file := FileAccess.open(where, FileAccess.WRITE)',
      '\t\tif file == null:',
      '\t\t\treturn -1',
      '\t\tfile.store_string(text)',
      '\t\tfile.close()',
      '\tif changed > 0:',
      '\t\t_codex_status.text = "Notes synced: %d changed elsewhere." % changed',
      '\t_refresh_codex()',
      '\treturn changed',
      '',
      'func _sync_tick() -> void:',
      '\tif codex_open():',
      '\t\tsync_codex_notes()',
      '',
      '## Share the notes (Y): put them on the clipboard, as the text the export writes. Returns it.',
      'func share_codex_notes() -> String:',
      '\tvar text := codex_notes_text()',
      '\tDisplayServer.clipboard_set(text)',
      '\treturn text',
      '',
      '## Take in notes someone shared (V): read them from the clipboard.',
      'func paste_codex_notes() -> Dictionary:',
      '\treturn take_codex_notes(DisplayServer.clipboard_get())',
      '',
      'func _say_taken(read: Dictionary) -> String:',
      '\treturn "Imported %d notes%s" % [read["notes"].size(), (". Not in the codex (yet): " + "; ".join(read["skipped"])) if not read["skipped"].is_empty() else ""]',
      '',
      '## Open the note box for the entry under the cursor (the first shown, if none).',
      'func edit_codex_note() -> void:',
      '\tvar game := _game()',
      '\tif game == null:',
      '\t\treturn',
      '\tif not codex_entry_keys().has(_codex_cursor):',
      '\t\tmove_codex_cursor(0)',
      '\tif _codex_cursor == "":',
      '\t\treturn',
      '\t_codex_note_edit.text = game.note_for(_codex_cursor)',
      '\t_codex_note_edit.visible = true',
      '\tif _codex_note_edit.is_inside_tree():',
      '\t\t_codex_note_edit.grab_focus()',
      '',
      '## Keep a note on the entry under the cursor ("" takes it off), and close the box.',
      'func set_codex_note(text: String) -> void:',
      '\tvar game := _game()',
      '\tif game and _codex_cursor != "":',
      '\t\tgame.set_note(_codex_cursor, text)',
      '\t_close_note()',
      '\tsync_codex_notes()',
      '',
      'func _close_note() -> void:',
      '\t_codex_note_edit.visible = false',
      '\tif _codex_note_edit.has_focus():',
      '\t\t_codex_note_edit.release_focus()',
      '\t_refresh_codex()',
      '',
      '## Bookmark the entry under the cursor (the first shown, if none), or take its bookmark off.',
      'func toggle_codex_bookmark() -> void:',
      '\tvar game := _game()',
      '\tif game == null:',
      '\t\treturn',
      '\tif not codex_entry_keys().has(_codex_cursor):',
      '\t\tmove_codex_cursor(0)',
      '\tif _codex_cursor != "":',
      '\t\tgame.toggle_bookmark(_codex_cursor)',
      '\t_refresh_codex()',
      '',
      '## Order each section: "found" (as found), "newest" (newest first) or "name" (A–Z).',
      'func set_codex_sort(key: String) -> void:',
      '\t_setup()',
      '\t_codex_sort = key if CODEX_SORTS.has(key) else "found"',
      '\t_codex_sort_button.select(CODEX_SORTS.find(_codex_sort))',
      '\t_refresh_codex()',
      '',
      'func codex_sort() -> String:',
      '\treturn _codex_sort',
      '',
      'func codex_section() -> String:',
      '\treturn _codex_section',
      '',
      'func codex_search() -> String:',
      '\treturn _codex_search.text if _codex_search else ""',
      '',
      'func codex_open() -> bool:',
      '\treturn _codex != null and _codex.visible',
      '',
      'func open_codex() -> void:',
      '\t_setup()',
      '\tsync_codex_notes()',
      '\t_codex_new = 0',
      '\t_refresh_codex()',
      '\t_codex.visible = true',
      '\t_refresh_codex_button()',
      '',
      'func close_codex() -> void:',
      '\tif _codex:',
      '\t\t_codex.visible = false',
      '\t\tif _codex_search.has_focus():',
      '\t\t\t_codex_search.release_focus()',
      '',
      'func toggle_codex() -> void:',
      '\tif codex_open():',
      '\t\tclose_codex()',
      '\telse:',
      '\t\topen_codex()',
      '',
      '## What the codex button says: how many quest, character, location, item, object, mechanic, encounter and lore updates are new since it was last opened.',
      'func codex_button_text() -> String:',
      '\treturn _codex_button.text if _codex_button else ""',
      '',
      'func _on_codex_news(_key: String) -> void:',
      '\tif codex_open():',
      '\t\t_refresh_codex()',
      '\telse:',
      '\t\t_codex_new += 1',
      '\t_refresh_codex_button()',
      '',
      '## Only an object with a codex entry is news for the codex.',
      'func _on_object_used(key: String) -> void:',
      '\tif VCGSRules.OBJECT_ENTRIES.has(key):',
      '\t\t_on_codex_news(key)',
      '',
      '## Only a location with a codex entry is news for the codex.',
      'func _on_location_visited(key: String) -> void:',
      '\tif VCGSRules.LOCATIONS.has(key):',
      '\t\t_on_codex_news(key)',
      '',
      '## Only an item with a codex entry is news for the codex.',
      'func _on_item_found(key: String) -> void:',
      '\tif VCGSRules.ITEMS.has(key):',
      '\t\t_on_codex_news(key)',
      '',
      '## Only a character with a codex entry is news for the codex.',
      'func _on_character_met(key: String) -> void:',
      '\tif VCGSRules.CHARACTERS.has(key):',
      '\t\t_on_codex_news(key)',
      '',
      'func _refresh_codex_button() -> void:',
      '\tif _codex_button:',
      '\t\t_codex_button.text = "Codex (C)" if _codex_new == 0 else "Codex (C) · %d new" % _codex_new',
      '',
      '## Show some text and the buttons that go with it: each action is [label, Callable].',
      'func _show(words: String, actions: Array) -> void:',
      '\t_setup()',
      '\t_text.text = words',
      '\tfor child in _buttons.get_children():',
      '\t\t_buttons.remove_child(child)',
      '\t\tchild.queue_free()',
      '\t_labels = []',
      '\t_actions = []',
      '\tfor a in actions:',
      '\t\tvar button := Button.new()',
      '\t\tbutton.text = str(a[0])',
      '\t\tbutton.pressed.connect(a[1])',
      '\t\t_buttons.add_child(button)',
      '\t\t_labels.append(str(a[0]))',
      '\t\t_actions.append(a[1])',
      '',
      'func _on_event(event: Dictionary) -> void:',
      '\tvar kind := str(event.get("kind", ""))',
      '\tif kind == "freePlay" or kind == "choice" or kind == "trigger" or kind == "encounter":',
      '\t\treturn',
      '\tmode = "wait"',
      '\tif kind == "dialogue" and event.has("with"):',
      '\t\t# Dual dialogue: both voices at once.',
      '\t\t_show("%s\\n\\n    ‖ at the same time ‖\\n\\n%s" % [_voice(str(event.get("line", ""))), _voice(str(event["with"]))], [["Continue", flow.advance]])',
      '\telif kind == "dialogue":',
      '\t\t_show(_voice(str(event.get("line", ""))), [["Continue", flow.advance]])',
      '\telif kind == "cinematic":',
      '\t\t_show(_cinematic(str(event.get("ref", "")), str(event.get("label", ""))), [["Continue", flow.advance]])',
      '\telse:',
      '\t\t_show(str(event.get("label", "")), [["Continue", flow.advance]])',
      '',
      '## A line as the player reads it: who, how, and what they say.',
      'func _voice(line_id: String) -> String:',
      '\tvar line: Dictionary = VCGSDialogue.line(line_id)',
      '\tvar who := str(VCGSDialogue.SPEAKERS.get(line.get("speaker", ""), "NO SPEAKER")).to_upper()',
      '\tvar how := str(line.get("direction", ""))',
      '\treturn "%s%s\\n%s" % [who, ("  (" + how + ")") if how != "" else "", str(line.get("text", ""))]',
      '',
      'func _cinematic(ref: String, fallback: String) -> String:',
      '\tvar path := "%s/cinematics/%s.tres" % [generated_root, ref]',
      '\tif not ResourceLoader.exists(path):',
      '\t\treturn "[Cinematic] " + fallback',
      '\tvar c: Resource = load(path)',
      '\tvar out := "[Cinematic] %s · %ss" % [c.get("display_name"), str(c.get("seconds"))]',
      '\tvar n := 0',
      '\tfor s in c.get("shot_list"):',
      '\t\tn += 1',
      '\t\tout += "\\n  %d. %s · %s: %s (%ss)" % [n, s.get("framing", ""), s.get("move", ""), s.get("action", ""), str(s.get("seconds", 0))]',
      '\treturn out',
      '',
      'func _on_choice(_key: String, options: Array) -> void:',
      '\tmode = "choice"',
      '\tvar actions: Array = []',
      '\tfor i in options.size():',
      '\t\tvar pick: int = i',
      '\t\tactions.append([str(options[i]), func() -> void: flow.choose(pick)])',
      '\t_show("Choose:", actions)',
      '',
      '## An encounter: stand in for the fight with a Win and a Lose button.',
      'func _on_encounter(key: String, can_win: bool) -> void:',
      '\tmode = "encounter"',
      '\tvar path := "%s/encounters/%s.tres" % [generated_root, key]',
      '\tvar title := str(load(path).get("display_name")) if ResourceLoader.exists(path) else key',
      '\tvar actions: Array = []',
      '\tif can_win:',
      '\t\tactions.append(["Win", func() -> void: flow.win()])',
      '\tactions.append(["Lose", flow.lose])',
      '\t_show("[Encounter] %s%s" % [title, "" if can_win else " · can\'t be won yet"], actions)',
      '',
      'func _on_game_over(key: String) -> void:',
      '\t_end({ "outcome": "gameOver", "name": "lost to " + key })',
      '',
      'func _on_free_play(ends_when: String) -> void:',
      '\tmode = "free"',
      '\t_ends = ends_when',
      '\t_refresh_free()',
      '',
      'func _on_game_changed() -> void:',
      '\tif mode == "free":',
      '\t\t_refresh_free.call_deferred()',
      '',
      '## The objects in this scene the player can use right now.',
      'func _refresh_free() -> void:',
      '\tif mode != "free":',
      '\t\treturn',
      '\tvar actions: Array = []',
      '\tfor node in _interactables(get_parent()):',
      '\t\tvar thing: String = str(node.get_parent().get("label")) if node.get_parent().get("label") != null else str(node.get_parent().name)',
      '\t\tfor verb in node.available_verbs():',
      '\t\t\tvar target: Node = node',
      '\t\t\tvar v: String = verb',
      '\t\t\tactions.append(["%s %s" % [v, thing], func() -> void: target.interact(v)])',
      '\tactions.append(["Move on", flow.advance])',
      '\t_show(("Free play: ends when " + _ends) if _ends != "" else "Free play", actions)',
      '',
      '## Everything in this scene the player can use (the generated objects\' scripts).',
      'func _interactables(from: Node) -> Array[Node]:',
      '\tvar out: Array[Node] = []',
      '\tif from == null:',
      '\t\treturn out',
      '\tfor child in from.get_children():',
      '\t\tif child.has_method("available_verbs") and child.has_method("interact"):',
      '\t\t\tout.append(child)',
      '\t\tout.append_array(_interactables(child))',
      '\treturn out',
      '',
      'func _on_finished(next: String) -> void:',
      '\tvar here: Dictionary = VCGSStory.NODES.get(flow.scene_key(), {})',
      '\tif here.has("outcome"):',
      '\t\t_end(here)',
      '\t\treturn',
      '\tgo_to(next)',
      '',
      'func _end(node: Dictionary) -> void:',
      '\tmode = "end"',
      '\tvar how := "Game over" if str(node.get("outcome", "")) == "gameOver" else "The end"',
      '\t_show("%s: %s" % [how, node.get("name", "")], [])',
      '',
      '## Where a node goes: its first route whose conditions hold, else on along the spine.',
      'func _onward(node: Dictionary, game: VCGSGameState) -> String:',
      '\tfor route in node.get("routes", []):',
      '\t\tif VCGSRuleEngine.check(route.get("when", {}), game):',
      '\t\t\tVCGSRuleEngine.apply(route.get("effects", []), game)',
      '\t\t\treturn str(route.get("to", ""))',
      '\treturn str(node.get("onward", ""))',
      '',
      '## Follow the story graph from a node to the next thing to play.',
      'func go_to(key: String) -> void:',
      '\tmode = "story"',
      '\tvar game := _game()',
      '\tfor _step in 100:',
      '\t\tif key == "":',
      '\t\t\tmode = "end"',
      '\t\t\t_show("The end.", [])',
      '\t\t\treturn',
      '\t\tvar node: Dictionary = VCGSStory.NODES.get(key, {})',
      '\t\tif node.is_empty():',
      '\t\t\t_show("The story goes on to %s, which is not on the graph." % key, [])',
      '\t\t\treturn',
      '\t\tvar kind := str(node.get("kind", ""))',
      '\t\tvar title := str(node.get("name", key))',
      '\t\tif kind == "end" or (node.has("outcome") and kind != "scene"):',
      '\t\t\t_end(node)',
      '\t\t\treturn',
      '\t\tif kind == "scene":',
      '\t\t\tvar file := str(node.get("file", ""))',
      '\t\t\t_show("Next: " + title, [["Play " + title, func() -> void: (Engine.get_main_loop() as SceneTree).change_scene_to_file(file)]])',
      '\t\t\treturn',
      '\t\tif kind == "choice":',
      '\t\t\tvar choice_script: GDScript = load(str(node.get("script", "")))',
      '\t\t\tif not choice_script.available(game):',
      '\t\t\t\tkey = _onward(node, game)',
      '\t\t\t\tcontinue',
      '\t\t\tmode = "choice"',
      '\t\t\tvar actions: Array = []',
      '\t\t\tfor i in choice_script.offered(game):',
      '\t\t\t\tvar pick: int = i',
      '\t\t\t\tactions.append([str(choice_script.OPTIONS[i]["label"]), func() -> void: go_to(choice_script.choose(pick, game))])',
      '\t\t\tvar prompt := str(choice_script.PROMPT)',
      '\t\t\t_show(title + (("\\n" + prompt) if prompt != "" else ""), actions)',
      '\t\t\treturn',
      '\t\tif kind == "plotPoint" or kind == "cinematic":',
      '\t\t\tvar after := _onward(node, game)',
      '\t\t\tvar words := _cinematic(key, title) if kind == "cinematic" else title',
      '\t\t\t_show(words, [["Continue", func() -> void: go_to(after)]])',
      '\t\t\treturn',
      '\t\tkey = _onward(node, game)',
      '\t_show("The story goes round without stopping here.", [])',
    ]),
  ];
};

// ---------------------------------------------------------------- scenes

interface Placed {
  key: string;
  name: string;
  kind: string;
  color: string;
  /** An object's interactable script. */
  script?: string;
}

/** What each category of a scene's contents is, looked up in the IR. */
const lookup = (ir: HandoffIR, root: string) => {
  const by = (list: { ident: { key: string }; name: string }[], kind: string, extra: (x: never) => Partial<Placed> = () => ({})) =>
    new Map(list.map((x) => [x.ident.key, { key: x.ident.key, name: x.name, kind, color: COLORS[kind] ?? '#c8bfae', ...extra(x as never) }]));
  return {
    characters: new Map(ir.characters.map((c) => [c.ident.key, { key: c.ident.key, name: c.name, kind: 'character', color: c.color || COLORS.character! }])),
    environment: by(ir.locations, 'environment'),
    objects: new Map(ir.objects.filter((o) => o.kind === 'object').map((o) => [o.ident.key, { key: o.ident.key, name: o.name, kind: 'object', color: COLORS.object!, script: `res://${root}/objects/${o.ident.key}.gd` }])),
    puzzles: new Map(ir.objects.filter((o) => o.kind === 'puzzle').map((o) => [o.ident.key, { key: o.ident.key, name: o.name, kind: 'puzzle', color: COLORS.puzzle! }])),
    inventory: by(ir.items, 'inventory'),
    cinematics: by(ir.cinematics, 'cinematic'),
    choices: by(ir.choices, 'choice'),
    logic: new Map<string, Placed>([
      ...ir.flags.map((f): [string, Placed] => [f.ident.key, { key: f.ident.key, name: f.name, kind: 'state', color: COLORS.state! }]),
      ...ir.triggers.map((t): [string, Placed] => [t.ident.key, { key: t.ident.key, name: t.name, kind: t.kind, color: COLORS[t.kind]! }]),
    ]),
  } as Record<string, Map<string, Placed>>;
};

const nodeName = (key: string) =>
  key
    .split('_')
    .filter(Boolean)
    .map((w) => w[0]!.toUpperCase() + w.slice(1))
    .join('')
    .replace(/^(\d)/, 'N$1') || 'Element';

/** Where each group of placeholders sits in a 1152×648 window. */
const ROWS: { category: string; group: string; y: number; x0: number; step: number; size: [number, number] }[] = [
  { category: 'cinematics', group: 'Cinematics', y: 120, x0: 180, step: 160, size: [120, 60] },
  { category: 'characters', group: 'Characters', y: 250, x0: 120, step: 130, size: [70, 90] },
  { category: 'objects', group: 'Objects', y: 250, x0: 700, step: 140, size: [90, 80] },
  { category: 'inventory', group: 'Items', y: 360, x0: 700, step: 110, size: [60, 60] },
  { category: 'puzzles', group: 'Puzzles', y: 360, x0: 480, step: 120, size: [80, 70] },
  { category: 'choices', group: 'Choices', y: 360, x0: 120, step: 120, size: [60, 60] },
];

export const sceneTscn = (ir: HandoffIR, scene: IrScene, root: string): string => {
  const known = lookup(ir, root);
  const ext: { type: string; path: string; id: string }[] = [];
  const res = (path: string) => {
    let found = ext.find((e) => e.path === path);
    if (!found) ext.push((found = { type: 'Script', path, id: `${ext.length + 1}_script` }));
    return `ExtResource(${str(found.id)})`;
  };
  const flow = res(`res://${root}/scenes/${scene.ident.key}.gd`);
  const placeholder = res(`res://${RUNTIME}/placeholder.gd`);
  const player = res(`res://${RUNTIME}/debug_player.gd`);
  const nodes: string[] = [];
  const node = (name: string, type: string, parent: string | null, props: Record<string, string> = {}, groups: string[] = []) =>
    nodes.push(
      [
        `[node name=${str(name)} type=${str(type)}${parent !== null ? ` parent=${str(parent)}` : ''}${groups.length ? ` groups=[${groups.map(str).join(', ')}]` : ''}]`,
        ...Object.entries(props).map(([k, v]) => `${k} = ${v}`),
      ].join('\n'),
    );

  node(nodeName(scene.ident.key), 'Node2D', null);
  node('Flow', 'Node', '.', { script: flow });
  const location = (scene.contents['environment'] ?? []).map((k) => known['environment']!.get(k)).find(Boolean);
  node('Location', 'Node2D', '.', {
    position: 'Vector2(24, 24)',
    script: placeholder,
    kind: str('environment'),
    label: str(location ? `${location.name} · ${scene.slug}` : scene.slug),
    color: color(location?.color ?? COLORS.environment!),
    size: 'Vector2(1104, 380)',
  });

  for (const row of ROWS) {
    const placed = (scene.contents[row.category] ?? []).map((k) => known[row.category]!.get(k)).filter((p): p is Placed => !!p);
    if (!placed.length) continue;
    node(row.group, 'Node2D', '.');
    const used = new Set<string>();
    placed.forEach((p, i) => {
      let name = nodeName(p.key);
      for (let n = 2; used.has(name); n++) name = `${nodeName(p.key)}${n}`;
      used.add(name);
      node(name, 'Node2D', row.group, {
        position: `Vector2(${row.x0 + i * row.step}, ${row.y})`,
        script: placeholder,
        kind: str(p.kind),
        label: str(p.name),
        color: color(p.color),
        size: `Vector2(${row.size[0]}, ${row.size[1]})`,
      });
      if (p.script) node('Interactable', 'Node', `${row.group}/${name}`, { script: res(p.script) }, ['vcgs_interactable']);
    });
  }
  const logic = (scene.contents['logic'] ?? []).map((k) => known['logic']!.get(k)).filter((p): p is Placed => !!p);
  if (logic.length) {
    node('Logic', 'Node2D', '.');
    logic.forEach((p, i) =>
      node(nodeName(p.key), 'Node2D', 'Logic', {
        position: `Vector2(${520 + i * 110}, 120)`,
        script: placeholder,
        kind: str(p.kind),
        label: str(p.name),
        color: color(p.color),
        size: 'Vector2(50, 50)',
      }),
    );
  }
  node('DebugPlayer', 'CanvasLayer', '.', {
    script: player,
    flow_path: 'NodePath("../Flow")',
    scene_title: str(`${scene.code} ${scene.name}`.trim()),
    generated_root: str(`res://${root}`),
  });

  return [
    `[gd_scene load_steps=${ext.length + 1} format=3]`,
    '',
    ...ext.map((e) => `[ext_resource type=${str(e.type)} path=${str(e.path)} id=${str(e.id)}]`),
    '',
    nodes.join('\n\n'),
    '',
  ].join('\n');
};

/** Plays the whole story from its Beginning, scene after scene. */
export const storyTscn = (ir: HandoffIR, root: string): string =>
  [
    '[gd_scene load_steps=2 format=3]',
    '',
    `[ext_resource type="Script" path=${str(`res://${RUNTIME}/debug_player.gd`)} id="1_script"]`,
    '',
    '[node name="PlayStory" type="Node2D"]',
    '',
    '[node name="DebugPlayer" type="CanvasLayer" parent="."]',
    'script = ExtResource("1_script")',
    `scene_title = ${str(ir.project.name)}`,
    `generated_root = ${str(`res://${root}`)}`,
    'whole_story = true',
    '',
  ].join('\n');

/** The graph as the story player walks it: every node, its kind and name, where it goes, and its scene or choice file. */
export const storyNodes = (ir: HandoffIR, root: string): Record<string, Record<string, unknown>> =>
  Object.fromEntries(
    ir.graph.map((n) => [
      n.key,
      {
        kind: n.kind,
        name: n.name,
        onward: n.onward ?? '',
        routes: n.routes.map((r) => ({ to: r.to, label: r.label, ...(r.when ? { when: r.when } : {}), ...(r.effects ? { effects: r.effects } : {}) })),
        ...(n.outcome ? { outcome: n.outcome } : {}),
        ...(n.kind === 'scene' ? { file: `res://${root}/scenes/${n.key}.tscn` } : {}),
        ...(n.kind === 'choice' ? { script: `res://${root}/choices/${n.key}.gd` } : {}),
      },
    ]),
  );
