import type { IrNote } from './ir';
import { todoLines } from './notes';
import type { GeneratedFile } from './engines';
import { slabFaces, slabPrisms, type IrLevel, type IrLevelItem, type IrPiece } from './levels';

/**
 * Levels for Godot 4 (spec §11.2): a scene per level whose nodes are the
 * items, named by their export names and tagged with their GUIDs, holding
 * graybox meshes and collision; a generated script with the items' data;
 * and the VCGSLevel runtime that runs doors, pickups, volumes and rules on
 * GameState. play_<level>.tscn drops a first-person player in to walk it.
 */

export const RUNTIME = 'addons/vcgs_runtime';

const f = (n: number) => {
  const r = Math.round(n * 10000) / 10000;
  return Object.is(r, -0) ? '0' : String(r);
};

type M3 = [number, number, number, number, number, number, number, number, number];
const rotY = (deg: number): M3 => {
  const a = (deg * Math.PI) / 180;
  const c = Math.cos(a);
  const s = Math.sin(a);
  return [c, 0, s, 0, 1, 0, -s, 0, c];
};
const rotX = (deg: number): M3 => {
  const a = (deg * Math.PI) / 180;
  const c = Math.cos(a);
  const s = Math.sin(a);
  return [1, 0, 0, 0, c, -s, 0, s, c];
};
const mul = (a: M3, b: M3): M3 => {
  const out = new Array(9).fill(0) as M3;
  for (let i = 0; i < 3; i++) for (let j = 0; j < 3; j++) for (let k = 0; k < 3; k++) out[i * 3 + j] = out[i * 3 + j]! + a[i * 3 + k]! * b[k * 3 + j]!;
  return out;
};
/** Godot writes a Transform3D as its basis, row by row, then the origin. */
const transform = (m: M3, at: [number, number, number]) => `Transform3D(${[...m, ...at].map(f).join(', ')})`;
const color = (hex: string, alpha = 1): string => {
  const n = parseInt(hex.replace('#', '').slice(0, 6).padEnd(6, '0'), 16);
  return `Color(${f(((n >> 16) & 255) / 255)}, ${f(((n >> 8) & 255) / 255)}, ${f((n & 255) / 255)}, ${f(alpha)})`;
};
const str = (v: string) => JSON.stringify(v);

/** Node names: letters, digits and underscores (Godot refuses . : @ / " %). */
const nodeName = (name: string) => name.replace(/[.:@/"%]/g, '_') || 'Item';

// ---------------------------------------------------------------- the runtime

export const levelRuntime = (): GeneratedFile[] => [
  {
    path: `${RUNTIME}/level.gd`,
    kind: 'runtime',
    content: `${[
      '# VCGS Runtime for Godot 4.',
      'class_name VCGSLevel',
      'extends Node3D',
      '## A level from VC Game Studio. Its items are the nodes under it that carry',
      '## the metadata vcgs_guid; the generated script for the level holds their',
      '## data. Doors, pickups, volumes and rules run on GameState, the story\'s own',
      '## state, so the level and the story always agree. Your game answers the',
      '## signals (plays the cinematic, starts the scene, loads the next level).',
      '',
      'signal cinematic_requested(cinematic_key: String)',
      'signal scene_requested(scene_key: String)',
      'signal level_requested(level_key: String)',
      'signal spawn_requested(spawner: Node3D, actor_key: String, count: int)',
      'signal objective_changed(text: String)',
      'signal audio_requested(emitter: Node3D, sound: String)',
      'signal message_shown(text: String)',
      'signal checkpoint_reached(where: Vector3)',
      'signal story_object_used(object_key: String)',
      'signal player_died',
      '## An actor with a sight saw the player, or lost sight of them (its "spotted" / "lost" rules run too).',
      'signal actor_spotted(guid: String)',
      'signal actor_lost_sight(guid: String)',
      '## The player\'s light went on or off (spec §6).',
      'signal light_changed(on: bool)',
      '## A travel link was taken (spec V2 §13): where it ends, how, and the map it leads to ("" for this one).',
      'signal travel_requested(link_key: String, to_map: String, transition: String, to: Vector3)',
      '## A child map was loaded into this one, or taken out (spec V2 §12, §13).',
      'signal map_loaded(map_key: String, map: VCGSLevel)',
      'signal map_unloaded(map_key: String)',
      '',
      'const INTERACTIVE := ["door", "pickup", "inventory", "weapon", "ammo", "health", "npc", "companion", "neutral", "dialogue", "interaction", "puzzle", "elevator", "ladder"]',
      'const PICKUPS := ["pickup", "inventory", "weapon", "ammo", "health"]',
      '',
      'var game: VCGSGameState',
      '## Item GUID → its node.',
      'var nodes: Dictionary = {}',
      'var open: Dictionary = {}',
      'var unlocked: Dictionary = {}',
      'var gone: Dictionary = {}',
      'var enabled: Dictionary = {}',
      'var done: Dictionary = {}',
      'var inside: Dictionary = {}',
      'var timers: Dictionary = {}',
      'var objective := ""',
      'var health := 100.0',
      'var checkpoint := Vector3.ZERO',
      'var time := 0.0',
      '## Actors that move (patrols, companions) by GUID: where each is in level space, the stop it',
      '## walks to, and until when it waits.',
      'var actors: Dictionary = {}',
      '## Actors that see the player now (line of sight), by GUID.',
      'var seen: Dictionary = {}',
      '## Who companions follow: the node in the group "player" (VCGSLevelPlayer) unless set.',
      'var player: Node3D',
      '## How far behind a companion may fall before it catches up at once.',
      'const CATCH_UP := 12.0',
      '## The player\'s light (spec §6): whether it is on, and the seconds of fuel left (INF for ever).',
      'var light_on := false',
      'var light_fuel := INF',
      'var _light: Dictionary = {}',
      'var _data: Dictionary = {}',
      'var _depth := 0',
      '',
      '## Every item\'s data by GUID. The generated level script returns it.',
      'func level_data() -> Dictionary:',
      '\treturn {}',
      '',
      '## The player\'s light, from the player start: { source, fuel, range }. The generated level script returns it.',
      'func light_data() -> Dictionary:',
      '\treturn {}',
      '',
      '## Story keys → names, for messages.',
      'func story_names() -> Dictionary:',
      '\treturn {}',
      '',
      '## Where this map is in the hierarchy (spec V2 §4): its kind, parent, boundary, extent and the maps inside it. The generated level script returns it.',
      'func map_data() -> Dictionary:',
      '\treturn {}',
      '',
      '## Its travel links by key (spec V2 §13): points, ends, where they lead, locks. The generated level script returns them.',
      'func travel_data() -> Dictionary:',
      '\treturn {}',
      '',
      '## Child maps loaded into this one, by key.',
      'var maps: Dictionary = {}',
      '## Where the generated level scenes are; this scene\'s own folder unless set.',
      'var levels_dir := ""',
      '',
      'func _ready() -> void:',
      '\tif game == null:',
      '\t\tvar autoload := get_node_or_null("/root/GameState")',
      '\t\tif autoload is VCGSGameState:',
      '\t\t\tsetup(autoload)',
      '',
      '## Wire the level to the story\'s state (the GameState autoload unless given another).',
      'func setup(state: VCGSGameState) -> void:',
      '\tgame = state',
      '\t_data = level_data()',
      '\t_light = light_data()',
      '\tlight_fuel = _full_fuel()',
      '\tnodes.clear()',
      '\t_index(self)',
      '\t_dress_people()',
      '\tfor guid in nodes:',
      '\t\tvar node: Node = nodes[guid]',
      '\t\tif node is Area3D:',
      '\t\t\tvar area := node as Area3D',
      '\t\t\tif not area.body_entered.is_connected(_on_body_entered):',
      '\t\t\t\tarea.body_entered.connect(_on_body_entered.bind(guid))',
      '\t\t\t\tarea.body_exited.connect(_on_body_exited.bind(guid))',
      '\tif not game.changed.is_connected(_on_changed):',
      '\t\tgame.changed.connect(_on_changed)',
      '\tfor guid in _data:',
      '\t\tif role(guid) == "spawn" and str(item(guid).get("kind", "")) == "marker" and float(param(guid, "delay", 0.0)) <= 0.0 and is_present(guid):',
      '\t\t\t_spawn(guid)',
      '\trefresh()',
      '\t# Continuous children are part of this map from the start.',
      '\tfor child in child_maps():',
      '\t\tif str(child.get("boundary", "")) == "continuous" and child.get("placement") != null:',
      '\t\t\tload_map(str(child.get("key", "")))',
      '',
      '## Characters placed in the level show as stand-in figures (until final art replaces them).',
      'const PEOPLE := { "npc": Color(0.85, 0.38, 0.48), "enemy": Color(0.9, 0.28, 0.3), "companion": Color(0.37, 0.66, 0.83), "neutral": Color(0.6, 0.56, 0.48) }',
      '',
      '## In play, the designer\'s scaffolding stays out of sight, as in the studio\'s Play Mode: markers',
      '## (player start, patrol stops, spawns, cover…) and anything set not visible. They still show in the editor.',
      'func _dress_people() -> void:',
      '\tfor guid in nodes:',
      '\t\tvar node := nodes[guid] as Node3D',
      '\t\tif node == null or node.has_node("Art"):',
      '\t\t\tcontinue',
      '\t\tvar scaffold: bool = (str(item(guid).get("kind", "")) == "marker" and not PEOPLE.has(role(guid))) or (str(item(guid).get("kind", "")) != "space" and param(guid, "visible", true) == false)',
      '\t\tif scaffold and node.get_node_or_null("Proxy") is Node3D:',
      '\t\t\t(node.get_node("Proxy") as Node3D).visible = false',
      '\t\tif not PEOPLE.has(role(guid)) or node.has_node("Figure"):',
      '\t\t\tcontinue',
      '\t\tvar proxy := node.get_node_or_null("Proxy") as Node3D',
      '\t\tif proxy != null:',
      '\t\t\tproxy.visible = false',
      '\t\tnode.add_child(VCGSFigure.build(PEOPLE[role(guid)]))',
      '',
      'func _index(node: Node) -> void:',
      '\tfor child in node.get_children():',
      '\t\tif child.has_meta("vcgs_guid"):',
      '\t\t\tnodes[str(child.get_meta("vcgs_guid"))] = child',
      '\t\t_index(child)',
      '',
      'func item(guid: String) -> Dictionary:',
      '\treturn _data.get(guid, {})',
      '',
      'func role(guid: String) -> String:',
      '\treturn str(item(guid).get("role", ""))',
      '',
      'func param(guid: String, key: String, fallback: Variant = null) -> Variant:',
      '\treturn item(guid).get("params", {}).get(key, fallback)',
      '',
      'func story_name(key: String) -> String:',
      '\treturn str(story_names().get(key, key))',
      '',
      '## The GUID of the item with this export name (the node\'s name), or "".',
      'func guid_of(export_name: String) -> String:',
      '\tfor guid in _data:',
      '\t\tif str(_data[guid].get("export_name", "")) == export_name:',
      '\t\t\treturn guid',
      '\treturn ""',
      '',
      '## Not taken, not switched off, and its "present only when" holds.',
      'func is_present(guid: String) -> bool:',
      '\tif gone.has(guid) or enabled.get(guid, true) == false:',
      '\t\treturn false',
      '\treturn VCGSRuleEngine.check(item(guid).get("active_when", {}), game)',
      '',
      'func is_open(guid: String) -> bool:',
      '\tif open.has(guid):',
      '\t\treturn bool(open[guid])',
      '\treturn bool(param(guid, "startsOpen", false)) or str(param(guid, "swing", "")) == "open archway"',
      '',
      '## Show what is there, hide what is not, open and shut doors. Runs after every change.',
      'func refresh() -> void:',
      '\tfor guid in nodes:',
      '\t\tvar node := nodes[guid] as Node3D',
      '\t\tif node == null:',
      '\t\t\tcontinue',
      '\t\tvar here := is_present(guid)',
      '\t\tnode.visible = here',
      '\t\t_switch(node, here)',
      '\t\tif role(guid) == "door":',
      '\t\t\tvar shut := here and not is_open(guid)',
      '\t\t\tfor part in ["Proxy", "Art", "Collision"]:',
      '\t\t\t\tvar child := node.get_node_or_null(part)',
      '\t\t\t\tif child is Node3D:',
      '\t\t\t\t\t(child as Node3D).visible = shut',
      '\t\t\t\t\t_switch(child, shut)',
      '',
      'func _switch(node: Node, on: bool) -> void:',
      '\tif node is CollisionShape3D:',
      '\t\t(node as CollisionShape3D).set_deferred("disabled", not on)',
      '\tif node is Area3D:',
      '\t\t(node as Area3D).set_deferred("monitoring", on)',
      '\tfor child in node.get_children():',
      '\t\tif not child.has_meta("vcgs_guid"):',
      '\t\t\t_switch(child, on)',
      '',
      '## What Interact would do to an item now: { verb, label } and "blocked" when it can\'t; {} for nothing.',
      'func offer(guid: String) -> Dictionary:',
      '\tif not is_present(guid):',
      '\t\treturn {}',
      '\tvar it := item(guid)',
      '\tvar has_rules := false',
      '\tfor rule in it.get("rules", []):',
      '\t\tif str(rule.get("on", "")) in ["interact", "use", "pickup"]:',
      '\t\t\thas_rules = true',
      '\tvar interactive: Variant = param(guid, "interactive", null)',
      '\tif interactive == false and not has_rules:',
      '\t\treturn {}',
      '\tif not (interactive == true or has_rules or role(guid) in INTERACTIVE):',
      '\t\treturn {}',
      '\tvar prompt := str(param(guid, "prompt", ""))',
      '\tif prompt == "":',
      '\t\tprompt = "Use"',
      '\tvar label := str(it.get("name", ""))',
      '\tif too_dark(guid):',
      '\t\tvar source := str(_light.get("source", ""))',
      '\t\treturn { "verb": prompt, "label": label, "blocked": "Too dark to see. Turn your light on (L)." if has_light_source() else ("Too dark to see." + ((" It needs " + story_name(source) + " for light.") if source != "" else "")) }',
      '\tif role(guid) == "door":',
      '\t\tif str(param(guid, "swing", "")) == "open archway":',
      '\t\t\treturn {}',
      '\t\tvar key := str(param(guid, "keyItem", ""))',
      '\t\tvar locked := bool(param(guid, "locked", false)) and not unlocked.has(guid)',
      '\t\tvar is_now_open := is_open(guid)',
      '\t\tif not is_now_open and locked and key != "" and not game.has_item(key):',
      '\t\t\treturn { "verb": prompt, "label": label, "blocked": "Locked. Needs " + story_name(key) + "." }',
      '\t\tif not is_now_open and locked and key == "":',
      '\t\t\treturn { "verb": prompt, "label": label, "blocked": "Locked." }',
      '\t\treturn { "verb": "Close" if is_now_open else (prompt if locked else "Open"), "label": label }',
      '\treturn { "verb": prompt, "label": label }',
      '',
      '## The player uses an item. Returns what to tell them ("" for nothing to say).',
      'func interact(guid: String) -> String:',
      '\tvar o := offer(guid)',
      '\tif o.is_empty():',
      '\t\treturn ""',
      '\tif o.has("blocked"):',
      '\t\tmessage_shown.emit(o["blocked"])',
      '\t\treturn str(o["blocked"])',
      '\tvar said := ""',
      '\tvar it := item(guid)',
      '\tif role(guid) == "door":',
      '\t\tvar was_open := is_open(guid)',
      '\t\tif not was_open and bool(param(guid, "locked", false)):',
      '\t\t\tunlocked[guid] = true',
      '\t\topen[guid] = not was_open',
      '\t\trefresh()',
      '\telif role(guid) in PICKUPS and param(guid, "collectible", true) != false:',
      '\t\tgone[guid] = true',
      '\t\tvar gives := str(param(guid, "item", ""))',
      '\t\tif role(guid) == "health":',
      '\t\t\thealth = min(100.0, health + float(param(guid, "value", 25)))',
      '\t\tvar rules_give := false',
      '\t\tfor rule in it.get("rules", []):',
      '\t\t\tif str(rule.get("on", "")) == "pickup":',
      '\t\t\t\tfor e in rule.get("effects", []):',
      '\t\t\t\t\tif str(e.get("kind", "")) == "give" and str(e.get("ref", "")) == gives:',
      '\t\t\t\t\t\trules_give = true',
      '\t\tif gives != "" and not rules_give:',
      '\t\t\tgame.give_item(gives, int(param(guid, "quantity", 1)))',
      '\t\tsaid = "Took " + (story_name(gives) if gives != "" else str(it.get("name", "")))',
      '\t\trun_rules(guid, "pickup")',
      '\t\trefresh()',
      '\telif role(guid) in ["npc", "companion", "neutral", "dialogue"]:',
      '\t\tvar scenes: Array = it.get("scenes", [])',
      '\t\tvar scene := str(scenes[0]) if not scenes.is_empty() else ""',
      '\t\tif scene != "":',
      '\t\t\tgame.visit(scene)',
      '\t\t\tscene_requested.emit(scene)',
      '\telse:',
      '\t\tvar own := false',
      '\t\tfor rule in it.get("rules", []):',
      '\t\t\tif str(rule.get("on", "")) == "interact":',
      '\t\t\t\town = true',
      '\t\tif not own:',
      '\t\t\tfor link in it.get("links", []):',
      '\t\t\t\tstory_object_used.emit(str(link))',
      '\trun_rules(guid, "interact")',
      '\trun_rules(guid, "use")',
      '\tif said != "":',
      '\t\tmessage_shown.emit(said)',
      '\treturn said',
      '',
      '## The player comes into a volume.',
      'func enter(guid: String) -> void:',
      '\tif inside.has(guid) or not is_present(guid):',
      '\t\treturn',
      '\tinside[guid] = true',
      '\tvar once := bool(param(guid, "once", false))',
      '\tif once and done.has(guid):',
      '\t\treturn',
      '\tif once:',
      '\t\tdone[guid] = true',
      '\tvar plays := false',
      '\tfor rule in item(guid).get("rules", []):',
      '\t\tfor a in rule.get("actions", []):',
      '\t\t\tif str(a.get("kind", "")) == "playCinematic":',
      '\t\t\t\tplays = true',
      '\tvar cinematic := str(param(guid, "cinematic", ""))',
      '\tif role(guid) == "cinematic" and cinematic != "" and not plays:',
      '\t\tcinematic_requested.emit(cinematic)',
      '\tif role(guid) == "checkpoint":',
      '\t\tcheckpoint = (nodes[guid] as Node3D).global_position',
      '\t\tcheckpoint_reached.emit(checkpoint)',
      '\tif role(guid) == "portal" and str(param(guid, "to", "")) != "":',
      '\t\tlevel_requested.emit(str(param(guid, "to", "")))',
      '\tif role(guid) == "spawn" and not done.has(guid):',
      '\t\t_spawn(guid)',
      '\trun_rules(guid, "enter")',
      '',
      'func exit(guid: String) -> void:',
      '\tif not inside.has(guid):',
      '\t\treturn',
      '\tinside.erase(guid)',
      '\trun_rules(guid, "exit")',
      '',
      'func _process(delta: float) -> void:',
      '\tif game == null:',
      '\t\treturn',
      '\ttime += delta',
      '\t_stream()',
      '\t_move_actors(delta)',
      '\t_watch()',
      '\t_approach_doors()',
      '\t_burn_light(delta)',
      '\tfor guid in inside:',
      '\t\tif role(guid) in ["hazard", "damage"] and is_present(guid):',
      '\t\t\tif bool(param(guid, "kills", false)):',
      '\t\t\t\thealth = 0.0',
      '\t\t\telse:',
      '\t\t\t\thealth -= float(param(guid, "damage", 0)) * delta',
      '\tif health <= 0.0 and time > 0.0:',
      '\t\thealth = 100.0',
      '\t\tplayer_died.emit()',
      '\tfor guid in _data:',
      '\t\tif not is_present(guid):',
      '\t\t\tcontinue',
      '\t\tif role(guid) == "spawn" and str(item(guid).get("kind", "")) == "marker" and not done.has(guid) and float(param(guid, "delay", 0.0)) <= time:',
      '\t\t\t_spawn(guid)',
      '\t\tvar n := 0',
      '\t\tfor rule in item(guid).get("rules", []):',
      '\t\t\tn += 1',
      '\t\t\tif str(rule.get("on", "")) != "timer":',
      '\t\t\t\tcontinue',
      '\t\t\tvar id: String = str(guid) + ":" + str(n)',
      '\t\t\tvar every: float = max(0.5, float(str(rule.get("detail", "5"))))',
      '\t\t\tif time - float(timers.get(id, 0.0)) >= every:',
      '\t\t\t\ttimers[id] = time',
      '\t\t\t\t_run(guid, rule)',
      '',
      '## The light\'s full fuel: its seconds, or INF when it never runs out.',
      'func _full_fuel() -> float:',
      '\tvar fuel := float(_light.get("fuel", 0))',
      '\treturn fuel if fuel > 0.0 else INF',
      '',
      '## Whether the player has what lights their light: its story item carried, or its mechanic available.',
      'func has_light_source() -> bool:',
      '\tvar source := str(_light.get("source", ""))',
      '\treturn source != "" and game != null and (game.has_item(source) or game.has_mechanic(source))',
      '',
      'func is_lit() -> bool:',
      '\treturn light_on and has_light_source()',
      '',
      '## Turn the player\'s light on or off (L): only with its source, and with fuel left. Returns what to tell them.',
      'func toggle_light() -> String:',
      '\tvar text := ""',
      '\tvar source := str(_light.get("source", ""))',
      '\tif light_on:',
      '\t\tlight_on = false',
      '\t\tlight_changed.emit(false)',
      '\t\ttext = "Light off."',
      '\telif source == "":',
      '\t\ttext = "You have no light here."',
      '\telif not has_light_source():',
      '\t\ttext = "You need " + story_name(source) + " for light."',
      '\telif light_fuel <= 0.0:',
      '\t\ttext = "Your light has no fuel left."',
      '\telse:',
      '\t\tlight_on = true',
      '\t\tlight_changed.emit(true)',
      '\t\ttext = "Light on."',
      '\tmessage_shown.emit(text)',
      '\treturn text',
      '',
      '## Gear, skills and crafting (spec §8): what the player can do now, in the order the',
      '## studio\'s Play Mode lists it: each item of equipment carried (Use and Put away when',
      '## equipped, else Equip), each skill (Learn), each recipe (Craft), with why not ("" when it can).',
      '## Each is { "act", "key", "label", "why" }.',
      'func gear_menu() -> Array:',
      '\tvar out: Array = []',
      '\tif game == null:',
      '\t\treturn out',
      '\tfor key in VCGSRules.EQUIPMENT:',
      '\t\tif not game.has_item(key):',
      '\t\t\tcontinue',
      '\t\tvar name := str(VCGSRules.EQUIPMENT[key]["name"])',
      '\t\tif game.is_equipped(key):',
      '\t\t\tout.append({ "act": "use", "key": key, "label": "Use " + name, "why": VCGSRules.use_check(key, game) })',
      '\t\t\tout.append({ "act": "unequip", "key": key, "label": "Put away " + name, "why": "" })',
      '\t\telse:',
      '\t\t\tout.append({ "act": "equip", "key": key, "label": "Equip " + name, "why": VCGSRules.equip_check(key, game) })',
      '\tfor key in VCGSRules.SKILLS:',
      '\t\tout.append({ "act": "learn", "key": key, "label": "Learn " + str(VCGSRules.SKILLS[key]["name"]), "why": VCGSRules.learn_check(key, game) })',
      '\tfor key in VCGSRules.RECIPES:',
      '\t\tout.append({ "act": "craft", "key": key, "label": "Craft " + str(VCGSRules.RECIPES[key]["name"]), "why": VCGSRules.craft_check(key, game) })',
      '\treturn out',
      '',
      '## The gear screen as text: GEAR, then each option numbered, with why not in brackets.',
      'func gear_text() -> String:',
      '\tvar lines: Array = ["GEAR"]',
      '\tvar menu := gear_menu()',
      '\tif menu.is_empty():',
      '\t\tlines.append("Nothing to equip, learn or craft.")',
      '\tfor i in menu.size():',
      '\t\tvar why := str(menu[i]["why"])',
      '\t\tlines.append("%d. %s%s" % [i + 1, menu[i]["label"], (" (" + why + ")") if why != "" else ""])',
      '\treturn "\\n".join(lines)',
      '',
      '## Do one: equip, put away, use, learn or craft, by the story\'s rules. Returns what to tell',
      '## the player ("Equipped Diving Knife", "Crafted 2 × Flare", or why not), as the studio says it.',
      'func gear_do(act: String, key: String) -> String:',
      '\tif game == null:',
      '\t\treturn ""',
      '\tvar why := ""',
      '\tvar name := _gear_name(key)',
      '\tvar done := ""',
      '\tmatch act:',
      '\t\t"equip":',
      '\t\t\twhy = VCGSRules.equip(key, game)',
      '\t\t\tdone = "Equipped " + name',
      '\t\t"unequip":',
      '\t\t\twhy = VCGSRules.unequip(key, game)',
      '\t\t\tdone = "Put away " + name',
      '\t\t"use":',
      '\t\t\twhy = VCGSRules.use_item(key, game)',
      '\t\t\tdone = "Used " + name',
      '\t\t"learn":',
      '\t\t\twhy = VCGSRules.learn(key, game)',
      '\t\t\tdone = "Learned " + name',
      '\t\t"craft":',
      '\t\t\twhy = VCGSRules.craft(key, game)',
      '\t\t\tvar makes := int(VCGSRules.RECIPES.get(key, {}).get("makes", 1))',
      '\t\t\tdone = "Crafted " + (("%d × " % makes) if makes > 1 else "") + name',
      '\t\t_:',
      '\t\t\twhy = "Nothing to do."',
      '\tvar text := why if why != "" else done',
      '\tmessage_shown.emit(text)',
      '\treturn text',
      '',
      'func _gear_name(key: String) -> String:',
      '\tfor table in [VCGSRules.EQUIPMENT, VCGSRules.SKILLS, VCGSRules.RECIPES, VCGSRules.ITEMS]:',
      '\t\tif table.has(key):',
      '\t\t\treturn str(table[key].get("name", key))',
      '\treturn story_name(key)',
      '',
      '## What is in the player\'s hand ("" for nothing).',
      'func in_hand() -> String:',
      '\treturn game.equipped_in("Hand") if game != null else ""',
      '',
      '## Use what is in the hand (R), as Use on the gear screen.',
      'func use_in_hand() -> String:',
      '\tvar key := in_hand()',
      '\tif key == "":',
      '\t\tmessage_shown.emit("Nothing in hand.")',
      '\t\treturn "Nothing in hand."',
      '\treturn gear_do("use", key)',
      '',
      '## The light burns its fuel while on, and goes out when that runs out or its source is gone.',
      'func _burn_light(delta: float) -> void:',
      '\tif not light_on:',
      '\t\treturn',
      '\tif not has_light_source():',
      '\t\tlight_on = false',
      '\t\tlight_changed.emit(false)',
      '\t\tmessage_shown.emit("Your light goes out.")',
      '\telif light_fuel != INF:',
      '\t\tlight_fuel = maxf(0.0, light_fuel - delta)',
      '\t\tif light_fuel <= 0.0:',
      '\t\t\tlight_on = false',
      '\t\t\tlight_changed.emit(false)',
      '\t\t\tmessage_shown.emit("Your light goes out: no fuel left.")',
      '',
      '## How dark it is where the player is (0 to 1): the darkest darkness zone they are in.',
      'func darkness() -> float:',
      '\tvar dark := 0.0',
      '\tfor guid in inside:',
      '\t\tif role(guid) == "darkness" and is_present(guid):',
      '\t\t\tdark = maxf(dark, clampf(float(param(guid, "dark", 92)) / 100.0, 0.0, 1.0))',
      '\treturn dark',
      '',
      '## Whether an item is lost in the dark: in a darkness zone that is here, with the light off.',
      'func too_dark(guid: String) -> bool:',
      '\tif is_lit():',
      '\t\treturn false',
      '\tfor zone in item(guid).get("in_dark", []):',
      '\t\tif is_present(str(zone)):',
      '\t\t\treturn true',
      '\treturn false',
      '',
      '## Line of sight (the same rules as the studio\'s Play Mode): an actor whose "sight" is',
      '## over 0 sees the player within that range and its field of view ("fov", degrees, about',
      '## the way it faces), with nothing solid in the way at eye height.',
      'func _watch() -> void:',
      '\tvar who: Node3D = player',
      '\tif who == null and is_inside_tree():',
      '\t\twho = get_tree().get_first_node_in_group("player") as Node3D',
      '\tif who == null:',
      '\t\treturn',
      '\tfor guid in _data:',
      '\t\tvar reach := float(param(guid, "sight", 0))',
      '\t\tif reach <= 0.0 or not nodes.has(guid) or not is_present(guid):',
      '\t\t\tif seen.has(guid):',
      '\t\t\t\tseen.erase(guid)',
      '\t\t\tcontinue',
      '\t\tvar node := nodes[guid] as Node3D',
      '\t\tvar eye := node.global_position + Vector3.UP * 1.6',
      '\t\tvar target := who.global_position + Vector3.UP * 1.6',
      '\t\tvar sees := eye.distance_to(target) <= reach and _in_view(node, target, float(param(guid, "fov", 90))) and _clear(eye, target, [node, who])',
      '\t\tif sees and not seen.has(guid):',
      '\t\t\tseen[guid] = true',
      '\t\t\tactor_spotted.emit(guid)',
      '\t\t\trun_rules(guid, "spotted")',
      '\t\telif not sees and seen.has(guid):',
      '\t\t\tseen.erase(guid)',
      '\t\t\tactor_lost_sight.emit(guid)',
      '\t\t\trun_rules(guid, "lost")',
      '',
      'func _in_view(node: Node3D, target: Vector3, fov: float) -> bool:',
      '\tif fov >= 360.0:',
      '\t\treturn true',
      '\tvar to := target - node.global_position',
      '\tto.y = 0.0',
      '\tif to.length() < 0.001:',
      '\t\treturn true',
      '\tvar facing := -node.global_transform.basis.z',
      '\tfacing.y = 0.0',
      '\treturn facing.normalized().dot(to.normalized()) >= cos(deg_to_rad(fov / 2.0)) - 0.000001',
      '',
      'func _clear(from: Vector3, to: Vector3, skip: Array) -> bool:',
      '\tif not is_inside_tree():',
      '\t\treturn true',
      '\tvar query := PhysicsRayQueryParameters3D.create(from, to)',
      '\tvar exclude: Array[RID] = []',
      '\tfor n in skip:',
      '\t\tif n is CollisionObject3D:',
      '\t\t\texclude.append((n as CollisionObject3D).get_rid())',
      '\tquery.exclude = exclude',
      '\treturn get_world_3d().direct_space_state.intersect_ray(query).is_empty()',
      '',
      '## Walking up to a closed door opens it, as interact() would, or says why it won\'t: once',
      '## each approach (as the studio\'s Play Mode). A door\'s "autoOpen" turned off waits for E.',
      'var at_doors: Dictionary = {}',
      '',
      'func _approach_doors() -> void:',
      '\tvar who: Node3D = player',
      '\tif who == null and is_inside_tree():',
      '\t\twho = get_tree().get_first_node_in_group("player") as Node3D',
      '\tif who == null:',
      '\t\treturn',
      '\tvar near: Dictionary = {}',
      '\tfor guid in _data:',
      '\t\tif role(guid) != "door" or not nodes.has(guid) or not is_present(guid):',
      '\t\t\tcontinue',
      '\t\tvar door := nodes[guid] as Node3D',
      '\t\tvar size: Array = item(guid).get("size", [1.2, 2.2, 0.2])',
      '\t\t# In the level\'s own space, as the patrols are.',
      '\t\tvar at := _parent_in_level(door) * door.position',
      '\t\tvar me := _parent_in_level(who) * who.position',
      '\t\tif absf(me.y - at.y) > 1.0 or Vector2(me.x - at.x, me.z - at.z).length() > maxf(1.1, float(size[0]) / 2.0 + 0.4):',
      '\t\t\tcontinue',
      '\t\tnear[guid] = true',
      '\t\tif at_doors.has(guid) or is_open(guid) or param(guid, "autoOpen", true) == false:',
      '\t\t\tcontinue',
      '\t\tinteract(guid)',
      '\tat_doors = near',
      '',
      '## What the player is at (as the studio\'s Play Mode): a ladder within reach, and how deep',
      '## the water around their feet is (0 for none).',
      'func traversal_at(world_pos: Vector3) -> Dictionary:',
      '\tvar at := global_transform.affine_inverse() * world_pos',
      '\tvar out := { "ladder": false, "depth": 0.0 }',
      '\tfor guid in _data:',
      '\t\tvar r := role(guid)',
      '\t\tif (r != "ladder" and r != "water") or not is_present(guid):',
      '\t\t\tcontinue',
      '\t\tvar it := item(guid)',
      '\t\tvar p: Array = it.get("position", [0, 0, 0])',
      '\t\tvar size: Array = it.get("size", [1, 1, 1])',
      '\t\tvar frame := Transform3D(Basis(Vector3.UP, deg_to_rad(float(it.get("turn", 0)))), Vector3(float(p[0]), float(p[1]), float(p[2])))',
      '\t\tvar l := frame.affine_inverse() * at',
      '\t\tvar reach := 0.2 if r == "ladder" else 0.0',
      '\t\tif absf(l.x) > float(size[0]) / 2.0 + reach or absf(l.z) > float(size[2]) / 2.0 + reach * 2.25:',
      '\t\t\tcontinue',
      '\t\tif l.y < (-0.2 if r == "ladder" else -0.25) or l.y > float(size[1]):',
      '\t\t\tcontinue',
      '\t\tif r == "ladder":',
      '\t\t\tout["ladder"] = true',
      '\t\telse:',
      '\t\t\tout["depth"] = maxf(float(out["depth"]), float(size[1]) - l.y)',
      '\treturn out',
      '',
      '## Stamina (spec §6), when the level\'s player start tracks it: running, swimming and climbing',
      '## spend it, resting wins it back; out of it the player can\'t run, and swimming starts to drown them.',
      'var stamina := 100.0',
      'signal exhausted',
      '',
      'func tracks_stamina() -> bool:',
      '\tfor guid in _data:',
      '\t\tif role(guid) == "playerStart":',
      '\t\t\treturn bool(param(guid, "stamina", false))',
      '\treturn false',
      '',
      'func spend_stamina(delta: float, run: bool, swim: bool, climb: bool) -> void:',
      '\tif not tracks_stamina():',
      '\t\treturn',
      '\tvar before := stamina',
      '\tvar cost := (15.0 if run else 0.0) + (6.0 if swim else 0.0) + (8.0 if climb else 0.0)',
      '\tstamina = clampf(stamina - cost * delta if cost > 0.0 else stamina + 12.0 * delta, 0.0, 100.0)',
      '\tif before > 0.0 and stamina == 0.0:',
      '\t\texhausted.emit()',
      '\t\tmessage_shown.emit("You\'re exhausted.")',
      '\tif swim and stamina == 0.0:',
      '\t\thealth -= 15.0 * delta',
      '',
      '## Walk the patrols on and bring the companions after the player (the same rules as',
      '## the studio\'s Play Mode): each actor\'s node goes where its pose is.',
      'func _move_actors(delta: float) -> void:',
      '\tfor guid in _data:',
      '\t\tvar motion: Dictionary = item(guid).get("motion", {})',
      '\t\t# While it sees the player, an actor does what its "onSight" says: chase, watch, or carry on.',
      '\t\tvar reaction := str(param(guid, "onSight", "carry on")) if seen.has(guid) else "carry on"',
      '\t\tif (motion.is_empty() and reaction == "carry on") or not nodes.has(guid) or not is_present(guid):',
      '\t\t\tcontinue',
      '\t\tvar node := nodes[guid] as Node3D',
      '\t\tvar parent := _parent_in_level(node)',
      '\t\tif not actors.has(guid):',
      '\t\t\tactors[guid] = { "at": parent * node.position, "stop": 0, "until": 0.0, "moving": false }',
      '\t\tvar pose: Dictionary = actors[guid]',
      '\t\tif reaction != "carry on":',
      '\t\t\tvar seer: Node3D = player',
      '\t\t\tif seer == null and is_inside_tree():',
      '\t\t\t\tseer = get_tree().get_first_node_in_group("player") as Node3D',
      '\t\t\tif seer != null:',
      '\t\t\t\tstep_reaction(pose, reaction, float(param(guid, "chaseSpeed", 3.5)), delta, _parent_in_level(seer) * seer.position)',
      '\t\telif str(motion.get("kind", "")) == "patrol":',
      '\t\t\tstep_patrol(pose, motion, delta, time)',
      '\t\telse:',
      '\t\t\tvar who: Node3D = player',
      '\t\t\tif who == null and is_inside_tree():',
      '\t\t\t\twho = get_tree().get_first_node_in_group("player") as Node3D',
      '\t\t\tif who == null:',
      '\t\t\t\tcontinue',
      '\t\t\tstep_follow(pose, motion, delta, _parent_in_level(who) * who.position)',
      '\t\tnode.position = parent.affine_inverse() * (pose["at"] as Vector3)',
      '\t\tif pose.has("facing"):',
      '\t\t\tvar facing: Vector3 = pose["facing"]',
      '\t\t\tnode.rotation.y = atan2(-facing.x, -facing.z)',
      '',
      '## A node\'s parent\'s transform in the level\'s space (the level\'s own for its direct children;',
      '## a node elsewhere in the scene through the world, when the level is in the tree).',
      'func _parent_in_level(node: Node3D) -> Transform3D:',
      '\tvar t := Transform3D.IDENTITY',
      '\tvar p := node.get_parent()',
      '\twhile p != null and p != self:',
      '\t\tif p is Node3D:',
      '\t\t\tt = (p as Node3D).transform * t',
      '\t\tp = p.get_parent()',
      '\tif p == null and is_inside_tree() and node.is_inside_tree():',
      '\t\treturn global_transform.affine_inverse() * (node.get_parent() as Node3D).global_transform if node.get_parent() is Node3D else global_transform.affine_inverse()',
      '\treturn t',
      '',
      '## Walk a pose toward target (level space) at most by metres; true when it gets there.',
      'static func _walk(pose: Dictionary, target: Vector3, by: float) -> bool:',
      '\tvar at: Vector3 = pose["at"]',
      '\tvar to := target - at',
      '\tvar flat := Vector3(to.x, 0.0, to.z)',
      '\tvar d := flat.length()',
      '\tif d > 0.000001:',
      '\t\tpose["facing"] = flat',
      '\tif d <= by or d < 0.000001:',
      '\t\tpose["at"] = target',
      '\t\tpose["moving"] = d > 0.000001',
      '\t\treturn true',
      '\tpose["at"] = at + to * (by / d)',
      '\tpose["moving"] = true',
      '\treturn false',
      '',
      '## One patrol step: wait at a stop, else walk on to it; arriving starts the wait and aims at',
      '## the next stop, round and round. now is the level\'s time after the step.',
      'static func step_patrol(pose: Dictionary, motion: Dictionary, delta: float, now: float) -> void:',
      '\tif now < float(pose.get("until", 0.0)):',
      '\t\tpose["moving"] = false',
      '\t\treturn',
      '\tvar stops: Array = motion.get("stops", [])',
      '\tif stops.is_empty():',
      '\t\treturn',
      '\tvar stop: Dictionary = stops[int(pose.get("stop", 0)) % stops.size()]',
      '\tvar at: Array = stop.get("at", [0, 0, 0])',
      '\tif _walk(pose, Vector3(float(at[0]), float(at[1]), float(at[2])), float(motion.get("speed", 1.4)) * delta):',
      '\t\tpose["moving"] = false',
      '\t\tpose["until"] = now + float(stop.get("wait", 0.0))',
      '\t\tpose["stop"] = (int(pose.get("stop", 0)) + 1) % stops.size()',
      '',
      '## One follow step: keep within the follow distance of the player at to (level space),',
      '## faster when far; more than CATCH_UP behind, or another floor, and it catches up at once.',
      'static func step_follow(pose: Dictionary, motion: Dictionary, delta: float, to: Vector3) -> void:',
      '\tvar at: Vector3 = pose["at"]',
      '\tvar flat := Vector3(to.x - at.x, 0.0, to.z - at.z)',
      '\tvar d := flat.length()',
      '\tvar distance := float(motion.get("distance", 2.0))',
      '\tif d > 0.000001:',
      '\t\tpose["facing"] = flat',
      '\tif d > CATCH_UP or absf(to.y - at.y) > 3.0:',
      '\t\tvar back := flat * (distance / d) if d > 0.000001 else Vector3(0.0, 0.0, distance)',
      '\t\tpose["at"] = Vector3(to.x - back.x, to.y, to.z - back.z)',
      '\t\tpose["moving"] = false',
      '\telif d <= distance:',
      '\t\tpose["moving"] = false',
      '\telse:',
      '\t\tvar speed := float(motion.get("speed", 3.5)) * (1.6 if d > distance * 2.5 else 1.0)',
      '\t\t_walk(pose, Vector3(at.x + flat.x * (d - distance) / d, to.y, at.z + flat.z * (d - distance) / d), speed * delta)',
      '',
      '## While an actor sees the player: face them, and for a chase close in to arm\'s reach (1 m) at its chase speed.',
      'static func step_reaction(pose: Dictionary, reaction: String, speed: float, delta: float, to: Vector3) -> void:',
      '\tvar at: Vector3 = pose["at"]',
      '\tvar flat := Vector3(to.x - at.x, 0.0, to.z - at.z)',
      '\tvar d := flat.length()',
      '\tif d > 0.000001:',
      '\t\tpose["facing"] = flat',
      '\tif reaction != "chase" or d <= 1.0:',
      '\t\tpose["moving"] = false',
      '\t\treturn',
      '\t_walk(pose, Vector3(at.x + flat.x * (d - 1.0) / d, to.y, at.z + flat.z * (d - 1.0) / d), maxf(0.1, speed) * delta)',
      '',
      '## Run an item\'s rules for an event: each checks its conditions, then changes the story and the level.',
      'func run_rules(guid: String, on: String, detail: String = "") -> void:',
      '\tfor rule in item(guid).get("rules", []):',
      '\t\tif str(rule.get("on", "")) != on:',
      '\t\t\tcontinue',
      '\t\tif on == "custom" and detail != "" and str(rule.get("detail", "")) != detail:',
      '\t\t\tcontinue',
      '\t\t_run(guid, rule)',
      '',
      'func _run(guid: String, rule: Dictionary) -> void:',
      '\tif not VCGSRuleEngine.check(rule.get("when", {}), game):',
      '\t\treturn',
      '\tVCGSRuleEngine.apply(rule.get("effects", []), game)',
      '\tfor action in rule.get("actions", []):',
      '\t\t_act(action, guid)',
      '\trefresh()',
      '',
      'func _act(action: Dictionary, from: String) -> void:',
      '\tvar target := str(action.get("target", ""))',
      '\tmatch str(action.get("kind", "")):',
      '\t\t"open":',
      '\t\t\topen[target] = true',
      '\t\t"close":',
      '\t\t\topen[target] = false',
      '\t\t"enable":',
      '\t\t\tenabled[target] = true',
      '\t\t"disable":',
      '\t\t\tenabled[target] = false',
      '\t\t"spawn":',
      '\t\t\t_spawn(target)',
      '\t\t"despawn":',
      '\t\t\tgone[target] = true',
      '\t\t"startScene":',
      '\t\t\tgame.visit(target)',
      '\t\t\tscene_requested.emit(target)',
      '\t\t"playCinematic":',
      '\t\t\tcinematic_requested.emit(target)',
      '\t\t"playAudio":',
      '\t\t\taudio_requested.emit(nodes.get(target) as Node3D, str(param(target, "sound", "")))',
      '\t\t"objective":',
      '\t\t\tvar text := str(param(target, "objective", ""))',
      '\t\t\tobjective = text if text != "" else str(item(target).get("name", ""))',
      '\t\t\tobjective_changed.emit(objective)',
      '\t\t"goToLevel":',
      '\t\t\tlevel_requested.emit(target)',
      '\t\t"refuel":',
      '\t\t\tlight_fuel = _full_fuel()',
      '\t\t\tmessage_shown.emit("Your light is full again.")',
      '',
      '# ---------------------------------------------------------------- maps and travel (spec V2)',
      '',
      'func child_maps() -> Array:',
      '\treturn map_data().get("children", [])',
      '',
      'func _levels_dir() -> String:',
      '\tif levels_dir != "":',
      '\t\treturn levels_dir',
      '\treturn scene_file_path.get_base_dir()',
      '',
      '## Load a child map into this one at its placement (a continuous or streamed child). Null when it can\'t be.',
      'func load_map(key: String) -> VCGSLevel:',
      '\tif maps.has(key):',
      '\t\treturn maps[key]',
      '\tfor child in child_maps():',
      '\t\tif str(child.get("key", "")) != key or child.get("placement") == null:',
      '\t\t\tcontinue',
      '\t\tvar packed := load(_levels_dir() + "/" + key + ".tscn") as PackedScene',
      '\t\tif packed == null:',
      '\t\t\treturn null',
      '\t\tvar level := packed.instantiate() as VCGSLevel',
      '\t\tif level == null:',
      '\t\t\treturn null',
      '\t\tvar place: Dictionary = child.get("placement")',
      '\t\tvar at: Array = place.get("position", [0, 0, 0])',
      '\t\tlevel.transform = Transform3D(Basis(Vector3.UP, deg_to_rad(float(place.get("turn", 0)))), Vector3(float(at[0]), float(at[1]), float(at[2])))',
      '\t\tlevel.levels_dir = _levels_dir()',
      '\t\tvar holder := get_node_or_null("Maps")',
      '\t\tif holder == null:',
      '\t\t\tholder = Node3D.new()',
      '\t\t\tholder.name = "Maps"',
      '\t\t\tadd_child(holder)',
      '\t\tholder.add_child(level)',
      '\t\tif game != null:',
      '\t\t\tlevel.setup(game)',
      '\t\tmaps[key] = level',
      '\t\tmap_loaded.emit(key, level)',
      '\t\treturn level',
      '\treturn null',
      '',
      'func unload_map(key: String) -> void:',
      '\tif not maps.has(key):',
      '\t\treturn',
      '\tvar level: Node = maps[key]',
      '\tmaps.erase(key)',
      '\tlevel.queue_free()',
      '\tmap_unloaded.emit(key)',
      '',
      '## How far a point (in this map\'s space) is outside a streamed child\'s footprint; 0 inside it.',
      'func outside_of(child: Dictionary, at: Vector3) -> float:',
      '\tvar centre: Array = child.get("centre", [0, 0, 0]) if child.get("centre") != null else [0, 0, 0]',
      '\tvar size: Array = child.get("size", [0, 0]) if child.get("size") != null else [0, 0]',
      '\tvar turn := float((child.get("placement", {}) as Dictionary).get("turn", 0)) if child.get("placement") != null else 0.0',
      '\tvar v := (at - Vector3(float(centre[0]), float(centre[1]), float(centre[2]))).rotated(Vector3.UP, -deg_to_rad(turn))',
      '\tvar dx: float = max(0.0, absf(v.x) - float(size[0]) / 2.0)',
      '\tvar dz: float = max(0.0, absf(v.z) - float(size[1]) / 2.0)',
      '\treturn Vector2(dx, dz).length()',
      '',
      '## Where a node is in this map\'s space (also before either is in the scene tree).',
      'func _here(node: Node3D) -> Vector3:',
      '\tvar p := node.global_position if node.is_inside_tree() else node.position',
      '\treturn (global_transform if is_inside_tree() else transform).affine_inverse() * p',
      '',
      '## Streamed children come in as the player nears them and go when they are well away (twice the margin).',
      'func _stream() -> void:',
      '\tvar who := player',
      '\tif who == null and is_inside_tree():',
      '\t\twho = get_tree().get_first_node_in_group("player") as Node3D',
      '\tif who == null:',
      '\t\treturn',
      '\tvar at := _here(who)',
      '\tfor child in child_maps():',
      '\t\tif str(child.get("boundary", "")) != "streamed" or child.get("placement") == null or child.get("size") == null:',
      '\t\t\tcontinue',
      '\t\tvar key := str(child.get("key", ""))',
      '\t\tvar away := outside_of(child, at)',
      '\t\tvar margin := float(child.get("load_margin", 25))',
      '\t\tif away <= margin and not maps.has(key):',
      '\t\t\tload_map(key)',
      '\t\telif away > margin * 2.0 and maps.has(key):',
      '\t\t\tunload_map(key)',
      '',
      '## Whether a travel link can be taken now: unlocked, or locked and its rule holds (locked without one, never).',
      'func can_travel(key: String) -> bool:',
      '\tvar link: Dictionary = travel_data().get(key, {})',
      '\tif link.is_empty():',
      '\t\treturn false',
      '\tif not bool(link.get("locked", false)):',
      '\t\treturn true',
      '\tvar when: Dictionary = link.get("unlock_when", {})',
      '\treturn not when.is_empty() and VCGSRuleEngine.check(when, game)',
      '',
      '## Take a travel link (backwards from its end with reverse): "" when the player goes, else why not.',
      '## travel_requested says where it ends and how; one that leads to another map asks for it too.',
      'func travel(key: String, reverse: bool = false) -> String:',
      '\tvar link: Dictionary = travel_data().get(key, {})',
      '\tif link.is_empty():',
      '\t\treturn "There is no such way."',
      '\tif reverse and bool(link.get("one_way", false)):',
      '\t\treturn "%s only goes one way." % str(link.get("name", key))',
      '\tif not can_travel(key):',
      '\t\treturn "%s is closed." % str(link.get("name", key))',
      '\tvar points: Array = link.get("points", [])',
      '\tvar end: Array = points[0] if reverse else points[points.size() - 1]',
      '\tvar to_map := "" if reverse else str(link.get("to_map", ""))',
      '\ttravel_requested.emit(key, to_map, str(link.get("transition", "walk")), Vector3(float(end[0]), float(end[1]), float(end[2])))',
      '\tif to_map != "":',
      '\t\tlevel_requested.emit(to_map)',
      '\treturn ""',
      '',
      'func _spawn(guid: String) -> void:',
      '\tdone[guid] = true',
      '\tspawn_requested.emit(nodes.get(guid) as Node3D, str(param(guid, "actor", "")), int(param(guid, "count", 1)))',
      '',
      'func _on_body_entered(body: Node3D, guid: String) -> void:',
      '\tif body.is_in_group("player"):',
      '\t\tenter(guid)',
      '',
      'func _on_body_exited(body: Node3D, guid: String) -> void:',
      '\tif body.is_in_group("player"):',
      '\t\texit(guid)',
      '',
      'func _on_changed() -> void:',
      '\tif _depth > 3:',
      '\t\treturn',
      '\t_depth += 1',
      '\tfor guid in _data:',
      '\t\tif is_present(guid):',
      '\t\t\trun_rules(guid, "stateChange")',
      '\trefresh()',
      '\t_depth -= 1',
      '',
      '## The nearest item the player can use from where they stand, or "".',
      'func nearest_offer(from: Vector3, facing: Vector3 = Vector3.ZERO) -> String:',
      '\tvar best := ""',
      '\tvar best_d := INF',
      '\tfor guid in nodes:',
      '\t\tif offer(guid).is_empty():',
      '\t\t\tcontinue',
      '\t\tvar node := nodes[guid] as Node3D',
      '\t\tvar size: Array = item(guid).get("size", [1, 1, 1])',
      '\t\tvar to := node.global_position - from',
      '\t\tto.y = 0.0',
      '\t\tvar reach: float = float(param(guid, "range", 1.5)) + max(float(size[0]), float(size[2])) / 2.0 + 0.3',
      '\t\tvar d := to.length()',
      '\t\tif d > reach or d >= best_d:',
      '\t\t\tcontinue',
      '\t\tif facing != Vector3.ZERO and d > 0.6 and to.normalized().dot(facing.normalized()) < 0.3:',
      '\t\t\tcontinue',
      '\t\tbest = guid',
      '\t\tbest_d = d',
      '\treturn best',
    ].join('\n')}\n`,
  },
  {
    path: `${RUNTIME}/figure.gd`,
    kind: 'runtime',
    content: `${[
      '# VCGS Runtime for Godot 4.',
      'class_name VCGSFigure',
      'extends RefCounted',
      '## A plain stand-in person (legs, hips, torso, arms, head, nose), about `height` tall,',
      '## feet at 0 and facing -Z: the player and the characters until your own models',
      '## replace them. The same figure as the studio\'s Play Mode.',
      '',
      'static func build(color: Color, height: float = 1.75) -> Node3D:',
      '\tvar k := height / 1.75',
      '\tvar figure := Node3D.new()',
      '\tfigure.name = "Figure"',
      '\tvar cloth := StandardMaterial3D.new()',
      '\tcloth.albedo_color = color',
      '\tvar dark := StandardMaterial3D.new()',
      '\tdark.albedo_color = color.darkened(0.45)',
      '\tvar skin := StandardMaterial3D.new()',
      '\tskin.albedo_color = Color(0.85, 0.71, 0.56)',
      '\tfor leg in [-0.1, 0.1]:',
      '\t\t_part(figure, _capsule(0.075 * k, (0.68 + 0.15) * k), dark, Vector3(leg, 0.44, 0) * k)',
      '\t_part(figure, _box(Vector3(0.34, 0.16, 0.2) * k), dark, Vector3(0, 0.88, 0) * k)',
      '\t_part(figure, _box(Vector3(0.38, 0.5, 0.22) * k), cloth, Vector3(0, 1.2, 0) * k)',
      '\tfor arm in [-0.25, 0.25]:',
      '\t\t_part(figure, _capsule(0.06 * k, (0.5 + 0.12) * k), cloth, Vector3(arm, 1.12, 0) * k)',
      '\tvar neck := CylinderMesh.new()',
      '\tneck.top_radius = 0.05 * k',
      '\tneck.bottom_radius = 0.05 * k',
      '\tneck.height = 0.08 * k',
      '\t_part(figure, neck, skin, Vector3(0, 1.49, 0) * k)',
      '\tvar head := SphereMesh.new()',
      '\thead.radius = 0.12 * k',
      '\thead.height = 0.24 * k',
      '\t_part(figure, head, skin, Vector3(0, 1.62, 0) * k)',
      '\tvar nose := _box(Vector3(0.04, 0.04, 0.07) * k)',
      '\t_part(figure, nose, skin, Vector3(0, 1.61, -0.14) * k)',
      '\treturn figure',
      '',
      'static func _capsule(radius: float, height: float) -> CapsuleMesh:',
      '\tvar m := CapsuleMesh.new()',
      '\tm.radius = radius',
      '\tm.height = height',
      '\treturn m',
      '',
      'static func _box(size: Vector3) -> BoxMesh:',
      '\tvar m := BoxMesh.new()',
      '\tm.size = size',
      '\treturn m',
      '',
      'static func _part(figure: Node3D, mesh: Mesh, material: Material, at: Vector3) -> void:',
      '\tvar part := MeshInstance3D.new()',
      '\t# A headless run (a server, a check) has no renderer to build meshes with: the parts stay, empty.',
      '\tif DisplayServer.get_name() != "headless":',
      '\t\tpart.mesh = mesh',
      '\tpart.material_override = material',
      '\tpart.position = at',
      '\tfigure.add_child(part)',
    ].join('\n')}\n`,
  },
  {
    path: `${RUNTIME}/level_player.gd`,
    kind: 'runtime',
    content: `${[
      '# VCGS Runtime for Godot 4.',
      'class_name VCGSLevelPlayer',
      'extends CharacterBody3D',
      '## A plain first-person player to walk a generated level straight away:',
      '## WASD or the arrows to move, the mouse to look (click to capture it,',
      '## Esc to let go), Space to jump, Shift to run, C or Ctrl to crouch (held), E to use',
      '## what is in reach, L for the light, R to use what is in hand, I for the gear screen',
      '## (then 1-9 to equip, use, learn or craft).',
      '## Replace it with your own player; the level only needs the "player" group.',
      '',
      '@export var level_path: NodePath',
      '@export var speed := 3.6',
      '@export var run_speed := 6.4',
      '@export var jump_speed := 5.2',
      '@export var look_speed := 0.0025',
      '## Crouching: how tall, where the eyes are, and how much slower (spec §6).',
      '@export var crouch_height := 1.1',
      '@export var crouch_eye := 0.95',
      '@export var crouch_pace := 0.45',
      '',
      'var level: VCGSLevel',
      'var camera: Camera3D',
      'var prompt: Label',
      'var said: Label',
      '## The gear screen (I): equipment, skills and recipes, numbered.',
      'var gear: Label',
      'var _said_until := 0.0',
      'var _clock := 0.0',
      'var _gravity: float = ProjectSettings.get_setting("physics/3d/default_gravity", 9.8)',
      'var crouched := false',
      '## The dark over the view, and the light carried at the head.',
      'var dark: ColorRect',
      'var lamp: OmniLight3D',
      '',
      'func _ready() -> void:',
      '\t# Once only, however often it is readied.',
      '\tif camera != null:',
      '\t\treturn',
      '\tadd_to_group("player")',
      '\tif get_node_or_null("Shape") == null:',
      '\t\tvar shape := CollisionShape3D.new()',
      '\t\tshape.name = "Shape"',
      '\t\tvar capsule := CapsuleShape3D.new()',
      '\t\tcapsule.radius = 0.32',
      '\t\tcapsule.height = 1.75',
      '\t\tshape.shape = capsule',
      '\t\tshape.position.y = 0.875',
      '\t\tadd_child(shape)',
      '\tcamera = Camera3D.new()',
      '\tcamera.position.y = 1.62',
      '\tadd_child(camera)',
      '\t# The player\'s own figure: seen by other cameras and in its shadow, not from inside the head.',
      '\tvar figure := VCGSFigure.build(Color(0.79, 0.64, 0.29))',
      '\tfor part in figure.get_children():',
      '\t\t(part as VisualInstance3D).layers = 2',
      '\tadd_child(figure)',
      '\tcamera.cull_mask &= ~2',
      '\tlamp = OmniLight3D.new()',
      '\tlamp.light_color = Color(1.0, 0.85, 0.6)',
      '\tlamp.light_energy = 1.6',
      '\tlamp.visible = false',
      '\tcamera.add_child(lamp)',
      '\tvar hud := CanvasLayer.new()',
      '\tadd_child(hud)',
      '\tdark = ColorRect.new()',
      '\tdark.set_anchors_preset(Control.PRESET_FULL_RECT)',
      '\tdark.mouse_filter = Control.MOUSE_FILTER_IGNORE',
      '\tdark.color = Color(0, 0, 0, 0)',
      '\thud.add_child(dark)',
      '\tprompt = Label.new()',
      '\tprompt.set_anchors_preset(Control.PRESET_CENTER_BOTTOM)',
      '\tprompt.position = Vector2(-160, -80)',
      '\thud.add_child(prompt)',
      '\tsaid = Label.new()',
      '\tsaid.position = Vector2(24, 24)',
      '\thud.add_child(said)',
      '\tgear = Label.new()',
      '\tgear.position = Vector2(24, 64)',
      '\tgear.visible = false',
      '\thud.add_child(gear)',
      '\tlevel = get_node_or_null(level_path) as VCGSLevel',
      '\tif level != null:',
      '\t\tlevel.message_shown.connect(_say)',
      '\t\tlevel.cinematic_requested.connect(func(key: String) -> void: _say("[Cinematic] " + level.story_name(key)))',
      '\t\tlevel.scene_requested.connect(func(key: String) -> void: _say("[Scene] " + level.story_name(key)))',
      '\t\tlevel.objective_changed.connect(func(text: String) -> void: _say("Objective: " + text))',
      '\t\tlamp.omni_range = float(level.light_data().get("range", 8))',
      '',
      '## Do the gear screen\'s nth option (from 0), and show the screen again.',
      'func pick_gear(n: int) -> String:',
      '\tvar menu := level.gear_menu()',
      '\tif n < 0 or n >= menu.size():',
      '\t\treturn ""',
      '\tvar text := level.gear_do(menu[n]["act"], menu[n]["key"])',
      '\t_show_gear()',
      '\treturn text',
      '',
      'func _show_gear() -> void:',
      '\tif gear != null and gear.visible and level != null:',
      '\t\tgear.text = level.gear_text()',
      '',
      'func _say(text: String) -> void:',
      '\tsaid.text = text',
      '\t_said_until = _clock + 3.0',
      '',
      'func _unhandled_input(event: InputEvent) -> void:',
      '\tif event is InputEventMouseButton and event.pressed:',
      '\t\tInput.mouse_mode = Input.MOUSE_MODE_CAPTURED',
      '\telif event is InputEventKey and event.pressed and (event as InputEventKey).physical_keycode == KEY_ESCAPE:',
      '\t\tInput.mouse_mode = Input.MOUSE_MODE_VISIBLE',
      '\telif event is InputEventMouseMotion and Input.mouse_mode == Input.MOUSE_MODE_CAPTURED:',
      '\t\tvar motion := event as InputEventMouseMotion',
      '\t\trotate_y(-motion.relative.x * look_speed)',
      '\t\tcamera.rotation.x = clamp(camera.rotation.x - motion.relative.y * look_speed, -1.45, 1.45)',
      '\telif event is InputEventKey and event.pressed and not event.echo and (event as InputEventKey).physical_keycode == KEY_L and level != null:',
      '\t\tlevel.toggle_light()',
      '\telif event is InputEventKey and event.pressed and not event.echo and (event as InputEventKey).physical_keycode == KEY_R and level != null:',
      '\t\tlevel.use_in_hand()',
      '\t\t_show_gear()',
      '\telif event is InputEventKey and event.pressed and not event.echo and (event as InputEventKey).physical_keycode == KEY_I and level != null:',
      '\t\tgear.visible = not gear.visible',
      '\t\t_show_gear()',
      '\telif event is InputEventKey and event.pressed and not event.echo and gear.visible and level != null and (event as InputEventKey).physical_keycode >= KEY_1 and (event as InputEventKey).physical_keycode <= KEY_9:',
      '\t\tpick_gear(int((event as InputEventKey).physical_keycode - KEY_1))',
      '\telif event is InputEventKey and event.pressed and not event.echo and (event as InputEventKey).physical_keycode in [KEY_E, KEY_F] and level != null:',
      '\t\tvar target := level.nearest_offer(global_position, -global_transform.basis.z)',
      '\t\tif target != "":',
      '\t\t\tlevel.interact(target)',
      '',
      '## Crouch (lower, slower, under what a standing body can\'t pass), or stand again once',
      '## there is room overhead.',
      'func set_crouched(want: bool) -> void:',
      '\tif want == crouched:',
      '\t\treturn',
      '\tif not want and is_inside_tree() and test_move(global_transform, Vector3.UP * (1.75 - crouch_height)):',
      '\t\treturn',
      '\tcrouched = want',
      '\tvar shape := get_node_or_null("Shape") as CollisionShape3D',
      '\tif shape != null and shape.shape is CapsuleShape3D:',
      '\t\tvar height := crouch_height if crouched else 1.75',
      '\t\t(shape.shape as CapsuleShape3D).height = height',
      '\t\tshape.position.y = height / 2.0',
      '\tif camera != null:',
      '\t\tcamera.position.y = crouch_eye if crouched else 1.62',
      '\tvar body := get_node_or_null("Figure") as Node3D',
      '\tif body != null:',
      '\t\tbody.scale.y = crouch_height / 1.75 if crouched else 1.0',
      '',
      'func _physics_process(delta: float) -> void:',
      '\t_clock += delta',
      '\tif _clock > _said_until:',
      '\t\tsaid.text = ""',
      '\tvar input := Vector2(',
      '\t\tfloat(Input.is_physical_key_pressed(KEY_D) or Input.is_physical_key_pressed(KEY_RIGHT)) - float(Input.is_physical_key_pressed(KEY_A) or Input.is_physical_key_pressed(KEY_LEFT)),',
      '\t\tfloat(Input.is_physical_key_pressed(KEY_S) or Input.is_physical_key_pressed(KEY_DOWN)) - float(Input.is_physical_key_pressed(KEY_W) or Input.is_physical_key_pressed(KEY_UP)))',
      '\tvar direction := (transform.basis * Vector3(input.x, 0, input.y)).normalized()',
      '\tset_crouched(Input.is_physical_key_pressed(KEY_C) or Input.is_physical_key_pressed(KEY_CTRL))',
      '\t# Ladders and water (spec §6, as the studio\'s Play Mode): forward climbs a ladder; deep water is swum, slower, jump to rise.',
      '\tvar at := level.traversal_at(global_position) if level != null else {}',
      '\tvar depth := float(at.get("depth", 0.0))',
      '\tvar swims := depth >= 1.1',
      '\tvar climbs := bool(at.get("ladder", false)) and not swims',
      '\tvar tired := level != null and level.tracks_stamina() and level.stamina <= 0.0',
      '\tvar running := Input.is_physical_key_pressed(KEY_SHIFT) and not tired and not swims',
      '\tvar pace := (speed * crouch_pace) if crouched else (run_speed if running else speed)',
      '\tif swims:',
      '\t\tpace *= 0.55',
      '\tif climbs:',
      '\t\tvar across := (transform.basis * Vector3(input.x, 0, 0)).normalized()',
      '\t\tvelocity.x = across.x * speed * 0.5',
      '\t\tvelocity.z = across.z * speed * 0.5',
      '\t\tvelocity.y = -input.y * 2.2',
      '\telse:',
      '\t\tvelocity.x = direction.x * pace',
      '\t\tvelocity.z = direction.z * pace',
      '\t\tif swims:',
      '\t\t\tvelocity.y = 2.4 if Input.is_physical_key_pressed(KEY_SPACE) else maxf(velocity.y - _gravity * 0.15 * delta, -1.2)',
      '\t\t\tif Input.is_physical_key_pressed(KEY_SPACE) and depth < 1.15:',
      '\t\t\t\tvelocity.y = minf(velocity.y, 0.0)',
      '\t\telif is_on_floor():',
      '\t\t\tif Input.is_physical_key_pressed(KEY_SPACE) and not crouched:',
      '\t\t\t\tvelocity.y = jump_speed',
      '\t\telse:',
      '\t\t\tvelocity.y -= _gravity * delta',
      '\tmove_and_slide()',
      '\tif level != null:',
      '\t\tvar moving := input.length() > 0.1',
      '\t\tlevel.spend_stamina(delta, running and moving, swims, climbs and absf(input.y) > 0.1)',
      '\tif level != null:',
      '\t\t# The dark: over the view in a darkness zone, pushed back by the light.',
      '\t\tvar lit := level.is_lit()',
      '\t\tlamp.visible = lit',
      '\t\tdark.color.a = level.darkness() * (0.35 if lit else 1.0)',
      '\t\tvar target := level.nearest_offer(global_position, -global_transform.basis.z)',
      '\t\tvar o := level.offer(target) if target != "" else {}',
      '\t\tprompt.text = "" if o.is_empty() else ("[E] " + str(o.get("blocked", str(o["verb"]) + " · " + str(o["label"]))))',
    ].join('\n')}\n`,
  },
];

// ---------------------------------------------------------------- scenes

class Tscn {
  private subs: string[] = [];
  private exts: string[] = [];
  private nodes: string[] = [];
  private cache = new Map<string, string>();
  private n = 0;

  ext(type: string, path: string): string {
    const k = `ext:${path}`;
    if (!this.cache.has(k)) {
      const id = `${this.exts.length + 1}_${type.toLowerCase()}`;
      this.exts.push(`[ext_resource type="${type}" path="${path}" id="${id}"]`);
      this.cache.set(k, id);
    }
    return `ExtResource("${this.cache.get(k)}")`;
  }

  sub(type: string, props: Record<string, string>): string {
    const body = Object.entries(props).map(([k, v]) => `${k} = ${v}`).join('\n');
    const k = `${type}:${body}`;
    if (!this.cache.has(k)) {
      const id = `${type}_${++this.n}`;
      this.subs.push(`[sub_resource type="${type}" id="${id}"]\n${body}`);
      this.cache.set(k, id);
    }
    return `SubResource("${this.cache.get(k)}")`;
  }

  node(name: string, type: string | null, parent: string | null, props: Record<string, string> = {}, extra = '') {
    const head = [`name=${str(name)}`, ...(type ? [`type="${type}"`] : []), ...(parent !== null ? [`parent=${str(parent)}`] : []), ...(extra ? [extra] : [])].join(' ');
    this.nodes.push([`[node ${head}]`, ...Object.entries(props).map(([k, v]) => `${k} = ${v}`)].join('\n'));
  }

  toString(): string {
    return [`[gd_scene load_steps=${this.exts.length + this.subs.length + 1} format=3]`, ...this.exts, ...this.subs, ...this.nodes].join('\n\n') + '\n';
  }
}

const slabMaterial = (t: Tscn, p: IrPiece): string => t.sub('StandardMaterial3D', { albedo_color: color(p.color, p.opacity), ...(p.opacity < 1 ? { transparency: '1' } : {}) });

/** A piece's mesh (sized, not scaled) and its turn about the item's up axis. */
const pieceMesh = (t: Tscn, p: IrPiece): { mesh: string; basis: M3 } => {
  const [sx, sy, sz] = p.size;
  const material = t.sub('StandardMaterial3D', {
    albedo_color: color(p.light ? p.light.color : p.color, p.opacity),
    ...(p.opacity < 1 ? { transparency: '1' } : {}),
    ...(p.light ? { emission_enabled: 'true', emission: color(p.light.color) } : {}),
  });
  const turn = rotY(p.turn);
  switch (p.shape) {
    case 'cylinder':
      return { mesh: t.sub('CylinderMesh', { top_radius: f(sx / 2), bottom_radius: f(sx / 2), height: f(sy), material }), basis: turn };
    case 'sphere':
      return { mesh: t.sub('SphereMesh', { radius: f(sx / 2), height: f(sy), material }), basis: turn };
    case 'cone':
      // Tip toward north (−z): a cylinder with no top, laid along z.
      return { mesh: t.sub('CylinderMesh', { top_radius: '0.0', bottom_radius: f(sx / 2), height: f(sz), material }), basis: mul(turn, rotX(-90)) };
    case 'wedge':
      // A right-angled prism, high side to the north: its triangle turned into the y–z plane.
      return { mesh: t.sub('PrismMesh', { left_to_right: '1.0', size: `Vector3(${f(sz)}, ${f(sy)}, ${f(sx)})`, material }), basis: mul(turn, rotY(90)) };
    default:
      return { mesh: t.sub('BoxMesh', { size: `Vector3(${f(sx)}, ${f(Math.max(0.01, sy))}, ${f(sz)})`, material }), basis: turn };
  }
};

const NODE_TYPE = (item: IrLevelItem): string => {
  if (item.kind === 'volume') return 'Area3D';
  if (item.kind === 'marker') return item.role === 'camera' ? 'Camera3D' : 'Marker3D';
  return 'Node3D';
};

export const levelTscn = (level: IrLevel, root: string): string => {
  const t = new Tscn();
  const script = t.ext('Script', `res://${root}/levels/${level.key}.gd`);
  t.node(nodeName(level.export_name), 'Node3D', null, {
    script,
    'metadata/vcgs_guid_level': str(level.guid),
    'metadata/vcgs_map_kind': str(level.map.kind),
    'metadata/vcgs_boundary': str(level.map.boundary),
    ...(level.map.parent ? { 'metadata/vcgs_parent': str(level.map.parent) } : {}),
    'metadata/vcgs_revision': str(level.revision),
  });
  const names = new Set<string>();
  for (const item of level.items) {
    let name = nodeName(item.export_name);
    for (let n = 2; names.has(name); n++) name = `${nodeName(item.export_name)}_${n}`;
    names.add(name);
    const type = NODE_TYPE(item);
    const groups = [item.role === 'playerStart' ? 'vcgs_player_start' : '', 'vcgs_item'].filter(Boolean);
    t.node(
      name,
      type,
      '.',
      {
        transform: transform(rotY(item.turn), item.position),
        ...(item.role === 'camera' ? { fov: f(Number(item.params.fov ?? 60)) } : {}),
        'metadata/vcgs_guid': str(item.guid),
        'metadata/vcgs_role': str(item.role),
        'metadata/vcgs_asset': str(item.asset),
        'metadata/vcgs_revision': str(item.revision),
        ...(item.links.length ? { 'metadata/vcgs_links': `PackedStringArray(${item.links.map(str).join(', ')})` } : {}),
        ...(item.replacement_locked ? { 'metadata/vcgs_replacement_locked': 'true' } : {}),
        ...(item.opens ? { 'metadata/vcgs_opens': str(item.opens) } : {}),
      },
      `groups=[${groups.map(str).join(', ')}]`,
    );
    const at = name;
    // What it looks like: the final art when there is some, else the graybox proxy (none when the art is locked).
    const visuals = item.pieces.filter((p) => p.part !== 'volume');
    if (item.final_asset) {
      t.node('Art', null, at, {}, `instance=${t.ext('PackedScene', item.final_asset.startsWith('res://') ? item.final_asset : `res://${item.final_asset}`)}`);
    } else if (!item.replacement_locked && visuals.length && item.kind !== 'volume') {
      t.node('Proxy', 'Node3D', at);
      visuals.forEach((p, n) => {
        if (p.shape === 'slab' && p.outline) {
          // A freeform floor or ceiling: its outline (drawn in x–y) turned flat and raised by its thickness from its underside.
          t.node(`${p.part}_${n}`, 'CSGPolygon3D', `${at}/Proxy`, {
            transform: transform(mul(rotY(p.turn), rotX(90)), [p.at[0], p.at[1] - p.size[1] / 2, p.at[2]]),
            polygon: `PackedVector2Array(${p.outline.flat().map(f).join(', ')})`,
            depth: f(p.size[1]),
            material: slabMaterial(t, p),
          });
          return;
        }
        const { mesh, basis } = pieceMesh(t, p);
        t.node(`${p.part}_${n}`, 'MeshInstance3D', `${at}/Proxy`, { transform: transform(basis, p.at), mesh });
      });
    }
    // What is in the way.
    const solid = item.pieces.filter((p) => p.collide && p.part !== 'volume');
    if (solid.length) {
      t.node('Collision', 'StaticBody3D', at);
      solid.forEach((p, n) => {
        const size = p.size;
        t.node(`${p.part}_${n}`, 'CollisionShape3D', `${at}/Collision`, {
          transform: transform(rotY(p.turn), p.at),
          // A slab collides by its own faces (both sides, so nothing falls through from below).
          shape:
            p.shape === 'slab' && p.outline
              ? t.sub('ConcavePolygonShape3D', { data: `PackedVector3Array(${slabFaces(p).flat(2).map(f).join(', ')})`, backface_collision: 'true' })
              : t.sub('BoxShape3D', { size: `Vector3(${f(size[0])}, ${f(Math.max(0.01, size[1]))}, ${f(size[2])})` }),
        });
      });
    }
    // A volume notices the player in its box.
    const zone = item.kind === 'volume' ? item.pieces.find((p) => p.part === 'volume' && p.shape === 'slab' && p.outline) : undefined;
    if (zone) {
      // A freeform volume: one convex prism per triangle, so the area notices the player anywhere inside its outline.
      slabPrisms(zone).forEach((points, n) => {
        t.node(n ? `Shape_${n + 1}` : 'Shape', 'CollisionShape3D', at, { transform: transform(rotY(zone.turn), zone.at), shape: t.sub('ConvexPolygonShape3D', { points: `PackedVector3Array(${points.flat().map(f).join(', ')})` }) });
      });
      if (zone.collide) {
        t.node('Collision', 'StaticBody3D', at);
        t.node('Shape', 'CollisionShape3D', `${at}/Collision`, {
          transform: transform(rotY(zone.turn), zone.at),
          shape: t.sub('ConcavePolygonShape3D', { data: `PackedVector3Array(${slabFaces(zone).flat(2).map(f).join(', ')})`, backface_collision: 'true' }),
        });
      }
    } else if (item.kind === 'volume') {
      const [w, h, d] = item.size;
      const blocks = item.pieces.some((p) => p.part === 'volume' && p.collide);
      t.node('Shape', 'CollisionShape3D', at, { transform: transform(rotY(0), [0, h / 2, 0]), shape: t.sub('BoxShape3D', { size: `Vector3(${f(w)}, ${f(h)}, ${f(d)})` }) });
      if (blocks) {
        t.node('Collision', 'StaticBody3D', at);
        t.node('Shape', 'CollisionShape3D', `${at}/Collision`, { transform: transform(rotY(0), [0, h / 2, 0]), shape: t.sub('BoxShape3D', { size: `Vector3(${f(w)}, ${f(h)}, ${f(d)})` }) });
      }
    }
    // Lights.
    for (const p of item.pieces) {
      if (!p.light) continue;
      const common = { light_color: color(p.light.color), light_energy: f(p.light.intensity), shadow_enabled: String(item.params.shadows !== false) };
      if (p.light.kind === 'spot') {
        t.node('Light', 'SpotLight3D', at, { transform: transform(rotY(0), p.at), ...common, spot_range: f(p.light.range), spot_angle: f((p.light.angle ?? 40) / 2) });
      } else {
        t.node('Light', 'OmniLight3D', at, { transform: transform(rotY(0), p.at), ...common, omni_range: f(p.light.range * (p.light.kind === 'area' ? 1.5 : 1)) });
      }
    }
  }
  // Travel links (spec V2 §13): a path along each, to see it in the editor and move along it.
  if (level.travel.length) {
    t.node('Travel', 'Node3D', '.');
    for (const link of level.travel) {
      const pts = link.points.flatMap((p) => [0, 0, 0, 0, 0, 0, ...p]);
      t.node(nodeName(link.key), 'Path3D', 'Travel', {
        curve: t.sub('Curve3D', { _data: `{"points": PackedVector3Array(${pts.map(f).join(', ')}), "tilts": PackedFloat32Array(${link.points.map(() => '0').join(', ')})}`, point_count: String(link.points.length) }),
        'metadata/vcgs_travel': str(link.key),
        'metadata/vcgs_kind': str(link.kind),
        ...(link.to_map ? { 'metadata/vcgs_to_map': str(link.to_map) } : {}),
      });
    }
  }
  return t.toString();
};

/** The level's data, for VCGSLevel. */
export const levelScript = (level: IrLevel, names: Record<string, string>, gd: (v: unknown) => string, header: string, notes: IrNote[] = []): string =>
  [
    header,
    `class_name Level${level.key.split('_').map((w) => (w ? w[0]!.toUpperCase() + w.slice(1) : '')).join('')}`,
    'extends VCGSLevel',
    `## ${level.name} · ${level.export_name} · ${level.items.length} items`,
    // Open comments and tasks on the level and its items (spec §16).
    ...todoLines(notes.filter((n) => n.on.kind === 'level' && n.on.key === level.guid), '#'),
    ...level.items.flatMap((i) => todoLines(notes.filter((n) => n.on.kind === 'levelItem' && n.on.key === i.guid), `# ${i.export_name}:`)),
    '',
    `const KEY := ${gd(level.key)}`,
    `const GUID := ${gd(level.guid)}`,
    `const FLOORS := ${gd(level.floors)}`,
    '',
    '## Every item by GUID: what it is, its settings, its story links, when it is there and its rules.',
    `const ITEMS := ${gd(
      Object.fromEntries(
        level.items.map((i) => [
          i.guid,
          {
            export_name: i.export_name,
            name: i.name,
            role: i.role,
            kind: i.kind,
            size: i.size,
            params: Object.fromEntries(Object.entries(i.params).filter(([k]) => !['material', 'finalAsset', 'template', 'export', 'replacementLocked', 'visible'].includes(k))),
            links: i.links,
            ...(i.scenes.length ? { scenes: i.scenes } : {}),
            ...(i.active_when ? { active_when: i.active_when } : {}),
            ...(i.rules.length ? { rules: i.rules } : {}),
            ...(i.motion ? { motion: i.motion } : {}),
            ...(i.in_dark ? { in_dark: i.in_dark } : {}),
            ...(i.puzzles ? { puzzles: i.puzzles } : {}),
            ...(i.opens ? { opens: i.opens } : {}),
          },
        ]),
      ),
    )}`,
    '',
    `const NAMES := ${gd(names)}`,
    '',
    '## The player\'s light: what lights it, its fuel in seconds (0 for ever), how far it reaches.',
    `const LIGHT := ${gd(level.light ?? {})}`,
    '',
    `## Where it is in the hierarchy (${level.map.kind}${level.map.parent ? `, part of ${level.map.parent}` : ''}, ${level.map.boundary}) and the maps inside it.`,
    `const MAP := ${gd(level.map)}`,
    '',
    '## Its travel links by key.',
    `const TRAVEL := ${gd(Object.fromEntries(level.travel.map((t) => [t.key, t])))}`,
    '',
    'func map_data() -> Dictionary:',
    '\treturn MAP',
    '',
    'func travel_data() -> Dictionary:',
    '\treturn TRAVEL',
    '',
    'func light_data() -> Dictionary:',
    '\treturn LIGHT',
    '',
    'func level_data() -> Dictionary:',
    '\treturn ITEMS',
    '',
    'func story_names() -> Dictionary:',
    '\treturn NAMES',
  ].join('\n');

/** A scene to walk the level at once: the level, a first-person player at its start, light. */
export const playTscn = (level: IrLevel, root: string): string => {
  const t = new Tscn();
  const scene = t.ext('PackedScene', `res://${root}/levels/${level.key}.tscn`);
  const player = t.ext('Script', `res://${RUNTIME}/level_player.gd`);
  const env = t.sub('Environment', { background_mode: '1', background_color: 'Color(0.03, 0.03, 0.04, 1)', ambient_light_source: '2', ambient_light_color: 'Color(0.95, 0.9, 0.8, 1)', ambient_light_energy: '0.6' });
  t.node(`Play${level.key.split('_').map((w) => (w ? w[0]!.toUpperCase() + w.slice(1) : '')).join('')}`, 'Node3D', null);
  t.node('Level', null, '.', {}, `instance=${scene}`);
  const start = level.start ?? { position: [0, 0, 0] as [number, number, number], turn: 0 };
  t.node('Player', 'CharacterBody3D', '.', { transform: transform(rotY(start.turn), [start.position[0], start.position[1] + 0.05, start.position[2]]), script: player, level_path: 'NodePath("../Level")' });
  t.node('Sun', 'DirectionalLight3D', '.', { transform: transform(mul(rotY(35), rotX(-55)), [0, 20, 0]), shadow_enabled: 'true' });
  t.node('World', 'WorldEnvironment', '.', { environment: env });
  return t.toString();
};
