/**
 * The puzzle runtime for Godot (puzzle spec §6, §8, §10): a puzzle's steps
 * kept as the Puzzle Creator plays them — done stays done, sequences in
 * order, steps waiting on what they need first, timed sub-goals on the play
 * clock, wrong moves noticed when they happen (fail-forward, or a reset),
 * effects the first time a step is done — staged hints, and the screen
 * puzzles' answers checked for every kind. The same rules as the studio's
 * progress.ts and screens.ts, and as the Unity and Unreal runtimes.
 */
export const puzzleRuntimeGd = (): string[] => [
  '# VCGS Runtime for Godot 4.',
  'class_name VCGSPuzzleRuntime',
  'extends RefCounted',
  '## Puzzle steps, hints and screen puzzles as VC Game Studio plays them.',
  '## A puzzle\'s progress: done (step -> order done), failed, begun (timed',
  '## sub-goal -> clock when its first step was done), seq, fails (wrong moves),',
  '## wrong (whether each step\'s wrong move holds now), stale (steps undone',
  '## while their condition held: done again only once it stops and holds anew).',
  '',
  'static func empty_progress() -> Dictionary:',
  '\treturn { "done": {}, "failed": {}, "begun": {}, "seq": 0, "fails": 0, "wrong": {}, "stale": {} }',
  '',
  'static func _children(steps: Array, parent: Variant) -> Array:',
  '\tvar out: Array = []',
  '\tfor s in steps:',
  '\t\tif s.get("parent") == parent:',
  '\t\t\tout.append(s)',
  '\treturn out',
  '',
  'static func _find(steps: Array, id: Variant) -> Dictionary:',
  '\tfor s in steps:',
  '\t\tif s.get("id") == id:',
  '\t\t\treturn s',
  '\treturn {}',
  '',
  'static func _descendants(steps: Array, id: String) -> Array:',
  '\tvar out: Array = []',
  '\tfor c in _children(steps, id):',
  '\t\tout.append(c)',
  '\t\tout.append_array(_descendants(steps, str(c["id"])))',
  '\treturn out',
  '',
  'static func _required(steps: Array, parent: Variant) -> Array:',
  '\tvar out: Array = []',
  '\tfor c in _children(steps, parent):',
  '\t\tif not c.get("optional", false):',
  '\t\t\tout.append(c)',
  '\treturn out',
  '',
  '## Whether a step may be done yet: what it needs first is done, the step before',
  '## it in a sequence is, and the sub-goal it is under is open too.',
  'static func unlocked(steps: Array, step: Dictionary, done: Dictionary) -> bool:',
  '\tfor r in step.get("requires", []):',
  '\t\tif not _find(steps, r).is_empty() and not done.has(r):',
  '\t\t\treturn false',
  '\tvar parent_id: Variant = step.get("parent")',
  '\tif parent_id == null:',
  '\t\treturn true',
  '\tvar parent := _find(steps, parent_id)',
  '\tif parent.is_empty():',
  '\t\treturn true',
  '\tif parent.get("gate", "all") == "sequence" and not step.get("optional", false):',
  '\t\tvar order := _required(steps, parent_id)',
  '\t\tfor i in order.size():',
  '\t\t\tif order[i]["id"] == step["id"] and i > 0 and not done.has(order[i - 1]["id"]):',
  '\t\t\t\treturn false',
  '\treturn unlocked(steps, parent, done)',
  '',
  'static func _mark_done(p: Dictionary, n: Dictionary, steps: Array, now: float, events: Array, effects: Array) -> void:',
  '\tp["seq"] = int(p["seq"]) + 1',
  '\tp["done"][n["id"]] = p["seq"]',
  '\tevents.append({ "step": n["id"], "label": n["label"], "what": "done" })',
  '\teffects.append_array(n.get("effects", []))',
  '\t# Its first step done starts a timed sub-goal\'s clock.',
  '\tvar at: Variant = n.get("parent")',
  '\twhile at != null:',
  '\t\tvar a := _find(steps, at)',
  '\t\tif a.is_empty():',
  '\t\t\tbreak',
  '\t\tif float(a.get("within", 0)) > 0.0 and not p["begun"].has(a["id"]):',
  '\t\t\tp["begun"][a["id"]] = now',
  '\t\tat = a.get("parent")',
  '',
  '## Move a puzzle on: returns { progress, events, effects, solved, changed }.',
  '## events: { step, label, what } with what done, failed, expired or reset.',
  'static func advance(design: Dictionary, before: Dictionary, game: VCGSGameState, now: float) -> Dictionary:',
  '\tvar steps: Array = design.get("steps", [])',
  '\tvar p: Dictionary = empty_progress()',
  '\tif not before.is_empty():',
  '\t\tp = before.duplicate(true)',
  '\t\tfor k in ["done", "failed", "begun", "wrong", "stale"]:',
  '\t\t\tif typeof(p.get(k)) != TYPE_DICTIONARY:',
  '\t\t\t\tp[k] = {}',
  '\tvar events: Array = []',
  '\tvar effects: Array = []',
  '\tvar changed := false',
  '\t# Time first: a timed sub-goal that ran out loses what was done under it.',
  '\tfor g in steps:',
  '\t\tvar gid := str(g["id"])',
  '\t\tif g["kind"] != "goal" or float(g.get("within", 0)) <= 0.0 or not p["begun"].has(gid) or p["done"].has(gid):',
  '\t\t\tcontinue',
  '\t\tif now - float(p["begun"][gid]) <= float(g["within"]):',
  '\t\t\tcontinue',
  '\t\tfor d in _descendants(steps, gid):',
  '\t\t\tif p["done"].has(d["id"]) and d["kind"] != "goal":',
  '\t\t\t\tp["stale"][d["id"]] = true',
  '\t\t\tp["done"].erase(d["id"])',
  '\t\t\tp["failed"].erase(d["id"])',
  '\t\tp["begun"].erase(gid)',
  '\t\tevents.append({ "step": gid, "label": g["label"], "what": "expired" })',
  '\t\tchanged = true',
  '\t# Then as many passes as there are steps: each can open the next.',
  '\tfor _pass in steps.size() + 1:',
  '\t\tvar moved := false',
  '\t\tfor n in steps:',
  '\t\t\tvar nid := str(n["id"])',
  '\t\t\tif p["done"].has(nid):',
  '\t\t\t\tcontinue',
  '\t\t\tif n["kind"] != "goal":',
  '\t\t\t\t# A wrong move is noticed when it happens, open or not.',
  '\t\t\t\tvar fail: Dictionary = n.get("fail", {})',
  '\t\t\t\tvar wrong_now: bool = fail.has("when") and VCGSRuleEngine.check(fail["when"], game)',
  '\t\t\t\tvar was: bool = p["wrong"].get(nid, false)',
  '\t\t\t\tif was != wrong_now:',
  '\t\t\t\t\tp["wrong"][nid] = wrong_now',
  '\t\t\t\t\tchanged = true',
  '\t\t\t\tif wrong_now and not was and not p["failed"].has(nid):',
  '\t\t\t\t\tp["seq"] = int(p["seq"]) + 1',
  '\t\t\t\t\tp["failed"][nid] = p["seq"]',
  '\t\t\t\t\tevents.append({ "step": nid, "label": n["label"], "what": "failed" })',
  '\t\t\t\t\teffects.append_array(fail.get("effects", []))',
  '\t\t\t\t\tchanged = true',
  '\t\t\t\t\tmoved = true',
  '\t\t\t\t\tif fail.get("forward", false):',
  '\t\t\t\t\t\t_mark_done(p, n, steps, now, events, effects)',
  '\t\t\t\t\t\tcontinue',
  '\t\t\t\t\tp["fails"] = int(p["fails"]) + 1',
  '\t\t\t\t\tif design.get("reset", "never") == "onFail":',
  '\t\t\t\t\t\tvar stale := {}',
  '\t\t\t\t\t\tfor x in steps:',
  '\t\t\t\t\t\t\tif x["kind"] != "goal" and (p["done"].has(x["id"]) or x["id"] == nid):',
  '\t\t\t\t\t\t\t\tstale[x["id"]] = true',
  '\t\t\t\t\t\tp = { "done": {}, "failed": {}, "begun": {}, "seq": p["seq"], "fails": p["fails"], "wrong": p["wrong"], "stale": stale }',
  '\t\t\t\t\t\tevents.append({ "step": nid, "label": n["label"], "what": "reset" })',
  '\t\t\t\t\t\tbreak',
  '\t\t\t\t\tcontinue',
  '\t\t\t\tif p["stale"].has(nid):',
  '\t\t\t\t\t# Undone while it held: it must stop holding first.',
  '\t\t\t\t\tif n.has("when") and VCGSRuleEngine.check(n["when"], game):',
  '\t\t\t\t\t\tcontinue',
  '\t\t\t\t\tp["stale"].erase(nid)',
  '\t\t\t\t\tchanged = true',
  '\t\t\t\t\tcontinue',
  '\t\t\t\tif unlocked(steps, n, p["done"]) and n.has("when") and VCGSRuleEngine.check(n["when"], game):',
  '\t\t\t\t\t_mark_done(p, n, steps, now, events, effects)',
  '\t\t\t\t\tchanged = true',
  '\t\t\t\t\tmoved = true',
  '\t\t\t\tcontinue',
  '\t\t\tif not unlocked(steps, n, p["done"]):',
  '\t\t\t\tcontinue',
  '\t\t\tvar kids := _required(steps, nid)',
  '\t\t\tif kids.is_empty():',
  '\t\t\t\tcontinue',
  '\t\t\tvar any_done := false',
  '\t\t\tvar all_done := true',
  '\t\t\tfor c in kids:',
  '\t\t\t\tif p["done"].has(c["id"]):',
  '\t\t\t\t\tany_done = true',
  '\t\t\t\telse:',
  '\t\t\t\t\tall_done = false',
  '\t\t\tif any_done if n.get("gate", "all") == "any" else all_done:',
  '\t\t\t\t_mark_done(p, n, steps, now, events, effects)',
  '\t\t\t\tchanged = true',
  '\t\t\t\tmoved = true',
  '\t\tif not moved:',
  '\t\t\tbreak',
  '\tvar top := _required(steps, null)',
  '\tvar solved := not top.is_empty()',
  '\tfor t in top:',
  '\t\tif not p["done"].has(t["id"]):',
  '\t\t\tsolved = false',
  '\treturn { "progress": p, "events": events, "effects": effects, "solved": solved, "changed": changed }',
  '',
  '## Whether a timed sub-goal is running (so the clock matters).',
  'static func running(progress: Dictionary) -> bool:',
  '\treturn typeof(progress.get("begun")) == TYPE_DICTIONARY and not progress["begun"].is_empty()',
  '',
  '## Staged hints due now and not given: each needs its wrong moves made and its',
  '## condition holding (and at least one of them). fails counts the puzzle\'s',
  '## wrong moves and the wrong answers at its elements\' screens.',
  'static func due_hints(design: Dictionary, fails: int, given: Dictionary, game: VCGSGameState) -> Array:',
  '\tvar out: Array = []',
  '\tfor h in design.get("hints", []):',
  '\t\tif given.has(h["id"]) or (not h.has("afterFails") and not h.has("when")):',
  '\t\t\tcontinue',
  '\t\tif h.has("afterFails") and fails < int(h["afterFails"]):',
  '\t\t\tcontinue',
  '\t\tif h.has("when") and not VCGSRuleEngine.check(h["when"], game):',
  '\t\t\tcontinue',
  '\t\tout.append(h)',
  '\treturn out',
  '',
  '# ------------------------------------------------------------ screen puzzles',
  '',
  'const PIECE_SIDES := { "empty": 0, "end": 1, "straight": 5, "corner": 3, "tee": 7, "cross": 15 }',
  '',
  'static func _turned(sides: int, rot: int) -> int:',
  '\tvar s := sides',
  '\tfor _i in ((rot % 4) + 4) % 4:',
  '\t\ts = ((s << 1) | (s >> 3)) & 15',
  '\treturn s',
  '',
  '## Whether a circuit\'s source reaches its sink with its pieces turned so (one turn a cell).',
  'static func circuit_joined(screen: Dictionary, rot: Array) -> bool:',
  '\tvar w := int(screen.get("width", 0))',
  '\tvar h := int(screen.get("height", 0))',
  '\tvar cells: Array = screen.get("cells", [])',
  '\tvar src := int(screen.get("source", 0))',
  '\tvar sink := int(screen.get("sink", cells.size() - 1))',
  '\tvar sides := func(i: int) -> int: return _turned(int(PIECE_SIDES.get(cells[i].get("piece", "empty"), 0)), int(rot[i]) if i < rot.size() else 0)',
  '\tvar seen := { src: true }',
  '\tvar queue: Array = [src]',
  '\twhile not queue.is_empty():',
  '\t\tvar at: int = queue.pop_front()',
  '\t\tif at == sink:',
  '\t\t\treturn true',
  '\t\tvar r := int(float(at) / float(w))',
  '\t\tvar c := at % w',
  '\t\tfor step in [[1, 4, at - w if r > 0 else -1], [2, 8, at + 1 if c < w - 1 else -1], [4, 1, at + w if r < h - 1 else -1], [8, 2, at - 1 if c > 0 else -1]]:',
  '\t\t\tvar to: int = step[2]',
  '\t\t\tif to >= 0 and not seen.has(to) and (sides.call(at) & step[0]) != 0 and (sides.call(to) & step[1]) != 0:',
  '\t\t\t\tseen[to] = true',
  '\t\t\t\tqueue.append(to)',
  '\treturn false',
  '',
  '## Flip a switch, and the switches it is linked to.',
  'static func flip(screen: Dictionary, on: Array, i: int) -> Array:',
  '\tvar next := on.duplicate()',
  '\tvar links: Array = screen.get("links", [])',
  '\tvar which: Array = [i]',
  '\tif i < links.size():',
  '\t\twhich.append_array(links[i])',
  '\tfor j in which:',
  '\t\tif int(j) >= 0 and int(j) < next.size():',
  '\t\t\tnext[int(j)] = not next[int(j)]',
  '\treturn next',
  '',
  'static func _ints(a: Variant) -> Array:',
  '\tvar out: Array = []',
  '\tif typeof(a) == TYPE_ARRAY:',
  '\t\tfor x in a:',
  '\t\t\tout.append(int(x))',
  '\treturn out',
  '',
  'static func _strs(a: Variant) -> Array:',
  '\tvar out: Array = []',
  '\tif typeof(a) == TYPE_ARRAY:',
  '\t\tfor x in a:',
  '\t\t\tout.append(str(x))',
  '\treturn out',
  '',
  '## Whether an answer solves a screen. What the answer is, by kind: keypad and',
  '## custom, the text entered; dial, the numbers set in order; symbols, the symbols',
  '## pressed; ordering, the items in the order given; matching, the right-hand',
  '## items in the order of the left; assembly, slot id -> part id; levers, each',
  '## switch on or off; rings, each ring\'s turn; tiles, the number on each square',
  '## (0 the gap); circuit, each cell\'s turn.',
  'static func check_screen(screen: Dictionary, answer: Variant) -> bool:',
  '\tmatch str(screen.get("kind", "")):',
  '\t\t"keypad":',
  '\t\t\treturn str(screen.get("code", "")) != "" and str(answer) == str(screen.get("code", ""))',
  '\t\t"custom":',
  '\t\t\treturn str(screen.get("text", "")).strip_edges() != "" and str(answer).strip_edges().to_lower() == str(screen.get("text", "")).strip_edges().to_lower()',
  '\t\t"dial":',
  '\t\t\treturn not _ints(screen.get("combination", [])).is_empty() and _ints(answer) == _ints(screen.get("combination", []))',
  '\t\t"symbols":',
  '\t\t\treturn not _strs(screen.get("answer", [])).is_empty() and _strs(answer) == _strs(screen.get("answer", []))',
  '\t\t"ordering":',
  '\t\t\treturn _strs(screen.get("items", [])).size() > 1 and _strs(answer) == _strs(screen.get("items", []))',
  '\t\t"matching":',
  '\t\t\tvar rights: Array = []',
  '\t\t\tfor pair in screen.get("pairs", []):',
  '\t\t\t\trights.append(str(pair.get("right", "")))',
  '\t\t\treturn not rights.is_empty() and _strs(answer) == rights',
  '\t\t"assembly":',
  '\t\t\tvar slots: Array = screen.get("slots", [])',
  '\t\t\tif slots.is_empty() or typeof(answer) != TYPE_DICTIONARY:',
  '\t\t\t\treturn false',
  '\t\t\tfor slot in slots:',
  '\t\t\t\tif str(answer.get(slot["id"], "")) != str(slot.get("accepts", "")):',
  '\t\t\t\t\treturn false',
  '\t\t\treturn true',
  '\t\t"levers":',
  '\t\t\tvar target: Array = screen.get("target", [])',
  '\t\t\tif target.is_empty() or typeof(answer) != TYPE_ARRAY or answer.size() != target.size():',
  '\t\t\t\treturn false',
  '\t\t\tfor i in target.size():',
  '\t\t\t\tif bool(answer[i]) != bool(target[i]):',
  '\t\t\t\t\treturn false',
  '\t\t\treturn true',
  '\t\t"rings":',
  '\t\t\tvar turns := _ints(answer)',
  '\t\t\tif turns.is_empty() or turns.size() != int(screen.get("rings", 0)):',
  '\t\t\t\treturn false',
  '\t\t\tfor t in turns:',
  '\t\t\t\tif t % maxi(1, int(screen.get("segments", 8))) != 0:',
  '\t\t\t\t\treturn false',
  '\t\t\treturn true',
  '\t\t"tiles":',
  '\t\t\tvar n := maxi(2, int(screen.get("size", 3)))',
  '\t\t\tvar solved: Array = []',
  '\t\t\tfor i in n * n - 1:',
  '\t\t\t\tsolved.append(i + 1)',
  '\t\t\tsolved.append(0)',
  '\t\t\treturn _ints(answer) == solved',
  '\t\t"circuit":',
  '\t\t\treturn typeof(answer) == TYPE_ARRAY and circuit_joined(screen, answer)',
  '\treturn false',
  '',
  '## How a live screen starts, for your UI: tiles shuffled by legal moves, rings',
  '## where they start, circuit pieces turned out of true (the source and sink stay),',
  '## switches as they start, and ordering reversed. Never already solved.',
  'static func start_state(screen: Dictionary, seed: int = 7) -> Array:',
  '\tvar rng := RandomNumberGenerator.new()',
  '\trng.seed = seed',
  '\tmatch str(screen.get("kind", "")):',
  '\t\t"tiles":',
  '\t\t\tvar n := maxi(2, int(screen.get("size", 3)))',
  '\t\t\tvar tiles: Array = []',
  '\t\t\tfor i in n * n - 1:',
  '\t\t\t\ttiles.append(i + 1)',
  '\t\t\ttiles.append(0)',
  '\t\t\tvar gap := tiles.size() - 1',
  '\t\t\tvar last := -1',
  '\t\t\tfor _m in maxi(1, int(screen.get("shuffle", 40))):',
  '\t\t\t\tvar options: Array = []',
  '\t\t\t\tfor cand in [gap - n if gap >= n else -1, gap + 1 if gap % n < n - 1 else -1, gap + n if gap < n * (n - 1) else -1, gap - 1 if gap % n > 0 else -1]:',
  '\t\t\t\t\tif cand >= 0 and cand != last:',
  '\t\t\t\t\t\toptions.append(cand)',
  '\t\t\t\tvar to: int = options[rng.randi_range(0, options.size() - 1)]',
  '\t\t\t\ttiles[gap] = tiles[to]',
  '\t\t\t\ttiles[to] = 0',
  '\t\t\t\tlast = gap',
  '\t\t\t\tgap = to',
  '\t\t\tif check_screen(screen, tiles):',
  '\t\t\t\tvar t0 = tiles[0]',
  '\t\t\t\ttiles[0] = tiles[1]',
  '\t\t\t\ttiles[1] = t0',
  '\t\t\treturn tiles',
  '\t\t"rings":',
  '\t\t\tvar rings: Array = []',
  '\t\t\tvar start: Array = screen.get("start", [])',
  '\t\t\tfor i in int(screen.get("rings", 0)):',
  '\t\t\t\trings.append(int(start[i]) if i < start.size() else 0)',
  '\t\t\treturn rings',
  '\t\t"circuit":',
  '\t\t\tvar rot: Array = []',
  '\t\t\tvar cells: Array = screen.get("cells", [])',
  '\t\t\tfor i in cells.size():',
  '\t\t\t\tvar fixed: bool = cells[i]["piece"] in ["empty", "cross"] or i == int(screen.get("source", 0)) or i == int(screen.get("sink", -1))',
  '\t\t\t\trot.append(int(cells[i]["rot"]) if fixed else (int(cells[i]["rot"]) + 1 + rng.randi_range(0, 2)) % 4)',
  '\t\t\tif circuit_joined(screen, rot):',
  '\t\t\t\tfor i in cells.size():',
  '\t\t\t\t\tif not (cells[i]["piece"] in ["empty", "cross"] or i == int(screen.get("source", 0)) or i == int(screen.get("sink", -1))):',
  '\t\t\t\t\t\trot[i] = (int(rot[i]) + 1) % 4',
  '\t\t\treturn rot',
  '\t\t"levers":',
  '\t\t\tvar on: Array = []',
  '\t\t\tvar starts: Array = screen.get("startOn", [])',
  '\t\t\tfor i in (screen.get("switches", []) as Array).size():',
  '\t\t\t\ton.append(bool(starts[i]) if i < starts.size() else false)',
  '\t\t\treturn on',
  '\t\t"ordering":',
  '\t\t\tvar items := _strs(screen.get("items", []))',
  '\t\t\titems.reverse()',
  '\t\t\treturn items',
  '\treturn []',
];
