import type { EngineAdapter, ElementOutput, EngineOutput, GeneratedFile } from './engines';
import { fingerprint } from './engines';
import type { HandoffIR, IrEvent, IrThing } from './ir';

/**
 * The Godot 4 adapter: GDScript and Resources.
 *
 * Every project gets the same small runtime (addons/vcgs_runtime): a game
 * state autoload, a scene-flow player, an interactable base and Resource
 * classes. Everything under the output folder is generated from the story and
 * is rewritten on each export; nobody edits it by hand.
 */

const RUNTIME = 'addons/vcgs_runtime';
const HEADER = '# Generated by VC Game Studio. Edit the story, not this file.';
const VERSION = 'godot-1';

// ---------------------------------------------------------------- literals

/** A GDScript (and .tres) literal for plain data. */
export const gd = (value: unknown, indent = ''): string => {
  if (value === null || value === undefined) return 'null';
  if (typeof value === 'string') return JSON.stringify(value);
  if (typeof value === 'number') return Number.isFinite(value) ? String(value) : '0';
  if (typeof value === 'boolean') return value ? 'true' : 'false';
  const inner = `${indent}\t`;
  if (Array.isArray(value)) {
    if (value.length === 0) return '[]';
    return `[\n${value.map((v) => `${inner}${gd(v, inner)},`).join('\n')}\n${indent}]`;
  }
  const entries = Object.entries(value as Record<string, unknown>).filter(([, v]) => v !== undefined);
  if (entries.length === 0) return '{}';
  // Short records stay on one line so the tables read as tables.
  const flat = entries.every(([, v]) => v === null || typeof v !== 'object');
  if (flat && entries.length <= 8) return `{ ${entries.map(([k, v]) => `${JSON.stringify(k)}: ${gd(v)}`).join(', ')} }`;
  return `{\n${entries.map(([k, v]) => `${inner}${JSON.stringify(k)}: ${gd(v, inner)},`).join('\n')}\n${indent}}`;
};

const color = (hex: string): string => {
  const m = /^#?([0-9a-f]{6})$/i.exec(hex.trim());
  const n = m ? parseInt(m[1]!, 16) : 0xd9607a;
  const c = (shift: number) => (((n >> shift) & 255) / 255).toFixed(3).replace(/\.?0+$/, '') || '0';
  return `Color(${c(16)}, ${c(8)}, ${c(0)}, 1)`;
};

/** A text Resource (.tres) for one of the runtime's Resource classes. */
const tres = (scriptClass: string, script: string, fields: Record<string, string>): string =>
  [
    `[gd_resource type="Resource" script_class="${scriptClass}" load_steps=2 format=3]`,
    '',
    `[ext_resource type="Script" path="res://${RUNTIME}/${script}" id="1_script"]`,
    '',
    '[resource]',
    'script = ExtResource("1_script")',
    ...Object.entries(fields).map(([k, v]) => `${k} = ${v}`),
    '',
  ].join('\n');

const eventData = (e: IrEvent): Record<string, unknown> => ({
  kind: e.kind,
  label: e.label,
  ...(e.ref ? { ref: e.ref } : {}),
  ...(e.line ? { line: e.line } : {}),
  ...(e.seconds !== undefined ? { seconds: e.seconds } : {}),
  ...(e.shots !== undefined ? { shots: e.shots } : {}),
  ...(e.endsWhen ? { ends_when: e.endsWhen } : {}),
  ...(e.condition ? { condition: e.condition } : {}),
  ...(e.mainLabel !== undefined ? { main_label: e.mainLabel } : {}),
});

// ---------------------------------------------------------------- the runtime

const runtime = (): GeneratedFile[] => {
  const file = (name: string, lines: string[]): GeneratedFile => ({ path: `${RUNTIME}/${name}`, content: `${lines.join('\n')}\n`, kind: 'runtime' });
  const element = (cls: string, extra: string[]) =>
    file(`${cls.replace('VCGS', '').toLowerCase()}.gd`, [
      '# VCGS Runtime for Godot 4.',
      `class_name ${cls}`,
      'extends Resource',
      '',
      '@export var key := ""',
      '@export var code := ""',
      '@export var display_name := ""',
      '@export_multiline var description := ""',
      '## Every other field written in VC Game Studio, by name.',
      '@export var details: Dictionary = {}',
      ...extra,
    ]);
  return [
    file('game_state.gd', [
      '# VCGS Runtime for Godot 4. Add this file as an autoload named GameState',
      '# (Project > Project Settings > Globals > Autoload).',
      'class_name VCGSGameState',
      'extends Node',
      '',
      'signal flag_changed(flag: String, value: String)',
      'signal object_state_changed(object_key: String, state: String)',
      'signal item_changed(item_key: String, count: int)',
      'signal trigger_fired(trigger_key: String)',
      '',
      'var flags: Dictionary = {}',
      'var object_states: Dictionary = {}',
      'var items: Dictionary = {}',
      'var arcs: Dictionary = {}',
      'var chosen: Dictionary = {}',
      '',
      'func get_flag(flag: String, default_value: String = "") -> String:',
      '\treturn str(flags.get(flag, default_value))',
      '',
      'func set_flag(flag: String, value: String) -> void:',
      '\tif flags.get(flag) == value:',
      '\t\treturn',
      '\tflags[flag] = value',
      '\tflag_changed.emit(flag, value)',
      '',
      'func set_object_state(object_key: String, state: String) -> void:',
      '\tobject_states[object_key] = state',
      '\tobject_state_changed.emit(object_key, state)',
      '',
      'func has_item(item_key: String) -> bool:',
      '\treturn int(items.get(item_key, 0)) > 0',
      '',
      'func give_item(item_key: String, count: int = 1) -> void:',
      '\titems[item_key] = int(items.get(item_key, 0)) + count',
      '\titem_changed.emit(item_key, items[item_key])',
      '',
      'func consume_item(item_key: String, count: int = 1) -> void:',
      '\titems[item_key] = max(0, int(items.get(item_key, 0)) - count)',
      '\titem_changed.emit(item_key, items[item_key])',
      '',
      '## Move a character along their arc: +1 for growth, -1 for a setback.',
      'func arc_add(character_key: String, amount: int = 1) -> void:',
      '\tarcs[character_key] = int(arcs.get(character_key, 0)) + amount',
      '',
      'func remember_choice(choice_key: String, option: String) -> void:',
      '\tchosen[choice_key] = option',
    ]),
    file('scene_flow.gd', [
      '# VCGS Runtime for Godot 4.',
      'class_name VCGSSceneFlow',
      'extends Node',
      '## Plays a scene\'s timeline in order and says what each event needs.',
      '## Your game answers (shows the line, plays the cinematic, hands back',
      '## control) and calls advance() or choose() when it is done.',
      '',
      'signal event_started(event: Dictionary)',
      'signal dialogue_requested(line_id: String)',
      'signal cinematic_requested(cinematic_key: String)',
      'signal free_play_started(ends_when: String)',
      'signal choice_requested(choice_key: String, options: Array)',
      'signal scene_finished(next_key: String)',
      '',
      'var _track: Array = []',
      'var _index := -1',
      'var _branch := -1',
      '',
      '## The main track, in playing order. Generated scenes fill this in.',
      'func events() -> Array:',
      '\treturn []',
      '',
      '## Each other option of a choice: the index it leaves from, its events, and where it rejoins.',
      'func branches() -> Array:',
      '\treturn []',
      '',
      '## What plays after this scene on the story graph.',
      'func next_node() -> String:',
      '\treturn ""',
      '',
      'func start() -> void:',
      '\t_track = events()',
      '\t_index = -1',
      '\t_branch = -1',
      '\tadvance()',
      '',
      '## Call when the current event is done.',
      'func advance() -> void:',
      '\t_index += 1',
      '\tif _index >= _track.size():',
      '\t\tif _branch >= 0:',
      '\t\t\tvar rejoin: int = branches()[_branch].get("rejoin", -1)',
      '\t\t\t_branch = -1',
      '\t\t\t_track = events()',
      '\t\t\tif rejoin >= 0:',
      '\t\t\t\t_index = rejoin - 1',
      '\t\t\t\tadvance()',
      '\t\t\t\treturn',
      '\t\tscene_finished.emit(next_node())',
      '\t\treturn',
      '\tvar event: Dictionary = _track[_index]',
      '\tevent_started.emit(event)',
      '\tmatch event.get("kind", ""):',
      '\t\t"dialogue":',
      '\t\t\tdialogue_requested.emit(event.get("line", ""))',
      '\t\t"cinematic":',
      '\t\t\tcinematic_requested.emit(event.get("ref", ""))',
      '\t\t"freePlay":',
      '\t\t\tfree_play_started.emit(event.get("ends_when", ""))',
      '\t\t"choice":',
      '\t\t\tchoice_requested.emit(event.get("ref", ""), _options_at(_index))',
      '',
      '## Call with the option the player picked: 0 carries on, 1 and up take a branch.',
      'func choose(option: int) -> void:',
      '\tif option <= 0:',
      '\t\tadvance()',
      '\t\treturn',
      '\tvar from_here: Array = []',
      '\tfor i in branches().size():',
      '\t\tif branches()[i].get("from", -1) == _index:',
      '\t\t\tfrom_here.append(i)',
      '\tif option - 1 >= from_here.size():',
      '\t\tadvance()',
      '\t\treturn',
      '\t_branch = from_here[option - 1]',
      '\t_track = branches()[_branch].get("events", [])',
      '\t_index = -1',
      '\tadvance()',
      '',
      'func _options_at(index: int) -> Array:',
      '\tvar options: Array = [events()[index].get("main_label", "")]',
      '\tfor branch in branches():',
      '\t\tif branch.get("from", -1) == index:',
      '\t\t\toptions.append(branch.get("label", ""))',
      '\treturn options',
    ]),
    file('interactable.gd', [
      '# VCGS Runtime for Godot 4.',
      'class_name VCGSInteractable',
      'extends Node',
      '## An object the player can use. Generated subclasses give its states and',
      '## interactions; attach one to the object\'s node in your scene.',
      '',
      'signal state_changed(state: String)',
      '',
      'var state := ""',
      '',
      'func object_key() -> String:',
      '\treturn ""',
      '',
      'func states() -> Array:',
      '\treturn []',
      '',
      'func initial_state() -> String:',
      '\treturn ""',
      '',
      'func interactions() -> Array:',
      '\treturn []',
      '',
      '## The GameState autoload, found whether or not this node is in the tree yet.',
      'func _game() -> VCGSGameState:',
      '\tvar tree := get_tree() if is_inside_tree() else Engine.get_main_loop() as SceneTree',
      '\treturn tree.root.get_node_or_null("GameState") as VCGSGameState if tree else null',
      '',
      'func _ready() -> void:',
      '\t_settle()',
      '',
      '## Take up the saved state, or where the object starts, the first time it is needed.',
      'func _settle() -> void:',
      '\tif state != "":',
      '\t\treturn',
      '\tvar game := _game()',
      '\tstate = str(game.object_states.get(object_key(), initial_state())) if game else initial_state()',
      '',
      '## The verbs the player can use right now.',
      'func available_verbs() -> Array:',
      '\t_settle()',
      '\tvar verbs: Array = []',
      '\tfor i in interactions():',
      '\t\tif i.get("when", "") == "" or i.get("when", "") == state:',
      '\t\t\tverbs.append(i.get("verb", ""))',
      '\treturn verbs',
      '',
      'func interact(verb: String) -> bool:',
      '\t_settle()',
      '\tvar game := _game()',
      '\tfor i in interactions():',
      '\t\tif i.get("verb", "") != verb:',
      '\t\t\tcontinue',
      '\t\tif i.get("when", "") != "" and i.get("when", "") != state:',
      '\t\t\tcontinue',
      '\t\tif i.get("becomes", "") != "":',
      '\t\t\tstate = i["becomes"]',
      '\t\t\tif game:',
      '\t\t\t\tgame.set_object_state(object_key(), state)',
      '\t\t\tstate_changed.emit(state)',
      '\t\tif game and i.has("sets"):',
      '\t\t\tgame.set_flag(i["sets"]["flag"], i["sets"]["value"])',
      '\t\tif game and i.get("fires", "") != "":',
      '\t\t\tVCGSRules.fire(i["fires"], game)',
      '\t\treturn true',
      '\treturn false',
    ]),
    element('VCGSCharacter', ['@export var role := ""', '@export var arc := ""', '@export var color := Color.WHITE']),
    element('VCGSItem', []),
    element('VCGSLocation', []),
    element('VCGSCinematic', ['@export var seconds := 0.0', '@export var shots := 1']),
    element('VCGSPuzzle', ['@export var states: Array = []']),
    file('README.md', [
      '# VCGS Runtime for Godot 4',
      '',
      'The small runtime that VC Game Studio\'s generated files use. It is the',
      'same for every project and is safe to commit.',
      '',
      '- `game_state.gd`: add it as an autoload named **GameState**.',
      '- `scene_flow.gd`: each generated scene extends it. Connect its signals',
      '  to your dialogue box, cinematic player and free-play code.',
      '- `interactable.gd`: each generated object extends it.',
      '- The Resource classes hold characters, items, locations, cinematics',
      '  and puzzles.',
    ]),
  ];
};

// ---------------------------------------------------------------- generation

const thingFields = (t: IrThing): Record<string, string> => ({
  key: gd(t.ident.key),
  code: gd(t.code),
  display_name: gd(t.name),
  description: gd(t.notes),
  details: gd(Object.fromEntries(Object.entries(t.fields).filter(([k]) => k !== 'seconds' && k !== 'shots'))),
});

export const generateGodot = (ir: HandoffIR, outputPath: string): EngineOutput => {
  const root = outputPath.replace(/^res:\/\//, '').replace(/\/+$/, '') || 'vcgs/generated';
  const files: GeneratedFile[] = [...runtime()];
  const elements: ElementOutput[] = [];
  const add = (path: string, content: string) => {
    files.push({ path: `${root}/${path}`, content: content.endsWith('\n') ? content : `${content}\n`, kind: 'generated' });
    return `${root}/${path}`;
  };
  const row = (e: Omit<ElementOutput, 'fingerprint'>, data: unknown) =>
    elements.push({ ...e, fingerprint: fingerprint(`${VERSION}:${JSON.stringify(data)}`) });

  // Scenes: one flow controller each.
  for (const s of ir.scenes) {
    const branches = s.branches.map((b) => ({ label: b.label, from: b.from, events: b.events.map(eventData), rejoin: b.rejoin ?? -1 }));
    const path = add(
      `scenes/${s.ident.key}.gd`,
      [
        HEADER,
        `class_name Scene${s.ident.type}`,
        `extends VCGSSceneFlow`,
        `## ${s.code} ${s.name} · ${s.slug}`,
        ...(s.summary ? [`## ${s.summary}`] : []),
        '',
        `const KEY := ${gd(s.ident.key)}`,
        `const CODE := ${gd(s.code)}`,
        `const CONTENTS := ${gd(s.contents)}`,
        `const EVENTS := ${gd(s.main.map(eventData))}`,
        `const BRANCHES := ${gd(branches)}`,
        '',
        'func events() -> Array:',
        '\treturn EVENTS',
        '',
        'func branches() -> Array:',
        '\treturn BRANCHES',
        '',
        'func next_node() -> String:',
        `\treturn ${gd(s.next ?? '')}`,
      ].join('\n'),
    );
    row(
      { id: s.id, label: `${s.code} ${s.name}`.trim(), symbol: 'scene', group: 'Story', generates: `Scene flow controller · ${s.main.length} event${s.main.length === 1 ? '' : 's'}${s.branches.length ? ` · ${s.branches.length} branch${s.branches.length === 1 ? '' : 'es'}` : ''}`, files: [path] },
      s,
    );
  }

  for (const c of ir.cinematics) {
    const path = add(
      `cinematics/${c.ident.key}.tres`,
      tres('VCGSCinematic', 'cinematic.gd', { ...thingFields(c), seconds: gd(Number(c.fields.seconds ?? 0)), shots: gd(Number(c.fields.shots ?? 1)) }),
    );
    row({ id: c.id, label: `${c.code} ${c.name}`.trim(), symbol: 'cinematic', group: 'Story', generates: 'Cinematic resource · shots · camera notes', files: [path] }, c);
  }

  for (const c of ir.choices) {
    const path = add(
      `choices/${c.ident.key}.gd`,
      [
        HEADER,
        `class_name Choice${c.ident.type}`,
        'extends RefCounted',
        '',
        `const KEY := ${gd(c.ident.key)}`,
        `const CODE := ${gd(c.code)}`,
        `const SCENE := ${gd(c.scene ?? '')}`,
        `const PROMPT := ${gd(c.prompt)}`,
        '## Each option and the story node it leads to ("" carries on in the scene).',
        `const OPTIONS := ${gd(c.options.map((o) => ({ label: o.label, to: o.to ?? '' })))}`,
        '',
        '## Records the pick and returns where it leads.',
        'static func choose(option: int, game: VCGSGameState) -> String:',
        '\tif option < 0 or option >= OPTIONS.size():',
        '\t\treturn ""',
        '\tgame.remember_choice(KEY, OPTIONS[option]["label"])',
        '\treturn OPTIONS[option]["to"]',
      ].join('\n'),
    );
    row({ id: c.id, label: `${c.code} ${c.name}`.trim(), symbol: 'choice', group: 'Story', generates: `Choice script · ${c.options.length} option${c.options.length === 1 ? '' : 's'}`, files: [path] }, c);
  }

  const storyData = { spine: ir.spine, branches: ir.branches, subplots: ir.subplots, arcs: ir.arcs };
  const storyPath = add(
    'story/story_graph.gd',
    [
      HEADER,
      'class_name VCGSStory',
      'extends RefCounted',
      `## ${ir.project.name}: the spine in order, branches, subplots and character arcs.`,
      '',
      `const SPINE := ${gd(ir.spine.map((n) => ({ key: n.key, kind: n.kind, name: n.name })))}`,
      `const BRANCHES := ${gd(ir.branches)}`,
      `const SUBPLOTS := ${gd(ir.subplots.map((s) => ({ key: s.key, name: s.name, from: s.from, to: s.to, beats: s.beats.map((b) => b.key) })))}`,
      `const ARCS := ${gd(Object.fromEntries(ir.arcs.map((a) => [a.character, a.events.map((e) => ({ polarity: e.polarity, name: e.name, tied_to: e.tiedTo ?? '' }))])))}`,
      `const SCENES := ${gd(Object.fromEntries(ir.scenes.map((s) => [s.ident.key, `res://${root}/scenes/${s.ident.key}.gd`])))}`,
    ].join('\n'),
  );
  row({ id: 'story', label: 'Story graph', symbol: 'plotPoint', group: 'Story', generates: `Spine (${ir.spine.length}) · branches · subplots · arcs`, files: [storyPath] }, storyData);

  // People and words.
  for (const c of ir.characters) {
    const path = add(
      `characters/${c.ident.key}.tres`,
      tres('VCGSCharacter', 'character.gd', {
        key: gd(c.ident.key),
        code: gd(c.code),
        display_name: gd(c.name),
        description: gd(c.description),
        role: gd(c.role),
        arc: gd(c.arc),
        color: color(c.color),
      }),
    );
    row({ id: c.id, label: c.name, symbol: 'character', group: 'People + words', generates: 'Character resource · arc', files: [path] }, c);
  }

  const table = Object.fromEntries(ir.lines.map((l) => [l.id, { scene: l.scene, speaker: l.speaker ?? '', text: l.text, direction: l.direction, vo: l.vo }]));
  const dialoguePath = add(
    'dialogue/dialogue_table.gd',
    [
      HEADER,
      'class_name VCGSDialogue',
      'extends RefCounted',
      '',
      `const LINES := ${gd(table)}`,
      '',
      'static func line(line_id: String) -> Dictionary:',
      '\treturn LINES.get(line_id, {})',
    ].join('\n'),
  );
  // Production files live under a .gdignore so Godot doesn't import them.
  add('production/.gdignore', '');
  const csv = (cells: string[]) => cells.map((c) => (/[",\n]/.test(c) ? `"${c.replace(/"/g, '""')}"` : c)).join(',');
  const voPath = add(
    'production/vo_cues.csv',
    [csv(['line', 'scene', 'speaker', 'text', 'direction', 'status']), ...ir.lines.filter((l) => l.vo !== 'none').map((l) => csv([l.id, l.scene, l.speaker ?? '', l.text, l.direction, l.vo]))].join('\n'),
  );
  row({ id: 'dialogue', label: `Dialogue (${ir.lines.length} line${ir.lines.length === 1 ? '' : 's'})`, symbol: 'dialogue', group: 'People + words', generates: 'Dialogue table · VO cue list', files: [dialoguePath, voPath] }, ir.lines);

  // The world.
  for (const o of ir.objects) {
    if (o.kind === 'puzzle') {
      const path = add(`puzzles/${o.ident.key}.tres`, tres('VCGSPuzzle', 'puzzle.gd', { key: gd(o.ident.key), code: gd(o.code), display_name: gd(o.name), description: gd(o.notes), details: gd(o.fields), states: gd(o.states) }));
      row({ id: o.id, label: o.name, symbol: 'puzzle', group: 'World', generates: 'Puzzle resource · hints · fail state', files: [path] }, o);
      continue;
    }
    const interactions = o.interactions.map((i) => ({
      verb: i.verb,
      ...(i.when ? { when: i.when } : {}),
      ...(i.becomes ? { becomes: i.becomes } : {}),
      ...(i.sets ? { sets: { flag: i.sets.flag, value: i.sets.value } } : {}),
      ...(i.fires ? { fires: i.fires } : {}),
    }));
    const path = add(
      `objects/${o.ident.key}.gd`,
      [
        HEADER,
        `class_name Object${o.ident.type}`,
        'extends VCGSInteractable',
        `## ${o.code} ${o.name}`.trim(),
        ...(o.fields.assetNotes ? [`## Asset notes: ${o.fields.assetNotes}`] : []),
        '',
        `const KEY := ${gd(o.ident.key)}`,
        `const STATES := ${gd(o.states)}`,
        `const INTERACTIONS := ${gd(interactions)}`,
        '',
        'func object_key() -> String:',
        '\treturn KEY',
        '',
        'func states() -> Array:',
        '\treturn STATES',
        '',
        'func initial_state() -> String:',
        `\treturn ${gd(o.initial ?? '')}`,
        '',
        'func interactions() -> Array:',
        '\treturn INTERACTIONS',
      ].join('\n'),
    );
    row({ id: o.id, label: o.name, symbol: 'object', group: 'World', generates: o.states.length ? 'Interactable · state machine' : 'Interactable stub', files: [path] }, o);
  }
  for (const [list, symbol, cls, script, label] of [
    [ir.items, 'inventory', 'VCGSItem', 'item.gd', 'Item definition'],
    [ir.locations, 'environment', 'VCGSLocation', 'location.gd', 'Location data · ambience cues'],
  ] as const) {
    for (const t of list) {
      const path = add(`${cls === 'VCGSItem' ? 'items' : 'locations'}/${t.ident.key}.tres`, tres(cls, script, thingFields(t)));
      row({ id: t.id, label: t.name, symbol, group: 'World', generates: label, files: [path] }, t);
    }
  }

  // Logic: one rules script for every flag, trigger and gate.
  const rulesPath = `${root}/logic/rules.gd`;
  const gates = ir.triggers.filter((t) => t.kind === 'gate');
  add(
    'logic/rules.gd',
    [
      HEADER,
      'class_name VCGSRules',
      'extends RefCounted',
      '',
      '## Every state the game remembers: its values and where it starts.',
      `const FLAGS := ${gd(Object.fromEntries(ir.flags.map((f) => [f.ident.key, { values: f.values, initial: f.initial }])))}`,
      '',
      `const TRIGGERS := ${gd(Object.fromEntries(ir.triggers.filter((t) => t.kind === 'trigger').map((t) => [t.ident.key, { fires_when: t.condition, does: t.effect, ...(t.sets ? { sets: t.sets } : {}) }])))}`,
      '',
      `const GATES := ${gd(Object.fromEntries(gates.map((g) => [g.ident.key, { needs: g.condition, holds: g.effect }])))}`,
      '',
      '## Put every flag where it starts. Call once when a new game begins.',
      'static func reset(game: VCGSGameState) -> void:',
      '\tfor flag in FLAGS:',
      '\t\tgame.flags[flag] = FLAGS[flag]["initial"]',
      '',
      'static func fire(trigger_key: String, game: VCGSGameState) -> void:',
      '\tvar trigger: Dictionary = TRIGGERS.get(trigger_key, {})',
      '\tif trigger.has("sets"):',
      '\t\tgame.set_flag(trigger["sets"]["flag"], trigger["sets"]["value"])',
      '\tgame.trigger_fired.emit(trigger_key)',
      '',
      '## Conditions are written in plain words in VC Game Studio for now. Each',
      '## gate opens and keeps its words beside it until conditions become rules.',
      'static func gate_open(gate_key: String, _game: VCGSGameState) -> bool:',
      ...(gates.length
        ? ['\tmatch gate_key:', ...gates.flatMap((g) => [`\t\t${gd(g.ident.key)}:`, `\t\t\treturn true  # Needs: ${g.condition || '(not written yet)'}`])]
        : []),
      '\treturn true',
    ].join('\n'),
  );
  for (const f of ir.flags) {
    row({ id: f.id, label: f.name, symbol: 'state', group: 'Logic', generates: `Game state flag · ${f.values.join(' / ')}`, files: [rulesPath] }, f);
  }
  for (const t of ir.triggers) {
    row({ id: t.id, label: t.name, symbol: t.kind, group: 'Logic', generates: t.kind === 'gate' ? 'Gate check (condition in words)' : 'Event trigger', files: [rulesPath] }, t);
  }

  const readme = add(
    'README.md',
    [
      `# ${ir.project.name} — generated by VC Game Studio`,
      '',
      'Everything in this folder is rewritten on each export. Change the story in',
      'VC Game Studio, not these files.',
      '',
      '1. Add `res://addons/vcgs_runtime/game_state.gd` as an autoload named **GameState**.',
      '2. Put a scene\'s flow controller (`scenes/`) on a node, connect its signals, and call `start()`.',
      '3. Attach an object\'s script (`objects/`) to its node; call `interact("Pull")` from your input code.',
      '4. Call `VCGSRules.reset(GameState)` when a new game begins.',
    ].join('\n'),
  );
  add(
    'vcgs_manifest.json',
    JSON.stringify(
      {
        generator: 'VC Game Studio',
        adapter: VERSION,
        engine: 'godot',
        project: ir.project,
        elements: elements.map((e) => ({ id: e.id, label: e.label, files: e.files, fingerprint: e.fingerprint })),
      },
      null,
      2,
    ),
  );
  void readme;
  return { files, elements };
};

export const godot: EngineAdapter = {
  id: 'godot',
  name: 'Godot 4',
  language: 'GDScript · Resources',
  available: true,
  defaultOutputPath: 'res://vcgs/generated',
  runtimeName: 'VCGS Runtime for Godot',
  setup: ['Add res://addons/vcgs_runtime/game_state.gd as an autoload named GameState.', 'Call VCGSRules.reset(GameState) when a new game begins.'],
  generate: generateGodot,
};
