import { tasksMarkdown, todoLines, withCodeNotes, withoutNotes } from './notes';
import { customRegion } from './custom';
import type { EngineAdapter, ElementOutput, EngineOutput, GeneratedFile } from './engines';
import { fingerprint } from './engines';
import { DESIGN_LISTS, type HandoffIR, type IrThing, type Ident } from './ir';
import { JSON_FORMAT } from './json';
import { ASMDEF, RUNTIME_FILES } from './unity-runtime';
import { EDITOR_ASMDEF, LEVEL_EDITOR_FILES, LEVEL_RUNTIME_FILES, levelJson } from './unity-levels';
import { markupInline } from '../inline';

/**
 * The Unity adapter: C# and ScriptableObjects. The runtime (Assets/VCGS/Runtime)
 * is plain C# for the story's logic with thin MonoBehaviour and
 * ScriptableObject wrappers; the generated folder holds story.json (read by
 * the runtime), StoryKeys.cs (every key, for game code) and an asset per
 * character, item, location and cinematic. Every file comes with a .meta
 * whose GUID is derived from its path, so the assets keep their references
 * across exports.
 */

const VERSION = 'unity-1';
const RUNTIME = 'Assets/VCGS/Runtime';
const EDITOR = 'Assets/VCGS/Editor';
const HEADER = '// Generated by VC Game Studio. Edit the story, not this file.';

/** A stable Unity GUID (32 hex digits) for a path. */
export const guidFor = (path: string): string => [0, 1, 2, 3].map((n) => fingerprint(`vcgs:${n}:${path}`)).join('');

const meta = (path: string, importer: string): string =>
  [`fileFormatVersion: 2`, `guid: ${guidFor(path)}`, importer, ''].join('\n');

const IMPORTERS = {
  script: ['MonoImporter:', '  externalObjects: {}', '  serializedVersion: 2', '  defaultReferences: []', '  executionOrder: 0', '  icon: {instanceID: 0}', '  userData: ', '  assetBundleName: ', '  assetBundleVariant: '].join('\n'),
  asset: ['NativeFormatImporter:', '  externalObjects: {}', '  mainObjectFileID: 11400000', '  userData: ', '  assetBundleName: ', '  assetBundleVariant: '].join('\n'),
  text: ['TextScriptImporter:', '  externalObjects: {}', '  userData: ', '  assetBundleName: ', '  assetBundleVariant: '].join('\n'),
  asmdef: ['AssemblyDefinitionImporter:', '  externalObjects: {}', '  userData: ', '  assetBundleName: ', '  assetBundleVariant: '].join('\n'),
  folder: ['folderAsset: yes', 'DefaultImporter:', '  externalObjects: {}', '  userData: ', '  assetBundleName: ', '  assetBundleVariant: '].join('\n'),
};

/** A YAML scalar Unity reads back as the same string. */
export const yamlString = (s: string): string => (s === '' ? "''" : JSON.stringify(s));

const yamlColor = (hex: string): string => {
  const m = /^#?([0-9a-f]{6})$/i.exec(hex.trim());
  const n = m ? parseInt(m[1]!, 16) : 0xffffff;
  const c = (shift: number) => Number((((n >> shift) & 255) / 255).toFixed(3));
  return `{r: ${c(16)}, g: ${c(8)}, b: ${c(0)}, a: 1}`;
};

/** A ScriptableObject asset in Unity's YAML, for one of the runtime's asset classes. */
const scriptableObject = (name: string, className: string, fields: string[]): string =>
  [
    '%YAML 1.1',
    '%TAG !u! tag:unity3d.com,2011:',
    '--- !u!114 &11400000',
    'MonoBehaviour:',
    '  m_ObjectHideFlags: 0',
    '  m_CorrespondingSourceObject: {fileID: 0}',
    '  m_PrefabInstance: {fileID: 0}',
    '  m_PrefabAsset: {fileID: 0}',
    '  m_GameObject: {fileID: 0}',
    '  m_Enabled: 1',
    '  m_EditorHideFlags: 0',
    // The class's own script file (Unity needs one class per file, named for it).
    `  m_Script: {fileID: 11500000, guid: ${guidFor(`${RUNTIME}/${className}.cs`)}, type: 3}`,
    `  m_Name: ${yamlString(name)}`,
    '  m_EditorClassIdentifier: ',
    ...fields.map((f) => `  ${f}`),
    '',
  ].join('\n');

const elementFields = (key: string, code: string, name: string, description: string, details: Record<string, string>): string[] => {
  const entries = Object.entries(details).filter(([k]) => k !== 'seconds' && k !== 'shots');
  return [
    `key: ${yamlString(key)}`,
    `code: ${yamlString(code)}`,
    `displayName: ${yamlString(name)}`,
    `description: ${yamlString(description)}`,
    entries.length ? 'details:' : 'details: []',
    ...entries.flatMap(([k, v]) => [`- name: ${yamlString(k)}`, `  value: ${yamlString(v)}`]),
  ];
};

/** A key's constants, each with the open comments and tasks on its element as TODO lines above it (spec §16). */
const keyClass = (name: string, summary: string, list: { ident: Ident }[], notes: HandoffIR['notes'] = []): string[] =>
  list.length
    ? [
        `    /// <summary>${summary}</summary>`,
        `    public static partial class ${name}`,
        '    {',
        ...list.flatMap((x) => [
          ...todoLines(notes.filter((n) => n.on.kind === 'object' && n.on.key === x.ident.key), '//', '        '),
          `        public const string ${x.ident.type} = ${JSON.stringify(x.ident.key)};`,
        ]),
        '    }',
        '',
      ]
    : [];

const storyKeys = (ir: HandoffIR): string => {
  return [
    HEADER,
    '',
    'namespace VCGS.Keys',
    '{',
    ...keyClass('Scenes', 'Story scenes, for VcgsSceneFlow.', ir.scenes, ir.notes),
    ...keyClass('Choices', 'Choices, on the graph and in scenes.', ir.choices, ir.notes),
    ...keyClass('Characters', 'Characters and NPCs.', ir.characters, ir.notes),
    ...keyClass('Objects', 'Interactive objects, for VcgsInteractable.', ir.objects.filter((o) => o.kind === 'object'), ir.notes),
    ...keyClass('Puzzles', 'Puzzles.', ir.objects.filter((o) => o.kind === 'puzzle'), ir.notes),
    ...keyClass('Items', 'Inventory items.', ir.items, ir.notes),
    ...keyClass('Locations', 'Locations.', ir.locations, ir.notes),
    ...DESIGN_LISTS.flatMap((d) => keyClass(d.folder, `${d.folder}: VcgsElement assets under ${d.folder}/.`, ir[d.list], ir.notes)),
    ...keyClass('Cinematics', 'Cinematics.', ir.cinematics, ir.notes),
    ...keyClass('Flags', 'States the game remembers (GameState.GetFlag / SetFlag).', ir.flags, ir.notes),
    ...keyClass('Triggers', 'Triggers (Rules.Fire).', ir.triggers.filter((t) => t.kind === 'trigger'), ir.notes),
    ...keyClass('Gates', 'Gates (Rules.GateOpen).', ir.triggers.filter((t) => t.kind === 'gate'), ir.notes),
    ...customRegion('//', 'code', '    ', 'Your own keys and helpers (or a partial class of your own in another file)'),
    '}',
    '',
  ].join('\n');
};

const README = (ir: HandoffIR, root: string) => `# ${ir.project.name} — generated by VC Game Studio

Everything in this folder is rewritten on each export. Change the story in VC
Game Studio, not these files. The runtime (\`${RUNTIME}\`) is the same for every
project.

1. Add an empty GameObject to your first scene with **VcgsGame** on it, and
   give it \`${root}/story.json\`. It stays loaded between scenes.
2. For a story scene, add **VcgsSceneFlow** with the scene's key
   (\`VCGS.Keys.Scenes\`), then connect to \`Player\`'s events
   (\`DialogueRequested\` — or \`DualRequested\` for two lines at once —, \`CinematicRequested\`, \`FreePlayStarted\`,
   \`ChoiceRequested\`, \`EncounterRequested\` (and \`GameOver\`), \`SceneFinished\`)
   and call \`Player.Advance()\` or \`Player.Choose(i)\`, or \`Player.Win()\` /
   \`Player.Lose()\` once an encounter is played.
3. For an object, add **VcgsInteractable** with its key (\`VCGS.Keys.Objects\`)
   and call \`Interact("Pull")\` from your input code.
4. \`VcgsGame.Instance.State\` is the playthrough: flags, items, arcs and the
   rest. Triggers fire, puzzles solve themselves, quests start and complete
   (\`QuestStarted\`, \`QuestCompleted\`), lore is discovered (\`LoreDiscovered\`,
   \`KnownLore\`, \`Story.LoreEntry\`) and mechanics become available
   (\`MechanicAvailable\`, \`HasMechanic\`, \`Story.MechanicDetail\`) as their
   conditions come true;
   \`StoryWalker\` follows the graph between scenes.
5. **Puzzles** built in the Puzzle Creator play their steps as the studio does
   (order, links, time limits on \`State.Clock\`, which VcgsGame advances,
   rewards, wrong moves, resets): \`PuzzleStep\`, \`StepDone\`, \`HintGiven\` and
   \`PuzzleCue\` (what solving one plays). An interaction that opens a **screen
   puzzle** raises \`ScreenRequested\` instead of acting: show your screen, then
   call \`Interactions.AnswerScreen(state, object, answer)\` (see
   \`PuzzleRuntime.CheckScreen\` for each kind's answer). **VcgsScreenPanel** is a
   stand-in to try them with.

To try the story before your game has its own screens, add **VcgsCodex** next
to VcgsGame: a Codex button (and C) opens the quest log and the lore found. The
same text is \`new Codex(state).Text()\` for your own UI.

The Characters, Items, Locations and Cinematics folders hold a ScriptableObject
per element, for designers to find in the Project window. So do Lore, Quests,
Mechanics and Encounters (\`VcgsLore\`, \`VcgsQuest\`, \`VcgsMechanic\`,
\`VcgsEncounter\`): design definitions for a codex, a quest log or tuning to
read. They are data; their logic lives in flags and triggers.
`;

export const generateUnity = (ir: HandoffIR, outputPath: string): EngineOutput => {
  const root = outputPath.replace(/\/+$/, '') || 'Assets/VCGS/Generated';
  const files: GeneratedFile[] = [];
  const folders = new Set<string>();
  const put = (path: string, content: string, kind: GeneratedFile['kind'], importer: keyof typeof IMPORTERS) => {
    files.push({ path, content: content.endsWith('\n') ? content : `${content}\n`, kind });
    files.push({ path: `${path}.meta`, content: meta(path, IMPORTERS[importer]), kind });
    // Every folder up to Assets gets a .meta too, so its GUID is stable.
    const parts = path.split('/');
    for (let i = 2; i < parts.length; i++) folders.add(parts.slice(0, i).join('/'));
    return path;
  };

  for (const [name, source] of Object.entries(RUNTIME_FILES)) put(`${RUNTIME}/${name}`, source, 'runtime', 'script');
  if (ir.levels.length) {
    for (const [name, source] of Object.entries(LEVEL_RUNTIME_FILES)) put(`${RUNTIME}/Levels/${name}`, source, 'runtime', 'script');
    for (const [name, source] of Object.entries(LEVEL_EDITOR_FILES)) put(`${EDITOR}/${name}`, source, 'runtime', 'script');
    put(`${EDITOR}/VCGS.Editor.asmdef`, EDITOR_ASMDEF, 'runtime', 'asmdef');
  }
  put(`${RUNTIME}/VCGS.Runtime.asmdef`, ASMDEF, 'runtime', 'asmdef');

  const elements: ElementOutput[] = [];
  const row = (e: Omit<ElementOutput, 'fingerprint'>, data: unknown) => elements.push({ ...e, fingerprint: fingerprint(`${VERSION}:${JSON.stringify(data)}`) });

  // A line with emphasis also carries it as TextMeshPro rich text.
  const tmp = (text: string) => markupInline(text, (run, st) => `${st.bold ? '<b>' : ''}${st.italic ? '<i>' : ''}${st.underline ? '<u>' : ''}${run}${st.underline ? '</u>' : ''}${st.italic ? '</i>' : ''}${st.bold ? '</b>' : ''}`);
  const lines = ir.lines.map((l) => (l.styled ? { ...l, rich: tmp(l.styled) } : l));
  const storyPath = put(`${root}/story.json`, JSON.stringify({ ...JSON_FORMAT, generator: 'VC Game Studio', ...withoutNotes(ir), lines }, null, 2), 'generated', 'text');
  const keysPath = put(`${root}/StoryKeys.cs`, storyKeys(ir), 'generated', 'script');
  put(`${root}/README.md`, README(ir, root), 'generated', 'text');

  row({ id: 'story', label: 'Story graph', symbol: 'plotPoint', group: 'Story', generates: `story.json · StoryKeys.cs · ${ir.graph.length} nodes`, files: [storyPath, keysPath] }, { graph: ir.graph, keys: storyKeys(withoutNotes(ir)) });
  for (const s of ir.scenes) row({ id: s.id, label: `${s.code} ${s.name}`.trim(), symbol: 'scene', group: 'Story', generates: `ScenePlayer data · ${s.main.length} events · Keys.Scenes.${s.ident.type}`, files: [storyPath] }, s);
  for (const c of ir.choices) row({ id: c.id, label: `${c.code} ${c.name}`.trim(), symbol: 'choice', group: 'Story', generates: `Choice · ${c.options.length} options`, files: [storyPath] }, c);

  const asset = (folder: string, t: IrThing | { ident: Ident; name: string }, className: string, fields: string[]) =>
    put(`${root}/${folder}/${t.ident.key}.asset`, scriptableObject(t.name, className, fields), 'generated', 'asset');

  for (const c of ir.cinematics) {
    const shots = c.shots ?? [];
    const path = asset('Cinematics', c, 'VcgsCinematic', [
      ...elementFields(c.ident.key, c.code, c.name, c.notes, c.fields),
      `seconds: ${Number(c.fields.seconds ?? 0)}`,
      `shots: ${Number(c.fields.shots ?? 1)}`,
      `skippable: ${c.fields.skippable === 'Not skippable' ? 0 : 1}`,
      shots.length ? 'shotList:' : 'shotList: []',
      ...shots.flatMap((s) => [
        `- framing: ${yamlString(s.framing)}`,
        `  move: ${yamlString(s.move)}`,
        `  lens: ${yamlString(s.lens)}`,
        s.characters.length ? '  characters:' : '  characters: []',
        ...s.characters.map((k) => `  - ${yamlString(k)}`),
        `  action: ${yamlString(s.action)}`,
        `  line: ${yamlString(s.line ?? '')}`,
        `  audio: ${yamlString(s.audio)}`,
        `  vfx: ${yamlString(s.vfx)}`,
        `  seconds: ${s.seconds}`,
        `  transition: ${yamlString(s.transition)}`,
        `  notes: ${yamlString(s.notes)}`,
      ]),
    ]);
    row({ id: c.id, label: `${c.code} ${c.name}`.trim(), symbol: 'cinematic', group: 'Story', generates: `VcgsCinematic asset${shots.length ? ` · ${shots.length} shots` : ''}`, files: [path] }, c);
  }
  for (const c of ir.characters) {
    const path = asset('Characters', c, 'VcgsCharacter', [
      ...elementFields(c.ident.key, c.code, c.name, c.description, {}),
      `role: ${yamlString(c.role)}`,
      `arc: ${yamlString(c.arc)}`,
      `color: ${yamlColor(c.color)}`,
    ]);
    row({ id: c.id, label: c.name, symbol: 'character', group: 'People + words', generates: 'VcgsCharacter asset', files: [path] }, c);
  }
  row({ id: 'dialogue', label: `Dialogue (${ir.lines.length} lines)`, symbol: 'dialogue', group: 'People + words', generates: 'Dialogue lines in story.json', files: [storyPath] }, ir.lines);
  for (const o of ir.objects) {
    row({ id: o.id, label: o.name, symbol: o.kind, group: 'World', generates: o.kind === 'puzzle' ? 'Puzzle · solved by rule' : `VcgsInteractable · ${o.interactions.length} interaction${o.interactions.length === 1 ? '' : 's'}`, files: [storyPath] }, o);
  }
  for (const [list, folder, className, symbol, label] of [
    [ir.items, 'Items', 'VcgsItem', 'inventory', 'VcgsItem asset'],
    [ir.locations, 'Locations', 'VcgsLocation', 'environment', 'VcgsLocation asset'],
  ] as const) {
    for (const t of list) {
      const path = asset(folder, t, className, elementFields(t.ident.key, t.code, t.name, t.notes, t.fields));
      row({ id: t.id, label: t.name, symbol, group: 'World', generates: label, files: [path] }, t);
    }
  }
  for (const d of DESIGN_LISTS) {
    const className = `Vcgs${d.type[0]!.toUpperCase()}${d.type.slice(1)}`;
    for (const t of ir[d.list]) {
      const path = asset(d.folder, t, className, elementFields(t.ident.key, t.code, t.name, t.notes, t.fields));
      row({ id: t.id, label: `${t.code} ${t.name}`.trim(), symbol: d.type, group: d.group, generates: `${className} asset`, files: [path] }, t);
    }
  }
  for (const f of ir.flags) row({ id: f.id, label: f.name, symbol: 'state', group: 'Logic', generates: `GameState flag · ${f.values.join(' / ')}`, files: [storyPath] }, f);
  for (const t of ir.triggers) row({ id: t.id, label: t.name, symbol: t.kind, group: 'Logic', generates: t.kind === 'gate' ? 'Rules.GateOpen' : 'Trigger · fires by rule', files: [storyPath] }, t);

  // Levels: their data, which VCGS › Update level from data… builds into the open scene.
  const names: Record<string, string> = Object.fromEntries(
    [...ir.characters, ...ir.objects, ...ir.items, ...ir.locations, ...DESIGN_LISTS.flatMap((d) => ir[d.list]), ...ir.cinematics, ...ir.flags, ...ir.triggers, ...ir.choices, ...ir.scenes].map((x) => [x.ident.key, x.name]),
  );
  for (const level of ir.levels) {
    const path = put(`${root}/Levels/${level.key}.json`, levelJson(level, names), 'generated', 'text');
    row({ id: level.guid, label: level.name, symbol: 'environment', group: 'World', generates: `Level data · ${level.items.length} items → VCGS › Update level (${level.export_name})`, files: [path] }, level);
  }
  put(
    `${root}/vcgs_manifest.json`,
    JSON.stringify(
      {
        generator: 'VC Game Studio',
        adapter: VERSION,
        engine: 'unity',
        project: ir.project,
        elements: elements.map((e) => ({ id: e.id, label: e.label, files: e.files, fingerprint: e.fingerprint })),
        levels: ir.levels.map((l) => ({
          guid: l.guid,
          name: l.name,
          data: `${root}/Levels/${l.key}.json`,
          revision: l.revision,
          items: l.items.map((i) => ({ guid: i.guid, export_name: i.export_name, source: `${l.name} / ${i.name}`, engine_ref: `${l.export_name}/${i.export_name}`, revision: i.revision, replacement_locked: i.replacement_locked })),
        })),
      },
      null,
      2,
    ),
    'generated',
    'text',
  );

  for (const folder of [...folders].sort()) files.push({ path: `${folder}.meta`, content: meta(folder, IMPORTERS.folder), kind: folder.startsWith(RUNTIME) || RUNTIME.startsWith(folder) || folder.startsWith(EDITOR) ? 'runtime' : 'generated' });
  // Open comments and tasks (spec §16), for the Unity team.
  const tasksPath = put(
    `${root}/TASKS.md`,
    tasksMarkdown(ir, 'Unity', (n) =>
      n.on.kind === 'object'
        ? `VCGS.Keys.*.${n.on.type} ("${n.on.key}")`
        : n.on.kind === 'level'
          ? `${n.on.export_name} (VcgsLevel)`
          : n.on.kind === 'levelItem'
            ? `${ir.levels.find((l) => l.items.some((i) => i.guid === n.on.key))?.export_name ?? ''}/${n.on.export_name}`
            : n.on.key,
    ),
    'generated',
    'text',
  );
  row({ id: 'tasks', label: `Comments and tasks (${ir.notes.length})`, symbol: 'plotPoint', group: 'Story', generates: 'TASKS.md · TODO(VCGS) in StoryKeys.cs', files: [tasksPath] }, ir.notes);
  return { files: withCodeNotes(files, ir), elements };
};

export const unity: EngineAdapter = {
  id: 'unity',
  name: 'Unity 6',
  language: 'C# · ScriptableObjects',
  available: true,
  defaultOutputPath: 'Assets/VCGS/Generated',
  runtimeName: 'VCGS Runtime for Unity',
  setup: [
    'Add a GameObject with VcgsGame to your first scene and give it Assets/VCGS/Generated/story.json.',
    'Put VcgsSceneFlow (with its scene key) in each scene, and VcgsInteractable on each usable object.',
    'For a level, open its scene and run VCGS › Update level from data…, choosing Assets/VCGS/Generated/Levels/<level>.json; run it again after each export.',
  ],
  generate: generateUnity,
};
