import type { EngineAdapter, ElementOutput, EngineOutput, GeneratedFile } from './engines';
import { fingerprint } from './engines';
import { DESIGN_LISTS, type HandoffIR, type Ident } from './ir';
import { JSON_FORMAT } from './json';
import { VCGS_CORE_H } from './unreal-core';
import { buildLevelScript, LEVEL_PLUGIN_FILES, levelJsonUnreal } from './unreal-levels';
import { markupInline } from '../inline';

/** Emphasis as URichTextBlock markup: one style row per run, named for what it combines. */
const richText = (text: string) =>
  markupInline(text, (run, st) => `<${[st.bold && 'Bold', st.italic && 'Italic', st.underline && 'Underline'].filter(Boolean).join('')}>${run}</>`);

/**
 * The Unreal adapter: a plugin (Plugins/VCGS) and the story's data.
 *
 * The plugin's logic is VcgsCore.h, portable C++17 that plays story.json the
 * way the Godot and Unity runtimes do; around it, a game-instance subsystem
 * (the playthrough), a scene-flow and an interactable component with
 * Blueprint events and functions, and DataTable row structs. The generated
 * side is story.json, VcgsStoryKeys.h with every key, DataTable CSVs for
 * characters, items, locations, cinematics, shots and lines, and an editor
 * Python script that imports them as DataTable assets.
 */

const VERSION = 'unreal-1';
const PLUGIN = 'Plugins/VCGS';
const SOURCE = `${PLUGIN}/Source/VCGS`;
const HEADER = '// Generated by VC Game Studio. Edit the story, not this file.';
const RUNTIME_HEAD = '// VCGS Runtime for Unreal. The same for every project; safe to commit.';

export const PLUGIN_FILES: Record<string, string> = {
  'VCGS.uplugin': `${JSON.stringify(
    {
      FileVersion: 3,
      Version: 1,
      VersionName: '1.0',
      FriendlyName: 'VCGS Runtime',
      Description: 'Plays a story written in VC Game Studio: its scenes, choices, rules and state.',
      Category: 'Gameplay',
      CreatedBy: 'VC Game Studio',
      CanContainContent: true,
      Modules: [{ Name: 'VCGS', Type: 'Runtime', LoadingPhase: 'Default' }],
      // Freeform floors and ceilings are procedural meshes.
      Plugins: [{ Name: 'ProceduralMeshComponent', Enabled: true }],
    },
    null,
    2,
  )}\n`,

  'Source/VCGS/VCGS.Build.cs': `${RUNTIME_HEAD}
using UnrealBuildTool;

public class VCGS : ModuleRules
{
    public VCGS(ReadOnlyTargetRules Target) : base(Target)
    {
        PCHUsage = PCHUsageMode.UseExplicitOrSharedPCHs;
        PublicDependencyModuleNames.AddRange(new string[] { "Core", "CoreUObject", "Engine", "InputCore", "ApplicationCore", "ProceduralMeshComponent" });
    }
}
`,

  'Source/VCGS/Public/VcgsCore.h': VCGS_CORE_H,

  'Source/VCGS/Public/VcgsConvert.h': `${RUNTIME_HEAD}
#pragma once

#include "CoreMinimal.h"
#include <string>

/** Between Unreal's strings and the core's UTF-8. */
namespace VcgsConvert
{
    inline std::string ToStd(const FString& S) { return std::string(TCHAR_TO_UTF8(*S)); }
    inline FString ToF(const std::string& S) { return FString(UTF8_TO_TCHAR(S.c_str())); }
}
`,

  'Source/VCGS/Public/VcgsTypes.h': `${RUNTIME_HEAD}
#pragma once

#include "CoreMinimal.h"
#include "Engine/DataTable.h"
#include "VcgsTypes.generated.h"

/** One option of a choice, for a menu: whether it can be picked, and why not. */
USTRUCT(BlueprintType)
struct VCGS_API FVcgsOption
{
    GENERATED_BODY()

    UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "VCGS") int32 Index = 0;
    UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "VCGS") FString Label;
    UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "VCGS") bool bAvailable = true;
    UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "VCGS") FString Why;
};

/** A row of DT_Characters. */
USTRUCT(BlueprintType)
struct VCGS_API FVcgsCharacterRow : public FTableRowBase
{
    GENERATED_BODY()

    UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "VCGS") FString Key;
    UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "VCGS") FString Code;
    UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "VCGS") FString DisplayName;
    UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "VCGS", meta = (MultiLine = true)) FString Description;
    UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "VCGS") FString Role;
    UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "VCGS") FString Arc;
    UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "VCGS") FLinearColor Color = FLinearColor::White;
};

/** A row of DT_Items, DT_Locations, DT_Lore, DT_Quests, DT_Mechanics or DT_Encounters: its fields as "name: value" lines in Details. */
USTRUCT(BlueprintType)
struct VCGS_API FVcgsElementRow : public FTableRowBase
{
    GENERATED_BODY()

    UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "VCGS") FString Key;
    UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "VCGS") FString Code;
    UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "VCGS") FString DisplayName;
    UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "VCGS", meta = (MultiLine = true)) FString Description;
    UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "VCGS", meta = (MultiLine = true)) FString Details;
};

/** A row of DT_Cinematics. */
USTRUCT(BlueprintType)
struct VCGS_API FVcgsCinematicRow : public FTableRowBase
{
    GENERATED_BODY()

    UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "VCGS") FString Key;
    UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "VCGS") FString Code;
    UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "VCGS") FString DisplayName;
    UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "VCGS", meta = (MultiLine = true)) FString Description;
    UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "VCGS") float Seconds = 0.f;
    UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "VCGS") int32 Shots = 1;
    UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "VCGS") bool bSkippable = true;
};

/** A row of DT_Shots: one shot of a cinematic, in order. */
USTRUCT(BlueprintType)
struct VCGS_API FVcgsShotRow : public FTableRowBase
{
    GENERATED_BODY()

    UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "VCGS") FString Cinematic;
    UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "VCGS") int32 Index = 0;
    UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "VCGS") FString Framing;
    UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "VCGS") FString Move;
    UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "VCGS") FString Lens;
    UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "VCGS") FString Characters;
    UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "VCGS", meta = (MultiLine = true)) FString Action;
    UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "VCGS") FString Line;
    UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "VCGS") FString Audio;
    UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "VCGS") FString Vfx;
    UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "VCGS") float Seconds = 0.f;
    UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "VCGS") FString Transition;
    UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "VCGS", meta = (MultiLine = true)) FString Notes;
};

/** A row of DT_Lines: one line of dialogue, for subtitles and the VO team. */
USTRUCT(BlueprintType)
struct VCGS_API FVcgsLineRow : public FTableRowBase
{
    GENERATED_BODY()

    UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "VCGS") FString Scene;
    UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "VCGS") FString Speaker;
    UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "VCGS", meta = (MultiLine = true)) FString Text;
    UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "VCGS") FString Direction;
    UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "VCGS") FString Vo;
    /** The line with its emphasis, for a URichTextBlock: <Bold>, <Italic>, <Underline> and their pairs (<BoldItalic>…) as rows of its text style set. Empty when it has none. */
    UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "VCGS", meta = (MultiLine = true)) FString Rich;
    /** Dual dialogue: the line this one is spoken at the same time as. */
    UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "VCGS") FString DualWith;
};
`,

  'Source/VCGS/Public/VcgsSubsystem.h': `${RUNTIME_HEAD}
#pragma once

#include "CoreMinimal.h"
#include "Subsystems/GameInstanceSubsystem.h"
#include "VcgsCore.h"
#include "VcgsTypes.h"
#include <memory>
#include "VcgsSubsystem.generated.h"

DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam(FVcgsQuestSignature, const FString&, Quest);

/**
 * The one playthrough of the story: reads story.json when the game starts and
 * keeps its state across levels. Everything here is callable from Blueprints.
 */
UCLASS()
class VCGS_API UVcgsSubsystem : public UGameInstanceSubsystem
{
    GENERATED_BODY()

public:
    virtual void Initialize(FSubsystemCollectionBase& Collection) override;
    virtual void Deinitialize() override;

    /** story.json, relative to the project's Content folder. */
    static FString StoryPath();

    /** Load a story from its JSON (done for you at start). */
    UFUNCTION(BlueprintCallable, Category = "VCGS") bool LoadStory(const FString& Json);
    /** Put everything where it starts. */
    UFUNCTION(BlueprintCallable, Category = "VCGS") void NewGame();
    UFUNCTION(BlueprintPure, Category = "VCGS") bool IsLoaded() const;
    UFUNCTION(BlueprintPure, Category = "VCGS") FString GetStoryName() const;
    /** The graph node the story starts at. */
    UFUNCTION(BlueprintPure, Category = "VCGS") FString GetStart() const;

    UFUNCTION(BlueprintPure, Category = "VCGS|State") FString GetFlag(const FString& Flag) const;
    UFUNCTION(BlueprintCallable, Category = "VCGS|State") void SetFlag(const FString& Flag, const FString& Value);
    UFUNCTION(BlueprintPure, Category = "VCGS|State") FString GetObjectState(const FString& Object) const;
    UFUNCTION(BlueprintPure, Category = "VCGS|State") bool HasItem(const FString& Item) const;
    UFUNCTION(BlueprintCallable, Category = "VCGS|State") void GiveItem(const FString& Item);
    UFUNCTION(BlueprintCallable, Category = "VCGS|State") void TakeItem(const FString& Item);
    UFUNCTION(BlueprintPure, Category = "VCGS|State") int32 GetArc(const FString& Character) const;
    UFUNCTION(BlueprintPure, Category = "VCGS|State") bool IsSolved(const FString& Puzzle) const;
    UFUNCTION(BlueprintPure, Category = "VCGS|State") bool WasVisited(const FString& Scene) const;
    UFUNCTION(BlueprintPure, Category = "VCGS|State") bool GateOpen(const FString& Gate) const;
    /** "" (not started), "active" or "done". Quests start and complete by their rules. */
    UFUNCTION(BlueprintPure, Category = "VCGS|State") FString GetQuestState(const FString& Quest) const;
    UFUNCTION(BlueprintPure, Category = "VCGS|State") bool WasWon(const FString& Encounter) const;
    /** Encounters the player has come to, in the order met (won or not): the codex. */
    UFUNCTION(BlueprintPure, Category = "VCGS|State") TArray<FString> GetMetEncounters() const;
    /** Characters the player has met (heard speak), in the order met. */
    UFUNCTION(BlueprintPure, Category = "VCGS|State") TArray<FString> GetMetCharacters() const;
    /** Items the player has ever held, in the order found (carried or not now). */
    UFUNCTION(BlueprintPure, Category = "VCGS|State") TArray<FString> GetFoundItems() const;
    /** Locations the player has been to (a scene set there played), in the order visited. */
    UFUNCTION(BlueprintPure, Category = "VCGS|State") TArray<FString> GetVisitedLocations() const;
    /** Objects the player has used, in the order first used. */
    UFUNCTION(BlueprintPure, Category = "VCGS|State") TArray<FString> GetUsedObjects() const;
    /** Lore the player has come across, in the order they found it: the codex. */
    UFUNCTION(BlueprintPure, Category = "VCGS|State") TArray<FString> GetKnownLore() const;
    UFUNCTION(BlueprintPure, Category = "VCGS|State") bool KnowsLore(const FString& Lore) const;
    /** A lore entry's name and text, for the codex. */
    UFUNCTION(BlueprintPure, Category = "VCGS|Story") void GetLoreEntry(const FString& Lore, FString& Name, FString& Text) const;
    UFUNCTION(BlueprintPure, Category = "VCGS|State") bool HasMechanic(const FString& Mechanic) const;
    /** A mechanic's field as written in the studio, such as "tuning" (empty when it has none). */
    UFUNCTION(BlueprintPure, Category = "VCGS|Story") FString GetMechanicDetail(const FString& Mechanic, const FString& Field) const;

    UPROPERTY(BlueprintAssignable, Category = "VCGS|State") FVcgsQuestSignature OnQuestStarted;
    UPROPERTY(BlueprintAssignable, Category = "VCGS|State") FVcgsQuestSignature OnQuestCompleted;
    UPROPERTY(BlueprintAssignable, Category = "VCGS|State") FVcgsQuestSignature OnLoreDiscovered;

    /** The codex in words: the quest log, the characters met, the locations visited, the items found, the objects used, the mechanics, the encounters met, then the lore found (AVcgsCodexHUD draws it). */
    /** With a Search, only the entries it finds (ignoring case), in the sections that have any. */
    UFUNCTION(BlueprintPure, Category = "VCGS|Codex") FString GetCodexText(const FString& Search = TEXT(""), const FString& Section = TEXT(""), const FString& Sort = TEXT("")) const;
    /** The sections this story's codex has ("quests", "lore"…), in order: what a filter by section offers. */
    UFUNCTION(BlueprintPure, Category = "VCGS|Codex") TArray<FString> GetCodexSections() const;
    /** Bookmark a codex entry ("lore:the_drowned_order"), or take its bookmark off; true when it is bookmarked now. */
    UFUNCTION(BlueprintCallable, Category = "VCGS|Codex") bool ToggleCodexBookmark(const FString& Entry);
    UFUNCTION(BlueprintPure, Category = "VCGS|Codex") bool IsCodexBookmarked(const FString& Entry) const;
    /** The player's note on a codex entry ("" takes it off); it ends the entry in the codex, and a search finds it. */
    UFUNCTION(BlueprintCallable, Category = "VCGS|Codex") void SetCodexNote(const FString& Entry, const FString& Note);
    UFUNCTION(BlueprintPure, Category = "VCGS|Codex") FString GetCodexNote(const FString& Entry) const;
    /** The player's notes in words, to export: each entry with a note, in the codex's order. */
    UFUNCTION(BlueprintPure, Category = "VCGS|Codex") FString GetCodexNotesText() const;
    /** Save the notes as a text file (Saved/CodexNotes.txt when Path is empty); returns where, or "" if it could not. */
    UFUNCTION(BlueprintCallable, Category = "VCGS|Codex") FString ExportCodexNotes(const FString& Path = TEXT(""));
    /**
     * Email the notes: open the mail app with them ("<story> codex notes"). When
     * they are too long for a mail link (bWhole false), they go on the clipboard
     * and the mail says so. Returns the link, or "" with no codex.
     */
    UFUNCTION(BlueprintCallable, Category = "VCGS|Codex") FString EmailCodexNotes(bool& bWhole, bool bOpen = true);
    /**
     * Text the notes: open the messages app with them (an sms: link). When they
     * are too long for a text link (bWhole false), they go on the clipboard and
     * the message says so. Returns the link, or "" with no codex.
     */
    UFUNCTION(BlueprintCallable, Category = "VCGS|Codex") FString TextCodexNotes(bool& bWhole, bool bOpen = true);
    /**
     * Print the notes: save them as a page (Saved/CodexNotes.html when Path is
     * empty) and, with bOpen, open it in the browser to print from. Returns
     * where, or "" if it could not.
     */
    UFUNCTION(BlueprintCallable, Category = "VCGS|Codex") FString PrintCodexNotes(const FString& Path = TEXT(""), bool bOpen = true);
    /**
     * Import exported notes (from a codex here, the studio's or another engine's):
     * each "SECTION · entry" block is matched to an entry by section and name,
     * and those notes are set (the others stay). Returns how many; Skipped gets
     * the headings that match nothing in the codex (yet).
     */
    UFUNCTION(BlueprintCallable, Category = "VCGS|Codex") int32 ImportCodexNotesText(const FString& Text, TArray<FString>& Skipped);
    /** The same from a text file (Saved/CodexNotes.txt when Path is empty); -1 if it could not be read. */
    UFUNCTION(BlueprintCallable, Category = "VCGS|Codex") int32 ImportCodexNotes(TArray<FString>& Skipped, const FString& Path = TEXT(""));
    /** Share the notes: put them on the clipboard, as the text the export writes. Returns it. */
    UFUNCTION(BlueprintCallable, Category = "VCGS|Codex") FString CopyCodexNotes();
    /** Take in notes someone shared: read them from the clipboard (as ImportCodexNotesText does). */
    UFUNCTION(BlueprintCallable, Category = "VCGS|Codex") int32 PasteCodexNotes(TArray<FString>& Skipped);
    /**
     * Sync the notes with a sync file (Saved/CodexNotesSync.json when Path is
     * empty): merge it in, for each entry the newer note winning, and write the
     * result back. Put it in a folder that syncs (a cloud drive, Steam Cloud) to
     * share the notes across devices. Returns how many notes the file changed
     * here, or -1 when it could not sync. The codex HUD syncs on its own.
     */
    UFUNCTION(BlueprintCallable, Category = "VCGS|Codex") int32 SyncCodexNotes(const FString& Path = TEXT(""));
    /** The codex entries shown (for a search, section and sort), in order, by key: what a cursor moves through. */
    UFUNCTION(BlueprintPure, Category = "VCGS|Codex") TArray<FString> GetCodexEntries(const FString& Search = TEXT(""), const FString& Section = TEXT(""), const FString& Sort = TEXT("")) const;
    /** Quest, character, location, item, object, mechanic, encounter and lore updates since the codex was last read. */
    UFUNCTION(BlueprintCallable, Category = "VCGS|Codex") int32 GetCodexNewCount();
    UFUNCTION(BlueprintCallable, Category = "VCGS|Codex") void MarkCodexRead();
    /** The core's codex, for C++ (null until a story is loaded). */
    vcgs::Codex* CodexState() const { return CodexData.get(); }
    UPROPERTY(BlueprintAssignable, Category = "VCGS|State") FVcgsQuestSignature OnMechanicAvailable;
    UPROPERTY(BlueprintAssignable, Category = "VCGS|State") FVcgsQuestSignature OnEncounterMet;
    UPROPERTY(BlueprintAssignable, Category = "VCGS|State") FVcgsQuestSignature OnEncounterWon;
    UPROPERTY(BlueprintAssignable, Category = "VCGS|State") FVcgsQuestSignature OnCharacterMet;
    UPROPERTY(BlueprintAssignable, Category = "VCGS|State") FVcgsQuestSignature OnItemFound;
    UPROPERTY(BlueprintAssignable, Category = "VCGS|State") FVcgsQuestSignature OnLocationVisited;
    UPROPERTY(BlueprintAssignable, Category = "VCGS|State") FVcgsQuestSignature OnObjectUsed;

    /** Where a graph node goes next: its first route whose conditions hold, else on along the spine. */
    UFUNCTION(BlueprintCallable, Category = "VCGS|Story") FString Onward(const FString& Node);
    /** "scene", "choice", "plotPoint", "cinematic", "begin", "end"... */
    UFUNCTION(BlueprintPure, Category = "VCGS|Story") FString NodeKind(const FString& Node) const;
    /** "ending", "gameOver", or empty when the node goes on. */
    UFUNCTION(BlueprintPure, Category = "VCGS|Story") FString NodeOutcome(const FString& Node) const;
    /** A choice on the graph: every option that can be picked now. */
    UFUNCTION(BlueprintCallable, Category = "VCGS|Story") TArray<FVcgsOption> ChoiceOptions(const FString& Choice) const;
    /** Pick an option of a choice on the graph; returns the node it leads to (empty if it can't be picked). */
    UFUNCTION(BlueprintCallable, Category = "VCGS|Story") FString ChooseOnGraph(const FString& Choice, int32 Option);
    UFUNCTION(BlueprintPure, Category = "VCGS|Story") void GetLine(const FString& LineId, FString& Speaker, FString& Text, FString& Direction) const;

    /** The core's playthrough, for C++ (null until a story is loaded). */
    vcgs::GameState* State() const { return Game.get(); }

private:
    std::unique_ptr<vcgs::Story> StoryData;
    std::unique_ptr<vcgs::GameState> Game;
    std::unique_ptr<vcgs::Codex> CodexData;
};
`,

  'Source/VCGS/Private/VcgsSubsystem.cpp': `${RUNTIME_HEAD}
#include "VcgsSubsystem.h"
#include "VcgsConvert.h"
#include "HAL/PlatformApplicationMisc.h"
#include "HAL/PlatformProcess.h"
#include "Misc/FileHelper.h"
#include "Misc/Paths.h"

using VcgsConvert::ToF;
using VcgsConvert::ToStd;

FString UVcgsSubsystem::StoryPath()
{
    return TEXT("VCGS/Generated/story.json");
}

void UVcgsSubsystem::Initialize(FSubsystemCollectionBase& Collection)
{
    Super::Initialize(Collection);
    FString Json;
    const FString Path = FPaths::ProjectContentDir() / StoryPath();
    if (FFileHelper::LoadFileToString(Json, *Path))
    {
        LoadStory(Json);
    }
    else
    {
        UE_LOG(LogTemp, Warning, TEXT("VCGS: no story at %s. Export it from VC Game Studio."), *Path);
    }
}

void UVcgsSubsystem::Deinitialize()
{
    Game.reset();
    StoryData.reset();
    Super::Deinitialize();
}

bool UVcgsSubsystem::LoadStory(const FString& Json)
{
    std::string Error;
    vcgs::Value Root = vcgs::JsonReader::Parse(ToStd(Json), &Error);
    if (!Root.IsObject())
    {
        UE_LOG(LogTemp, Error, TEXT("VCGS: story.json could not be read (%s)."), *ToF(Error));
        return false;
    }
    CodexData.reset();
    Game.reset();
    StoryData = std::make_unique<vcgs::Story>(std::move(Root));
    Game = std::make_unique<vcgs::GameState>(*StoryData);
    CodexData = std::make_unique<vcgs::Codex>(*Game);
    Game->OnQuestStarted = [this](const std::string& Quest) { OnQuestStarted.Broadcast(ToF(Quest)); };
    Game->OnQuestCompleted = [this](const std::string& Quest) { OnQuestCompleted.Broadcast(ToF(Quest)); };
    Game->OnLoreDiscovered = [this](const std::string& Lore) { OnLoreDiscovered.Broadcast(ToF(Lore)); };
    Game->OnMechanicAvailable = [this](const std::string& Mechanic) { OnMechanicAvailable.Broadcast(ToF(Mechanic)); };
    Game->OnEncounterMet = [this](const std::string& Encounter) { OnEncounterMet.Broadcast(ToF(Encounter)); };
    Game->OnEncounterWon = [this](const std::string& Encounter) { OnEncounterWon.Broadcast(ToF(Encounter)); };
    Game->OnCharacterMet = [this](const std::string& Character) { OnCharacterMet.Broadcast(ToF(Character)); };
    Game->OnItemFound = [this](const std::string& Item) { OnItemFound.Broadcast(ToF(Item)); };
    Game->OnLocationVisited = [this](const std::string& Location) { OnLocationVisited.Broadcast(ToF(Location)); };
    Game->OnObjectUsed = [this](const std::string& Object) { OnObjectUsed.Broadcast(ToF(Object)); };
    return true;
}

void UVcgsSubsystem::NewGame()
{
    if (Game) Game->Reset();
}

bool UVcgsSubsystem::IsLoaded() const { return Game != nullptr; }
FString UVcgsSubsystem::GetStoryName() const { return StoryData ? ToF(StoryData->Name) : FString(); }
FString UVcgsSubsystem::GetStart() const { return StoryData ? ToF(StoryData->Start) : FString(); }

FString UVcgsSubsystem::GetFlag(const FString& Flag) const { return Game ? ToF(Game->GetFlag(ToStd(Flag))) : FString(); }
void UVcgsSubsystem::SetFlag(const FString& Flag, const FString& Value) { if (Game) Game->SetFlag(ToStd(Flag), ToStd(Value)); }
FString UVcgsSubsystem::GetObjectState(const FString& Object) const { return Game ? ToF(Game->GetObjectState(ToStd(Object))) : FString(); }
bool UVcgsSubsystem::HasItem(const FString& Item) const { return Game && Game->HasItem(ToStd(Item)); }
void UVcgsSubsystem::GiveItem(const FString& Item) { if (Game) Game->GiveItem(ToStd(Item)); }
void UVcgsSubsystem::TakeItem(const FString& Item) { if (Game) Game->TakeItem(ToStd(Item)); }
int32 UVcgsSubsystem::GetArc(const FString& Character) const { return Game ? Game->Arc(ToStd(Character)) : 0; }
bool UVcgsSubsystem::IsSolved(const FString& Puzzle) const { return Game && Game->Solved.count(ToStd(Puzzle)) > 0; }
bool UVcgsSubsystem::WasVisited(const FString& Scene) const { return Game && Game->Visited.count(ToStd(Scene)) > 0; }
bool UVcgsSubsystem::GateOpen(const FString& Gate) const { return !Game || vcgs::Rules::GateOpen(ToStd(Gate), *Game); }
FString UVcgsSubsystem::GetQuestState(const FString& Quest) const { return Game ? ToF(Game->QuestState(ToStd(Quest))) : FString(); }
bool UVcgsSubsystem::WasWon(const FString& Encounter) const { return Game && Game->WasWon(ToStd(Encounter)); }
FString UVcgsSubsystem::GetCodexText(const FString& Search, const FString& Section, const FString& Sort) const { return CodexData ? ToF(CodexData->Text(ToStd(Search), ToStd(Section), ToStd(Sort))) : FString(); }
bool UVcgsSubsystem::ToggleCodexBookmark(const FString& Entry) { return Game && Game->ToggleBookmark(ToStd(Entry)); }
bool UVcgsSubsystem::IsCodexBookmarked(const FString& Entry) const { return Game && Game->IsBookmarked(ToStd(Entry)); }
void UVcgsSubsystem::SetCodexNote(const FString& Entry, const FString& Note) { if (Game) Game->SetNote(ToStd(Entry), ToStd(Note)); }
FString UVcgsSubsystem::GetCodexNote(const FString& Entry) const { return Game ? ToF(Game->NoteFor(ToStd(Entry))) : FString(); }
FString UVcgsSubsystem::GetCodexNotesText() const { return CodexData ? ToF(CodexData->NotesText()) : FString(); }
int32 UVcgsSubsystem::ImportCodexNotesText(const FString& Text, TArray<FString>& Skipped)
{
    Skipped.Reset();
    if (!CodexData || !Game) return 0;
    const vcgs::Codex::ReadNotes Read = CodexData->NotesFrom(ToStd(Text));
    for (const auto& Note : Read.Notes) Game->SetNote(Note.first, Note.second);
    for (const std::string& Head : Read.Skipped) Skipped.Add(ToF(Head));
    return static_cast<int32>(Read.Notes.size());
}

FString UVcgsSubsystem::CopyCodexNotes()
{
    const FString Text = GetCodexNotesText();
    FPlatformApplicationMisc::ClipboardCopy(*Text);
    return Text;
}

int32 UVcgsSubsystem::PasteCodexNotes(TArray<FString>& Skipped)
{
    FString Text;
    FPlatformApplicationMisc::ClipboardPaste(Text);
    return ImportCodexNotesText(Text, Skipped);
}

int32 UVcgsSubsystem::SyncCodexNotes(const FString& Path)
{
    if (!Game || !StoryData) return -1;
    const FString Where = Path.IsEmpty() ? FPaths::ProjectSavedDir() / TEXT("CodexNotesSync.json") : Path;
    FString Stored;
    int32 Changed = 0;
    if (FFileHelper::LoadFileToString(Stored, *Where)) Changed = FMath::Max(0, Game->SyncNotes(ToStd(Stored)));
    const FString Text = ToF(Game->NotesSyncText(StoryData->Name));
    if (!(Text == Stored) && !FFileHelper::SaveStringToFile(Text, *Where, FFileHelper::EEncodingOptions::ForceUTF8WithoutBOM)) return -1;
    return Changed;
}

int32 UVcgsSubsystem::ImportCodexNotes(TArray<FString>& Skipped, const FString& Path)
{
    const FString Where = Path.IsEmpty() ? FPaths::ProjectSavedDir() / TEXT("CodexNotes.txt") : Path;
    FString Text;
    if (!FFileHelper::LoadFileToString(Text, *Where)) return -1;
    return ImportCodexNotesText(Text, Skipped);
}

FString UVcgsSubsystem::ExportCodexNotes(const FString& Path)
{
    if (!CodexData) return FString();
    const FString Where = Path.IsEmpty() ? FPaths::ProjectSavedDir() / TEXT("CodexNotes.txt") : Path;
    return FFileHelper::SaveStringToFile(ToF(CodexData->NotesText()), *Where, FFileHelper::EEncodingOptions::ForceUTF8WithoutBOM) ? Where : FString();
}
FString UVcgsSubsystem::EmailCodexNotes(bool& bWhole, bool bOpen)
{
    bWhole = false;
    if (!CodexData) return FString();
    const std::pair<std::string, bool> Mail = CodexData->NotesMailto();
    bWhole = Mail.second;
    if (!bWhole) CopyCodexNotes();
    const FString Url = ToF(Mail.first);
    if (bOpen) FPlatformProcess::LaunchURL(*Url, nullptr, nullptr);
    return Url;
}
FString UVcgsSubsystem::TextCodexNotes(bool& bWhole, bool bOpen)
{
    bWhole = false;
    if (!CodexData) return FString();
    const std::pair<std::string, bool> Sms = CodexData->NotesSms();
    bWhole = Sms.second;
    if (!bWhole) CopyCodexNotes();
    const FString Url = ToF(Sms.first);
    if (bOpen) FPlatformProcess::LaunchURL(*Url, nullptr, nullptr);
    return Url;
}
FString UVcgsSubsystem::PrintCodexNotes(const FString& Path, bool bOpen)
{
    if (!CodexData) return FString();
    const FString Where = Path.IsEmpty() ? FPaths::ProjectSavedDir() / TEXT("CodexNotes.html") : Path;
    if (!FFileHelper::SaveStringToFile(ToF(CodexData->NotesPage()), *Where, FFileHelper::EEncodingOptions::ForceUTF8WithoutBOM)) return FString();
    if (bOpen) FPlatformProcess::LaunchFileInDefaultExternalApplication(*FPaths::ConvertRelativePathToFull(Where));
    return Where;
}
TArray<FString> UVcgsSubsystem::GetCodexEntries(const FString& Search, const FString& Section, const FString& Sort) const
{
    TArray<FString> Keys;
    if (CodexData) for (const std::string& Key : CodexData->EntryKeys(ToStd(Search), ToStd(Section), ToStd(Sort))) Keys.Add(ToF(Key));
    return Keys;
}
TArray<FString> UVcgsSubsystem::GetCodexSections() const
{
    TArray<FString> Keys;
    if (CodexData) for (const std::string& Key : CodexData->SectionKeys()) Keys.Add(ToF(Key));
    return Keys;
}
int32 UVcgsSubsystem::GetCodexNewCount() { return CodexData ? CodexData->New() : 0; }
void UVcgsSubsystem::MarkCodexRead() { if (CodexData) CodexData->MarkRead(); }
TArray<FString> UVcgsSubsystem::GetMetEncounters() const
{
    TArray<FString> Met;
    if (Game) for (const std::string& Encounter : Game->MetEncounters) Met.Add(ToF(Encounter));
    return Met;
}
TArray<FString> UVcgsSubsystem::GetUsedObjects() const
{
    TArray<FString> Used;
    if (Game) for (const std::string& Object : Game->UsedObjects) Used.Add(ToF(Object));
    return Used;
}
TArray<FString> UVcgsSubsystem::GetVisitedLocations() const
{
    TArray<FString> Visited;
    if (Game) for (const std::string& Location : Game->VisitedLocations) Visited.Add(ToF(Location));
    return Visited;
}
TArray<FString> UVcgsSubsystem::GetFoundItems() const
{
    TArray<FString> Found;
    if (Game) for (const std::string& Item : Game->FoundItems) Found.Add(ToF(Item));
    return Found;
}
TArray<FString> UVcgsSubsystem::GetMetCharacters() const
{
    TArray<FString> Met;
    if (Game) for (const std::string& Character : Game->MetCharacters) Met.Add(ToF(Character));
    return Met;
}
TArray<FString> UVcgsSubsystem::GetKnownLore() const
{
    TArray<FString> Known;
    if (Game) for (const std::string& Lore : Game->KnownLore) Known.Add(ToF(Lore));
    return Known;
}
bool UVcgsSubsystem::KnowsLore(const FString& Lore) const { return Game && Game->KnowsLore(ToStd(Lore)); }
void UVcgsSubsystem::GetLoreEntry(const FString& Lore, FString& Name, FString& Text) const
{
    if (!StoryData) return;
    const std::string Key = ToStd(Lore);
    const vcgs::Value& Entry = vcgs::Story::Find(StoryData->Lore, Key);
    Name = ToF(Entry["name"].Str());
    Text = ToF(Entry["notes"].Str());
}
bool UVcgsSubsystem::HasMechanic(const FString& Mechanic) const { return Game && Game->HasMechanic(ToStd(Mechanic)); }
FString UVcgsSubsystem::GetMechanicDetail(const FString& Mechanic, const FString& Field) const
{
    return StoryData ? ToF(vcgs::Story::Find(StoryData->Mechanics, ToStd(Mechanic))["fields"][ToStd(Field)].Str()) : FString();
}

FString UVcgsSubsystem::Onward(const FString& Node) { return Game ? ToF(vcgs::StoryWalker::Onward(*Game, ToStd(Node))) : FString(); }
FString UVcgsSubsystem::NodeKind(const FString& Node) const { return Game ? ToF(vcgs::StoryWalker::KindOf(*Game, ToStd(Node))) : FString(); }
FString UVcgsSubsystem::NodeOutcome(const FString& Node) const { return Game ? ToF(vcgs::StoryWalker::OutcomeOf(*Game, ToStd(Node))) : FString(); }

TArray<FVcgsOption> UVcgsSubsystem::ChoiceOptions(const FString& Choice) const
{
    TArray<FVcgsOption> Options;
    if (!Game) return Options;
    for (int Index : vcgs::StoryWalker::Offered(*Game, ToStd(Choice)))
    {
        FVcgsOption Option;
        Option.Index = Index;
        Option.Label = ToF(vcgs::StoryWalker::OptionLabel(*Game, ToStd(Choice), Index));
        Options.Add(Option);
    }
    return Options;
}

FString UVcgsSubsystem::ChooseOnGraph(const FString& Choice, int32 Option)
{
    return Game ? ToF(vcgs::StoryWalker::Choose(*Game, ToStd(Choice), Option)) : FString();
}

void UVcgsSubsystem::GetLine(const FString& LineId, FString& Speaker, FString& Text, FString& Direction) const
{
    if (!Game) return;
    const vcgs::StoryWalker::Line Line = vcgs::StoryWalker::GetLine(*Game, ToStd(LineId));
    Speaker = ToF(Line.Speaker);
    Text = ToF(Line.Text);
    Direction = ToF(Line.Direction);
}
`,

  'Source/VCGS/Public/VcgsCodexHUD.h': `${RUNTIME_HEAD}
#pragma once

#include "CoreMinimal.h"
#include "GameFramework/HUD.h"
#include "InputCoreTypes.h"
#include <string>
#include "VcgsCodexHUD.generated.h"

class UVcgsSubsystem;
namespace vcgs { class Codex; }

/**
 * A codex screen to try the story with before the game has its own: a Codex
 * label in the top corner (it counts what is new) and, when open, a panel with
 * everything found so far. Set it as the game mode's HUD class; press CodexKey
 * (C) to open it, C or Escape to close, or call ToggleCodex. Press / to search:
 * type letters, digits and spaces (Backspace deletes), Enter to stop typing,
 * Escape to clear the search; or call SetCodexSearch from your own UI. Tab
 * shows the next section alone (then All again); or call SetCodexSection. S
 * orders each section: as found, newest first, A–Z; or call SetCodexSort. The
 * arrow keys move a cursor (▶) through the entries and B bookmarks the one it
 * is on (★); Tab reaches the bookmarks alone too. N writes a note on it: type
 * it, Enter keeps it, Escape leaves it. E saves every note as a text file
 * (ExportCodexNotes on the subsystem), and I reads it back (ImportCodexNotes).
 * Y copies the notes to share them, V takes in notes someone shared, M emails
 * them (EmailCodexNotes), T texts them (TextCodexNotes), and P opens them as a
 * page to print (PrintCodexNotes). The notes
 * sync with Saved/CodexNotesSync.json (SyncCodexNotes) when the codex opens,
 * every few seconds while it is open, and after each note.
 */
UCLASS()
class VCGS_API AVcgsCodexHUD : public AHUD
{
    GENERATED_BODY()

public:
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "VCGS") FKey CodexKey = EKeys::C;

    UFUNCTION(BlueprintCallable, Category = "VCGS") void ToggleCodex();
    UFUNCTION(BlueprintPure, Category = "VCGS") bool IsCodexOpen() const { return bCodexOpen; }
    /** Show only the codex entries that match ("" for everything). */
    UFUNCTION(BlueprintCallable, Category = "VCGS") void SetCodexSearch(const FString& Search);
    UFUNCTION(BlueprintPure, Category = "VCGS") FString GetCodexSearch() const;
    /** Show only one section ("quests", "lore"…; "" for all of them). */
    UFUNCTION(BlueprintCallable, Category = "VCGS") void SetCodexSection(const FString& Section);
    UFUNCTION(BlueprintPure, Category = "VCGS") FString GetCodexSection() const;
    /** Order each section: "found" (as found), "newest" (newest first) or "name" (A–Z). */
    UFUNCTION(BlueprintCallable, Category = "VCGS") void SetCodexSort(const FString& Sort);
    UFUNCTION(BlueprintPure, Category = "VCGS") FString GetCodexSort() const;
    UFUNCTION(BlueprintPure, Category = "VCGS") bool IsTypingSearch() const { return bTypingSearch; }

    virtual void DrawHUD() override;

private:
    bool bCodexOpen = false;
    bool bTypingSearch = false;
    std::string SearchText;
    std::string SectionKey;
    std::string SortKey = "found";
    std::string CursorKey;
    bool bTypingNote = false;
    /** Seconds since the notes last synced (they sync every few while the codex is open). */
    float SinceSync = 0.f;
    void SyncNotes();
    std::string NoteDraft;
    /** What just happened, shown in the panel (the notes saved, say). */
    std::string StatusText;
    /** Add the letters, digits and spaces just pressed to Text (Backspace deletes). */
    void TypeKeys(std::string& Text);
    /** Move the cursor to the next entry shown (1) or the one before (-1). */
    void MoveCursor(vcgs::Codex& Book, int Step);
    UVcgsSubsystem* Subsystem() const;
    /** While typing a search: add the keys just pressed to it. */
    void TypeSearch();
};
`,

  'Source/VCGS/Private/VcgsCodexHUD.cpp': `${RUNTIME_HEAD}
#include "VcgsCodexHUD.h"
#include "VcgsConvert.h"
#include "VcgsSubsystem.h"
#include "Engine/Canvas.h"
#include "Engine/GameInstance.h"
#include "Engine/World.h"
#include "GameFramework/PlayerController.h"

using VcgsConvert::ToF;
using VcgsConvert::ToStd;

UVcgsSubsystem* AVcgsCodexHUD::Subsystem() const
{
    UWorld* World = GetWorld();
    UGameInstance* GameInstance = World ? World->GetGameInstance() : nullptr;
    return GameInstance ? GameInstance->GetSubsystem<UVcgsSubsystem>() : nullptr;
}

void AVcgsCodexHUD::SetCodexSearch(const FString& Search) { SearchText = ToStd(Search); }
FString AVcgsCodexHUD::GetCodexSearch() const { return ToF(SearchText); }
void AVcgsCodexHUD::SetCodexSection(const FString& Section) { SectionKey = ToStd(Section); }
FString AVcgsCodexHUD::GetCodexSection() const { return ToF(SectionKey); }
void AVcgsCodexHUD::SetCodexSort(const FString& Sort)
{
    const std::string Key = ToStd(Sort);
    SortKey = Key == "newest" || Key == "name" ? Key : "found";
}
FString AVcgsCodexHUD::GetCodexSort() const { return ToF(SortKey); }

void AVcgsCodexHUD::TypeKeys(std::string& Text)
{
    static const FKey Letters[] = {EKeys::A, EKeys::B, EKeys::C, EKeys::D, EKeys::E, EKeys::F, EKeys::G, EKeys::H, EKeys::I, EKeys::J, EKeys::K, EKeys::L, EKeys::M,
                                   EKeys::N, EKeys::O, EKeys::P, EKeys::Q, EKeys::R, EKeys::S, EKeys::T, EKeys::U, EKeys::V, EKeys::W, EKeys::X, EKeys::Y, EKeys::Z};
    static const FKey Digits[] = {EKeys::Zero, EKeys::One, EKeys::Two, EKeys::Three, EKeys::Four, EKeys::Five, EKeys::Six, EKeys::Seven, EKeys::Eight, EKeys::Nine};
    for (int i = 0; i < 26; i++) if (PlayerOwner->WasInputKeyJustPressed(Letters[i])) Text += static_cast<char>('a' + i);
    for (int i = 0; i < 10; i++) if (PlayerOwner->WasInputKeyJustPressed(Digits[i])) Text += static_cast<char>('0' + i);
    if (PlayerOwner->WasInputKeyJustPressed(EKeys::SpaceBar)) Text += ' ';
    if (PlayerOwner->WasInputKeyJustPressed(EKeys::BackSpace) && !Text.empty()) Text.pop_back();
}

void AVcgsCodexHUD::TypeSearch()
{
    static const FKey Letters[] = {EKeys::A, EKeys::B, EKeys::C, EKeys::D, EKeys::E, EKeys::F, EKeys::G, EKeys::H, EKeys::I, EKeys::J, EKeys::K, EKeys::L, EKeys::M,
                                   EKeys::N, EKeys::O, EKeys::P, EKeys::Q, EKeys::R, EKeys::S, EKeys::T, EKeys::U, EKeys::V, EKeys::W, EKeys::X, EKeys::Y, EKeys::Z};
    static const FKey Digits[] = {EKeys::Zero, EKeys::One, EKeys::Two, EKeys::Three, EKeys::Four, EKeys::Five, EKeys::Six, EKeys::Seven, EKeys::Eight, EKeys::Nine};
    for (int i = 0; i < 26; i++) if (PlayerOwner->WasInputKeyJustPressed(Letters[i])) SearchText += static_cast<char>('a' + i);
    for (int i = 0; i < 10; i++) if (PlayerOwner->WasInputKeyJustPressed(Digits[i])) SearchText += static_cast<char>('0' + i);
    if (PlayerOwner->WasInputKeyJustPressed(EKeys::SpaceBar)) SearchText += ' ';
    if (PlayerOwner->WasInputKeyJustPressed(EKeys::BackSpace) && !SearchText.empty()) SearchText.pop_back();
    if (PlayerOwner->WasInputKeyJustPressed(EKeys::Enter)) bTypingSearch = false;
    if (PlayerOwner->WasInputKeyJustPressed(EKeys::Escape))
    {
        // Escape clears the search, then stops typing.
        if (SearchText.empty()) bTypingSearch = false;
        SearchText.clear();
    }
}

void AVcgsCodexHUD::SyncNotes()
{
    SinceSync = 0.f;
    if (UVcgsSubsystem* Story = Subsystem())
    {
        const int32 Changed = Story->SyncCodexNotes();
        if (Changed > 0) StatusText = "Notes synced: " + std::to_string(Changed) + " changed elsewhere.";
    }
}

void AVcgsCodexHUD::MoveCursor(vcgs::Codex& Book, int Step)
{
    const std::vector<std::string> Keys = Book.EntryKeys(SearchText, SectionKey, SortKey);
    if (Keys.empty()) { CursorKey.clear(); return; }
    int At = -1;
    for (size_t i = 0; i < Keys.size(); i++) if (Keys[i] == CursorKey) At = static_cast<int>(i);
    const int Next = At < 0 ? 0 : At + Step;
    CursorKey = Keys[static_cast<size_t>(Next < 0 ? 0 : Next >= static_cast<int>(Keys.size()) ? static_cast<int>(Keys.size()) - 1 : Next)];
}

void AVcgsCodexHUD::ToggleCodex()
{
    bCodexOpen = !bCodexOpen;
    if (bCodexOpen) SyncNotes();
    bTypingSearch = false;
    if (UVcgsSubsystem* Story = Subsystem()) Story->MarkCodexRead();
}

void AVcgsCodexHUD::DrawHUD()
{
    Super::DrawHUD();
    UVcgsSubsystem* Story = Subsystem();
    vcgs::Codex* Book = Story ? Story->CodexState() : nullptr;
    if (!Book || !Canvas) return;
    if (PlayerOwner && bCodexOpen && bTypingNote)
    {
        // Writing a note: Enter keeps it, Escape leaves it as it was.
        if (PlayerOwner->WasInputKeyJustPressed(EKeys::Enter)) { Story->SetCodexNote(ToF(CursorKey), ToF(NoteDraft)); bTypingNote = false; SyncNotes(); }
        else if (PlayerOwner->WasInputKeyJustPressed(EKeys::Escape)) bTypingNote = false;
        else TypeKeys(NoteDraft);
    }
    else if (PlayerOwner && bCodexOpen && bTypingSearch) TypeSearch();
    else if (PlayerOwner && bCodexOpen && PlayerOwner->WasInputKeyJustPressed(EKeys::E))
    {
        const FString Where = Story->ExportCodexNotes();
        StatusText = Where.IsEmpty() ? std::string("Could not save the notes.") : "Notes saved to " + ToStd(Where);
    }
    else if (PlayerOwner && bCodexOpen && PlayerOwner->WasInputKeyJustPressed(EKeys::M))
    {
        bool bWhole = false;
        Story->EmailCodexNotes(bWhole);
        StatusText = bWhole ? "Opening your mail app with the notes." : "The notes are too long for a mail link: they are on the clipboard. Paste them into the mail.";
    }
    else if (PlayerOwner && bCodexOpen && PlayerOwner->WasInputKeyJustPressed(EKeys::T))
    {
        bool bWhole = false;
        Story->TextCodexNotes(bWhole);
        StatusText = bWhole ? "Opening your messages app with the notes." : "The notes are too long for a text link: they are on the clipboard. Paste them into the message.";
    }
    else if (PlayerOwner && bCodexOpen && PlayerOwner->WasInputKeyJustPressed(EKeys::P))
    {
        const FString Where = Story->PrintCodexNotes();
        StatusText = Where.IsEmpty() ? std::string("Could not save the notes page.") : "Notes page opened to print: " + ToStd(Where);
    }
    else if (PlayerOwner && bCodexOpen && PlayerOwner->WasInputKeyJustPressed(EKeys::Y))
    {
        Story->CopyCodexNotes();
        StatusText = "Notes copied: paste them to share them (V takes them in, in another codex).";
    }
    else if (PlayerOwner && bCodexOpen && (PlayerOwner->WasInputKeyJustPressed(EKeys::I) || PlayerOwner->WasInputKeyJustPressed(EKeys::V)))
    {
        // I: from the file E saved; V: from the clipboard (notes someone shared).
        TArray<FString> Skipped;
        const int32 Count = PlayerOwner->WasInputKeyJustPressed(EKeys::V) ? Story->PasteCodexNotes(Skipped) : Story->ImportCodexNotes(Skipped);
        std::string Missing;
        for (const FString& Head : Skipped) Missing += (Missing.empty() ? "" : "; ") + ToStd(Head);
        StatusText = Count < 0 ? std::string("No notes file to import.") : "Imported " + std::to_string(Count) + " notes" + (Missing.empty() ? "" : ". Not in the codex (yet): " + Missing);
    }
    else if (PlayerOwner && bCodexOpen && PlayerOwner->WasInputKeyJustPressed(EKeys::N))
    {
        const std::vector<std::string> Keys = Book->EntryKeys(SearchText, SectionKey, SortKey);
        if (std::find(Keys.begin(), Keys.end(), CursorKey) == Keys.end()) MoveCursor(*Book, 0);
        if (!CursorKey.empty())
        {
            NoteDraft = ToStd(Story->GetCodexNote(ToF(CursorKey)));
            bTypingNote = true;
        }
    }
    else if (PlayerOwner && bCodexOpen && PlayerOwner->WasInputKeyJustPressed(EKeys::Slash)) bTypingSearch = true;
    else if (PlayerOwner && bCodexOpen && (PlayerOwner->WasInputKeyJustPressed(EKeys::Down) || PlayerOwner->WasInputKeyJustPressed(EKeys::Up)))
        MoveCursor(*Book, PlayerOwner->WasInputKeyJustPressed(EKeys::Down) ? 1 : -1);
    else if (PlayerOwner && bCodexOpen && PlayerOwner->WasInputKeyJustPressed(EKeys::B))
    {
        const std::vector<std::string> Keys = Book->EntryKeys(SearchText, SectionKey, SortKey);
        if (std::find(Keys.begin(), Keys.end(), CursorKey) == Keys.end()) MoveCursor(*Book, 0);
        if (!CursorKey.empty()) Story->ToggleCodexBookmark(ToF(CursorKey));
    }
    else if (PlayerOwner && bCodexOpen && PlayerOwner->WasInputKeyJustPressed(EKeys::S))
        SortKey = SortKey == "found" ? "newest" : SortKey == "newest" ? "name" : "found";
    else if (PlayerOwner && bCodexOpen && PlayerOwner->WasInputKeyJustPressed(EKeys::Tab))
    {
        // The next section alone, then All again.
        std::vector<std::string> Options = {"", "bookmarks"};
        for (const std::string& Key : Book->SectionKeys()) Options.push_back(Key);
        size_t At = 0;
        while (At < Options.size() && Options[At] != SectionKey) At++;
        SectionKey = Options[(At + 1) % Options.size()];
    }
    else if (PlayerOwner && (PlayerOwner->WasInputKeyJustPressed(CodexKey) || (bCodexOpen && PlayerOwner->WasInputKeyJustPressed(EKeys::Escape)))) ToggleCodex();

    const float Width = Canvas->ClipX;
    const float Height = Canvas->ClipY;
    const FLinearColor Gold(0.91f, 0.78f, 0.45f);
    const FLinearColor Ink(0.95f, 0.92f, 0.85f);
    DrawRect(FLinearColor(0.09f, 0.08f, 0.06f, 0.85f), Width - 230.f, 10.f, 220.f, 30.f);
    DrawText(ToF(Book->ButtonText(ToStd(CodexKey.ToString()))), Gold, Width - 220.f, 16.f);
    if (!bCodexOpen) return;
    Book->MarkRead();
    SinceSync += GetWorld() ? GetWorld()->GetDeltaSeconds() : 0.f;
    if (SinceSync >= 3.f) SyncNotes();

    // The panel: the codex, line by line, as much as fits.
    const float Left = 60.f;
    const float Top = 50.f;
    const float PanelWidth = Width - 120.f;
    const float PanelHeight = Height - 100.f;
    DrawRect(FLinearColor(0.09f, 0.08f, 0.06f, 0.97f), Left, Top, PanelWidth, PanelHeight);
    const size_t Columns = static_cast<size_t>((PanelWidth - 36.f) / 9.f);
    float Y = Top + 18.f;
    if (bTypingSearch || !SearchText.empty())
    {
        DrawText(ToF("Search: " + SearchText + (bTypingSearch ? "_" : "")), Gold, Left + 18.f, Y);
        Y += 30.f;
    }
    if (!StatusText.empty())
    {
        DrawText(ToF(StatusText), Gold, Left + 18.f, Y);
        Y += 30.f;
    }
    if (bTypingNote)
    {
        DrawText(ToF("Note: " + NoteDraft + "_  (Enter keeps it · Esc leaves it)"), Gold, Left + 18.f, Y);
        Y += 30.f;
    }
    if (SortKey != "found")
    {
        DrawText(ToF(std::string("Sorted: ") + (SortKey == "newest" ? "newest first" : "A-Z") + " (S to change)"), Gold, Left + 18.f, Y);
        Y += 30.f;
    }
    if (!SectionKey.empty())
    {
        DrawText(ToF("Showing: " + vcgs::Codex::Title(SectionKey) + " (Tab for the next)"), Gold, Left + 18.f, Y);
        Y += 30.f;
    }
    for (const std::string& Line : vcgs::Codex::Wrap(Book->Text(SearchText, SectionKey, SortKey, CursorKey), Columns > 20 ? Columns : 20))
    {
        if (Y > Top + PanelHeight - 44.f) break;
        DrawText(ToF(Line), Line == "CODEX" ? Gold : Ink, Left + 18.f, Y);
        Y += 22.f;
    }
    DrawText(ToF(bTypingSearch ? "Type to search · Enter to stop · Esc to clear" : "/ search · Tab section · S sort · arrows + B, N · E save, I load, Y share, V paste, M mail, T text, P print notes · C or Esc close"), Gold, Left + 18.f, Top + PanelHeight - 30.f);
}
`,

  'Source/VCGS/Public/VcgsSceneFlowComponent.h': `${RUNTIME_HEAD}
#pragma once

#include "CoreMinimal.h"
#include "Components/ActorComponent.h"
#include "VcgsCore.h"
#include "VcgsTypes.h"
#include <memory>
#include "VcgsSceneFlowComponent.generated.h"

DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams(FVcgsEventSignature, const FString&, Kind, const FString&, Label);
DECLARE_DYNAMIC_MULTICAST_DELEGATE_FourParams(FVcgsDialogueSignature, const FString&, LineId, const FString&, Speaker, const FString&, Text, const FString&, Direction);
DECLARE_DYNAMIC_MULTICAST_DELEGATE_EightParams(FVcgsDualSignature, const FString&, LineId, const FString&, Speaker, const FString&, Text, const FString&, Direction, const FString&, WithLineId, const FString&, WithSpeaker, const FString&, WithText, const FString&, WithDirection);
DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam(FVcgsKeySignature, const FString&, Key);
DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams(FVcgsChoiceSignature, const FString&, Choice, const TArray<FString>&, Options);
DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams(FVcgsEncounterSignature, const FString&, Encounter, bool, bCanWin);

class UVcgsSubsystem;

/**
 * Plays a story scene in a level: set SceneKey (VcgsKeys::Scenes), bind its
 * events to your dialogue box, cinematic player and choice menu, and call
 * Advance() or Choose() when the player is done.
 */
UCLASS(ClassGroup = (VCGS), meta = (BlueprintSpawnableComponent))
class VCGS_API UVcgsSceneFlowComponent : public UActorComponent
{
    GENERATED_BODY()

public:
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "VCGS") FString SceneKey;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "VCGS") bool bStartOnBeginPlay = true;

    /** Every event as it starts: its kind and label. */
    UPROPERTY(BlueprintAssignable, Category = "VCGS") FVcgsEventSignature OnEventStarted;
    UPROPERTY(BlueprintAssignable, Category = "VCGS") FVcgsDialogueSignature OnDialogue;
    /** Dual dialogue: two lines at once, as one beat (instead of OnDialogue). Start both voices, then Advance() once. The left-hand speech comes first. */
    UPROPERTY(BlueprintAssignable, Category = "VCGS") FVcgsDualSignature OnDualDialogue;
    UPROPERTY(BlueprintAssignable, Category = "VCGS") FVcgsKeySignature OnCinematic;
    /** Free play: how it ends, in words. It ends by itself when its rule holds. */
    UPROPERTY(BlueprintAssignable, Category = "VCGS") FVcgsKeySignature OnFreePlay;
    UPROPERTY(BlueprintAssignable, Category = "VCGS") FVcgsChoiceSignature OnChoice;
    /** An encounter: play it (a fight, a chase), then call Win() or Lose(). bCanWin says whether a win counts now. */
    UPROPERTY(BlueprintAssignable, Category = "VCGS") FVcgsEncounterSignature OnEncounter;
    /** An encounter was lost, and that loss ends the game. */
    UPROPERTY(BlueprintAssignable, Category = "VCGS") FVcgsKeySignature OnGameOver;
    /** The scene is over: the graph node that comes next. */
    UPROPERTY(BlueprintAssignable, Category = "VCGS") FVcgsKeySignature OnFinished;

    UFUNCTION(BlueprintCallable, Category = "VCGS") void StartScene();
    UFUNCTION(BlueprintCallable, Category = "VCGS") void Advance();
    UFUNCTION(BlueprintCallable, Category = "VCGS") void Choose(int32 Option);
    /** The player won the encounter on now; false (and nothing happens) when a win doesn't count yet. */
    UFUNCTION(BlueprintCallable, Category = "VCGS") bool Win();
    /** The player lost the encounter on now: it plays again, the game is over, or the scene goes on. */
    UFUNCTION(BlueprintCallable, Category = "VCGS") void Lose();
    /** Every option of the choice on offer, including ones that can't be picked now. */
    UFUNCTION(BlueprintPure, Category = "VCGS") TArray<FVcgsOption> GetOptionsDetail() const;

protected:
    virtual void BeginPlay() override;
    virtual void EndPlay(const EEndPlayReason::Type Reason) override;

private:
    UVcgsSubsystem* Subsystem() const;
    std::unique_ptr<vcgs::ScenePlayer> Player;
};
`,

  'Source/VCGS/Private/VcgsSceneFlowComponent.cpp': `${RUNTIME_HEAD}
#include "VcgsSceneFlowComponent.h"
#include "VcgsConvert.h"
#include "VcgsSubsystem.h"
#include "Engine/GameInstance.h"
#include "Engine/World.h"

using VcgsConvert::ToF;
using VcgsConvert::ToStd;

UVcgsSubsystem* UVcgsSceneFlowComponent::Subsystem() const
{
    UWorld* World = GetWorld();
    UGameInstance* GameInstance = World ? World->GetGameInstance() : nullptr;
    return GameInstance ? GameInstance->GetSubsystem<UVcgsSubsystem>() : nullptr;
}

void UVcgsSceneFlowComponent::BeginPlay()
{
    Super::BeginPlay();
    if (bStartOnBeginPlay) StartScene();
}

void UVcgsSceneFlowComponent::EndPlay(const EEndPlayReason::Type Reason)
{
    Player.reset();
    Super::EndPlay(Reason);
}

void UVcgsSceneFlowComponent::StartScene()
{
    UVcgsSubsystem* Story = Subsystem();
    vcgs::GameState* Game = Story ? Story->State() : nullptr;
    if (!Game)
    {
        UE_LOG(LogTemp, Warning, TEXT("VCGS: no story loaded; export it from VC Game Studio."));
        return;
    }
    Player = std::make_unique<vcgs::ScenePlayer>(*Game, ToStd(SceneKey));
    if (!Player->Exists())
    {
        UE_LOG(LogTemp, Warning, TEXT("VCGS: the story has no scene %s."), *SceneKey);
        Player.reset();
        return;
    }
    Player->OnEvent = [this](const vcgs::Value& Event) { OnEventStarted.Broadcast(ToF(Event["kind"].Str()), ToF(Event["label"].Str())); };
    Player->OnDialogue = [this, Game](const std::string& LineId)
    {
        const vcgs::StoryWalker::Line Line = vcgs::StoryWalker::GetLine(*Game, LineId);
        OnDialogue.Broadcast(ToF(LineId), ToF(Line.Speaker), ToF(Line.Text), ToF(Line.Direction));
    };
    Player->OnDual = [this, Game](const std::string& LineId, const std::string& WithLineId)
    {
        const vcgs::StoryWalker::Line Line = vcgs::StoryWalker::GetLine(*Game, LineId);
        const vcgs::StoryWalker::Line With = vcgs::StoryWalker::GetLine(*Game, WithLineId);
        OnDualDialogue.Broadcast(ToF(LineId), ToF(Line.Speaker), ToF(Line.Text), ToF(Line.Direction), ToF(WithLineId), ToF(With.Speaker), ToF(With.Text), ToF(With.Direction));
    };
    Player->OnCinematic = [this](const std::string& Key) { OnCinematic.Broadcast(ToF(Key)); };
    Player->OnFreePlay = [this](const std::string& EndsWhen) { OnFreePlay.Broadcast(ToF(EndsWhen)); };
    Player->OnChoice = [this](const std::string& Choice, const std::vector<std::string>& Options)
    {
        TArray<FString> Labels;
        for (const std::string& Option : Options) Labels.Add(ToF(Option));
        OnChoice.Broadcast(ToF(Choice), Labels);
    };
    Player->OnEncounter = [this](const std::string& Encounter, bool bCanWin) { OnEncounter.Broadcast(ToF(Encounter), bCanWin); };
    Player->OnGameOver = [this](const std::string& Encounter) { OnGameOver.Broadcast(ToF(Encounter)); };
    Player->OnFinished = [this](const std::string& Next) { OnFinished.Broadcast(ToF(Next)); };
    Player->Start();
}

void UVcgsSceneFlowComponent::Advance()
{
    if (Player) Player->Advance();
}

void UVcgsSceneFlowComponent::Choose(int32 Option)
{
    if (Player) Player->Choose(Option);
}

bool UVcgsSceneFlowComponent::Win()
{
    return Player && Player->Win();
}

void UVcgsSceneFlowComponent::Lose()
{
    if (Player) Player->Lose();
}

TArray<FVcgsOption> UVcgsSceneFlowComponent::GetOptionsDetail() const
{
    TArray<FVcgsOption> Options;
    if (!Player) return Options;
    int32 Index = 0;
    for (const vcgs::ScenePlayer::Option& O : Player->OptionsDetail)
    {
        FVcgsOption Option;
        Option.Index = Index++;
        Option.Label = ToF(O.Label);
        Option.bAvailable = O.Available;
        Option.Why = ToF(O.Why);
        Options.Add(Option);
    }
    return Options;
}
`,

  'Source/VCGS/Public/VcgsInteractableComponent.h': `${RUNTIME_HEAD}
#pragma once

#include "CoreMinimal.h"
#include "Components/ActorComponent.h"
#include "VcgsInteractableComponent.generated.h"

class UVcgsSubsystem;

/** An object the player can use: set ObjectKey (VcgsKeys::Objects) and call Interact from your input code. */
UCLASS(ClassGroup = (VCGS), meta = (BlueprintSpawnableComponent))
class VCGS_API UVcgsInteractableComponent : public UActorComponent
{
    GENERATED_BODY()

public:
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "VCGS") FString ObjectKey;

    UFUNCTION(BlueprintPure, Category = "VCGS") TArray<FString> AvailableVerbs() const;
    UFUNCTION(BlueprintCallable, Category = "VCGS") bool Interact(const FString& Verb);
    UFUNCTION(BlueprintPure, Category = "VCGS") FString GetState() const;

private:
    UVcgsSubsystem* Subsystem() const;
};
`,

  'Source/VCGS/Private/VcgsInteractableComponent.cpp': `${RUNTIME_HEAD}
#include "VcgsInteractableComponent.h"
#include "VcgsConvert.h"
#include "VcgsSubsystem.h"
#include "Engine/GameInstance.h"
#include "Engine/World.h"

using VcgsConvert::ToF;
using VcgsConvert::ToStd;

UVcgsSubsystem* UVcgsInteractableComponent::Subsystem() const
{
    UWorld* World = GetWorld();
    UGameInstance* GameInstance = World ? World->GetGameInstance() : nullptr;
    return GameInstance ? GameInstance->GetSubsystem<UVcgsSubsystem>() : nullptr;
}

TArray<FString> UVcgsInteractableComponent::AvailableVerbs() const
{
    TArray<FString> Verbs;
    UVcgsSubsystem* Story = Subsystem();
    if (!Story || !Story->State()) return Verbs;
    for (const std::string& Verb : vcgs::Interactions::AvailableVerbs(*Story->State(), ToStd(ObjectKey))) Verbs.Add(ToF(Verb));
    return Verbs;
}

bool UVcgsInteractableComponent::Interact(const FString& Verb)
{
    UVcgsSubsystem* Story = Subsystem();
    return Story && Story->State() && vcgs::Interactions::Interact(*Story->State(), ToStd(ObjectKey), ToStd(Verb));
}

FString UVcgsInteractableComponent::GetState() const
{
    UVcgsSubsystem* Story = Subsystem();
    return Story && Story->State() ? ToF(Story->State()->GetObjectState(ToStd(ObjectKey))) : FString();
}
`,

  'Source/VCGS/Private/VcgsModule.cpp': `${RUNTIME_HEAD}
#include "Modules/ModuleManager.h"

IMPLEMENT_MODULE(FDefaultModuleImpl, VCGS)
`,
};

// ---------------------------------------------------------------- generated

const cppString = (s: string) => JSON.stringify(s);

const keySection = (name: string, summary: string, list: { ident: Ident }[]): string[] =>
  list.length
    ? [`    /** ${summary} */`, `    namespace ${name}`, '    {', ...list.map((x) => `        constexpr const TCHAR* ${x.ident.type} = TEXT(${cppString(x.ident.key)});`), '    }', '']
    : [];

export const storyKeysHeader = (ir: HandoffIR): string =>
  [
    HEADER,
    '#pragma once',
    '',
    '#include "CoreMinimal.h"',
    '',
    `/** Every key in ${ir.project.name.replace(/\*\//g, '')}, for game code: VcgsKeys::Scenes::Sc03TheVaultDoor. */`,
    'namespace VcgsKeys',
    '{',
    ...keySection('Scenes', 'Story scenes, for UVcgsSceneFlowComponent.', ir.scenes),
    ...keySection('Choices', 'Choices, on the graph and in scenes.', ir.choices),
    ...keySection('Characters', 'Characters and NPCs.', ir.characters),
    ...keySection('Objects', 'Interactive objects, for UVcgsInteractableComponent.', ir.objects.filter((o) => o.kind === 'object')),
    ...keySection('Puzzles', 'Puzzles.', ir.objects.filter((o) => o.kind === 'puzzle')),
    ...keySection('Items', 'Inventory items.', ir.items),
    ...keySection('Locations', 'Locations.', ir.locations),
    ...DESIGN_LISTS.flatMap((d) => keySection(d.folder, `${d.folder} (DT_${d.folder}).`, ir[d.list])),
    ...keySection('Cinematics', 'Cinematics.', ir.cinematics),
    ...keySection('Flags', 'States the game remembers.', ir.flags),
    ...keySection('Triggers', 'Triggers.', ir.triggers.filter((t) => t.kind === 'trigger')),
    ...keySection('Gates', 'Gates.', ir.triggers.filter((t) => t.kind === 'gate')),
    '}',
    '',
  ].join('\n');

/** A CSV cell as Unreal's DataTable importer reads it. */
const cell = (v: string | number | boolean) => {
  const s = typeof v === 'boolean' ? (v ? 'True' : 'False') : String(v);
  return /[",\n\r]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s;
};
const csv = (header: string[], rows: (string | number | boolean)[][]) => [header, ...rows].map((r) => r.map(cell).join(',')).join('\n');

const linearColor = (hex: string) => {
  const m = /^#?([0-9a-f]{6})$/i.exec(hex.trim());
  const n = m ? parseInt(m[1]!, 16) : 0xffffff;
  const c = (shift: number) => (((n >> shift) & 255) / 255).toFixed(3);
  return `(R=${c(16)},G=${c(8)},B=${c(0)},A=1.000)`;
};

/** name → [row struct, CSV]: the DataTables the import script makes. */
export const dataTables = (ir: HandoffIR): Record<string, { struct: string; csv: string }> => {
  const details = (fields: Record<string, string>) =>
    Object.entries(fields)
      .filter(([k]) => k !== 'seconds' && k !== 'shots')
      .map(([k, v]) => `${k}: ${v}`)
      .join('\n');
  return {
    Characters: {
      struct: 'VcgsCharacterRow',
      csv: csv(['---', 'Key', 'Code', 'DisplayName', 'Description', 'Role', 'Arc', 'Color'], ir.characters.map((c) => [c.ident.key, c.ident.key, c.code, c.name, c.description, c.role, c.arc, linearColor(c.color)])),
    },
    Items: { struct: 'VcgsElementRow', csv: csv(['---', 'Key', 'Code', 'DisplayName', 'Description', 'Details'], ir.items.map((t) => [t.ident.key, t.ident.key, t.code, t.name, t.notes, details(t.fields)])) },
    Locations: { struct: 'VcgsElementRow', csv: csv(['---', 'Key', 'Code', 'DisplayName', 'Description', 'Details'], ir.locations.map((t) => [t.ident.key, t.ident.key, t.code, t.name, t.notes, details(t.fields)])) },
    ...Object.fromEntries(
      DESIGN_LISTS.map((d) => [d.folder, { struct: 'VcgsElementRow', csv: csv(['---', 'Key', 'Code', 'DisplayName', 'Description', 'Details'], ir[d.list].map((t) => [t.ident.key, t.ident.key, t.code, t.name, t.notes, details(t.fields)])) }]),
    ),
    Cinematics: {
      struct: 'VcgsCinematicRow',
      csv: csv(
        ['---', 'Key', 'Code', 'DisplayName', 'Description', 'Seconds', 'Shots', 'bSkippable'],
        ir.cinematics.map((c) => [c.ident.key, c.ident.key, c.code, c.name, c.notes, Number(c.fields.seconds ?? 0), Number(c.fields.shots ?? 1), c.fields.skippable !== 'Not skippable']),
      ),
    },
    Shots: {
      struct: 'VcgsShotRow',
      csv: csv(
        ['---', 'Cinematic', 'Index', 'Framing', 'Move', 'Lens', 'Characters', 'Action', 'Line', 'Audio', 'Vfx', 'Seconds', 'Transition', 'Notes'],
        ir.cinematics.flatMap((c) =>
          (c.shots ?? []).map((s, i) => [`${c.ident.key}_${i + 1}`, c.ident.key, i + 1, s.framing, s.move, s.lens, s.characters.join(' '), s.action, s.line ?? '', s.audio, s.vfx, s.seconds, s.transition, s.notes]),
        ),
      ),
    },
    Lines: { struct: 'VcgsLineRow', csv: csv(['---', 'Scene', 'Speaker', 'Text', 'Direction', 'Vo', 'Rich', 'DualWith'], ir.lines.map((l) => [l.id, l.scene, l.speaker ?? '', l.text, l.direction, l.vo, l.styled ? richText(l.styled) : '', l.dual ?? ''])) },
  };
};

const importScript = (root: string, structs: Record<string, string>) => `# Generated by VC Game Studio. Run it in the Unreal Editor (Tools > Execute
# Python Script, with the Python Editor Script Plugin on) after each export:
# it imports the CSVs next to it as DataTable assets, replacing the old ones.
import os
import unreal

HERE = os.path.dirname(os.path.abspath(__file__))
DESTINATION = "/Game/${root.replace(/^Content\/?/, '')}/DataTables"
# Each table's CSV and the row struct it is read into.
STRUCTS = {
${Object.entries(structs)
  .map(([name, struct]) => `    ${JSON.stringify(name)}: "/Script/VCGS.${struct}",`)
  .join('\n')}
}


def import_table(name, struct_path):
    task = unreal.AssetImportTask()
    task.filename = os.path.join(HERE, "DataTables", name + ".csv")
    task.destination_path = DESTINATION
    task.destination_name = "DT_" + name
    task.replace_existing = True
    task.automated = True
    task.save = True
    factory = unreal.CSVImportFactory()
    factory.automated_import_settings.import_type = unreal.CSVImportType.ECSV_DATA_TABLE
    factory.automated_import_settings.import_row_struct = unreal.load_object(None, struct_path)
    task.factory = factory
    unreal.AssetToolsHelpers.get_asset_tools().import_asset_tasks([task])


for table, struct in STRUCTS.items():
    import_table(table, struct)
unreal.log("VCGS: imported %d DataTables into %s" % (len(STRUCTS), DESTINATION))
`;

const README = (ir: HandoffIR, root: string) => `# ${ir.project.name} — generated by VC Game Studio

Everything in \`${root}\` and \`${SOURCE}/Public/Generated\` is rewritten on each
export. Change the story in VC Game Studio, not these files. The plugin
(\`${PLUGIN}\`) is the same for every project.

1. **Enable the plugin**: it builds with your project (Core, CoreUObject, Engine).
2. **Package the story**: add \`${root.replace(/^Content\/?/, '')}\` to *Project Settings >
   Packaging > Additional Non-Asset Directories to Package*. The
   \`UVcgsSubsystem\` reads \`story.json\` from there when the game starts.
3. **A story scene**: add \`UVcgsSceneFlowComponent\` to an actor in the level,
   set \`SceneKey\` (\`VcgsKeys::Scenes\`), bind \`OnDialogue\` (and \`OnDualDialogue\`, two lines at once), \`OnCinematic\`,
   \`OnFreePlay\`, \`OnChoice\`, \`OnEncounter\` (and \`OnGameOver\`) and \`OnFinished\`, and call \`Advance\` /
   \`Choose\`, or \`Win\` / \`Lose\` for an encounter.
4. **An object**: add \`UVcgsInteractableComponent\` with its \`ObjectKey\` and call
   \`Interact("Pull")\`.
5. **DataTables** (optional, for designers and subtitles): run
   \`${root}/import_datatables.py\` in the editor to make DT_Characters, DT_Items,
   DT_Locations, DT_Cinematics, DT_Shots and DT_Lines, and the design
   definitions DT_Lore, DT_Quests, DT_Mechanics and DT_Encounters (codex text,
   a quest log, tuning; their logic lives in flags and triggers).

To try the story before your game has its own screens, set **AVcgsCodexHUD** as
the game mode's HUD class: C opens a codex with the quest log and the lore
found. \`GetCodexText\` and \`GetCodexNewCount\` on the subsystem give the same
for your own UMG widget.

The game state lives in the \`UVcgsSubsystem\` (flags, items, arcs and the rest,
all Blueprint-callable). Quests start and complete by their rules (\`OnQuestStarted\`,
\`OnQuestCompleted\`, \`GetQuestState\`), lore is discovered (\`OnLoreDiscovered\`,
\`GetKnownLore\`, \`GetLoreEntry\`) and mechanics become available (\`OnMechanicAvailable\`,
\`HasMechanic\`, \`GetMechanicDetail\`). Triggers fire and puzzles solve themselves as their
conditions come true; \`Onward\` and \`ChooseOnGraph\` follow the graph between
scenes.
`;

export const generateUnreal = (ir: HandoffIR, outputPath: string): EngineOutput => {
  const root = outputPath.replace(/\/+$/, '') || 'Content/VCGS/Generated';
  const files: GeneratedFile[] = [];
  const put = (path: string, content: string, kind: GeneratedFile['kind']) => {
    files.push({ path, content: content.endsWith('\n') ? content : `${content}\n`, kind });
    return path;
  };
  for (const [name, content] of Object.entries(PLUGIN_FILES)) put(`${PLUGIN}/${name}`, content, 'runtime');
  if (ir.levels.length) for (const [name, content] of Object.entries(LEVEL_PLUGIN_FILES)) put(`${PLUGIN}/${name}`, content, 'runtime');

  const storyPath = put(`${root}/story.json`, JSON.stringify({ ...JSON_FORMAT, generator: 'VC Game Studio', ...ir }, null, 2), 'generated');
  const keysPath = put(`${SOURCE}/Public/Generated/VcgsStoryKeys.h`, storyKeysHeader(ir), 'generated');
  const tables = dataTables(ir);
  const tablePaths: Record<string, string> = {};
  for (const [name, t] of Object.entries(tables)) tablePaths[name] = put(`${root}/DataTables/${name}.csv`, t.csv, 'generated');
  const scriptPath = put(`${root}/import_datatables.py`, importScript(root, Object.fromEntries(Object.entries(tables).map(([name, t]) => [name, t.struct]))), 'generated');
  put(`${root}/README.md`, README(ir, root), 'generated');

  const elements: ElementOutput[] = [];
  const row = (e: Omit<ElementOutput, 'fingerprint'>, data: unknown) => elements.push({ ...e, fingerprint: fingerprint(`${VERSION}:${JSON.stringify(data)}`) });
  row({ id: 'story', label: 'Story graph', symbol: 'plotPoint', group: 'Story', generates: `story.json · VcgsStoryKeys.h · ${ir.graph.length} nodes`, files: [storyPath, keysPath, scriptPath] }, { graph: ir.graph, keys: storyKeysHeader(ir) });
  for (const s of ir.scenes) row({ id: s.id, label: `${s.code} ${s.name}`.trim(), symbol: 'scene', group: 'Story', generates: `UVcgsSceneFlowComponent · ${s.main.length} events · VcgsKeys::Scenes::${s.ident.type}`, files: [storyPath] }, s);
  for (const c of ir.cinematics) row({ id: c.id, label: `${c.code} ${c.name}`.trim(), symbol: 'cinematic', group: 'Story', generates: `DT_Cinematics row${c.shots ? ` · ${c.shots.length} DT_Shots rows` : ''}`, files: [tablePaths.Cinematics!, tablePaths.Shots!] }, c);
  for (const c of ir.choices) row({ id: c.id, label: `${c.code} ${c.name}`.trim(), symbol: 'choice', group: 'Story', generates: `Choice · ${c.options.length} options`, files: [storyPath] }, c);
  for (const c of ir.characters) row({ id: c.id, label: c.name, symbol: 'character', group: 'People + words', generates: 'DT_Characters row', files: [tablePaths.Characters!] }, c);
  row({ id: 'dialogue', label: `Dialogue (${ir.lines.length} lines)`, symbol: 'dialogue', group: 'People + words', generates: 'DT_Lines · story.json', files: [tablePaths.Lines!, storyPath] }, ir.lines);
  for (const o of ir.objects) row({ id: o.id, label: o.name, symbol: o.kind, group: 'World', generates: o.kind === 'puzzle' ? 'Puzzle · solved by rule' : `UVcgsInteractableComponent · ${o.interactions.length} interaction${o.interactions.length === 1 ? '' : 's'}`, files: [storyPath] }, o);
  for (const t of ir.items) row({ id: t.id, label: t.name, symbol: 'inventory', group: 'World', generates: 'DT_Items row', files: [tablePaths.Items!] }, t);
  for (const t of ir.locations) row({ id: t.id, label: t.name, symbol: 'environment', group: 'World', generates: 'DT_Locations row', files: [tablePaths.Locations!] }, t);
  for (const d of DESIGN_LISTS) for (const t of ir[d.list]) row({ id: t.id, label: `${t.code} ${t.name}`.trim(), symbol: d.type, group: d.group, generates: `DT_${d.folder} row`, files: [tablePaths[d.folder]!] }, t);
  for (const f of ir.flags) row({ id: f.id, label: f.name, symbol: 'state', group: 'Logic', generates: `Game state flag · ${f.values.join(' / ')}`, files: [storyPath] }, f);
  for (const t of ir.triggers) row({ id: t.id, label: t.name, symbol: t.kind, group: 'Logic', generates: t.kind === 'gate' ? 'GateOpen' : 'Trigger · fires by rule', files: [storyPath] }, t);

  // Levels: their data, and the editor script that places and updates their actors.
  if (ir.levels.length) {
    const names: Record<string, string> = Object.fromEntries(
      [...ir.characters, ...ir.objects, ...ir.items, ...ir.locations, ...DESIGN_LISTS.flatMap((d) => ir[d.list]), ...ir.cinematics, ...ir.flags, ...ir.triggers, ...ir.choices, ...ir.scenes].map((x) => [x.ident.key, x.name]),
    );
    const builder = put(`${root}/Levels/build_level.py`, buildLevelScript(root), 'generated');
    for (const level of ir.levels) {
      const path = put(`${root}/Levels/${level.key}.json`, levelJsonUnreal(level, names), 'generated');
      row({ id: level.guid, label: level.name, symbol: 'environment', group: 'World', generates: `Level data · ${level.items.length} items → build_level.py places AVcgsLevelItem actors (${level.export_name})`, files: [path, builder] }, level);
    }
  }
  put(
    `${root}/vcgs_manifest.json`,
    JSON.stringify(
      {
        generator: 'VC Game Studio',
        adapter: VERSION,
        engine: 'unreal',
        project: ir.project,
        elements: elements.map((e) => ({ id: e.id, label: e.label, files: e.files, fingerprint: e.fingerprint })),
        levels: ir.levels.map((l) => ({
          guid: l.guid,
          name: l.name,
          data: `${root}/Levels/${l.key}.json`,
          revision: l.revision,
          items: l.items.map((i) => ({ guid: i.guid, export_name: i.export_name, source: `${l.name} / ${i.name}`, engine_ref: `AVcgsLevelItem ${i.export_name} (tag vcgs:${i.guid})`, revision: i.revision, replacement_locked: i.replacement_locked })),
        })),
      },
      null,
      2,
    ),
    'generated',
  );
  return { files, elements };
};

export const unreal: EngineAdapter = {
  id: 'unreal',
  name: 'Unreal Engine 5',
  language: 'C++ plugin · DataTables',
  available: true,
  defaultOutputPath: 'Content/VCGS/Generated',
  runtimeName: 'VCGS Runtime plugin for Unreal',
  setup: [
    'Enable the VCGS plugin, and add Content/VCGS/Generated to Additional Non-Asset Directories to Package.',
    'Add a UVcgsSceneFlowComponent (with its scene key) to each story level; run import_datatables.py for the DataTables.',
    'For a level, open the map it belongs in and run Levels/build_level.py (Tools > Execute Python Script); run it again after each export.',
  ],
  generate: generateUnreal,
};
