import type { EngineAdapter, ElementOutput, EngineOutput, GeneratedFile } from './engines';
import { fingerprint } from './engines';
import type { HandoffIR, Ident } from './ir';
import { JSON_FORMAT } from './json';
import { VCGS_CORE_H } from './unreal-core';
import { buildLevelScript, LEVEL_PLUGIN_FILES, levelJsonUnreal } from './unreal-levels';

/**
 * The Unreal adapter: a plugin (Plugins/VCGS) and the story's data.
 *
 * The plugin's logic is VcgsCore.h, portable C++17 that plays story.json the
 * way the Godot and Unity runtimes do; around it, a game-instance subsystem
 * (the playthrough), a scene-flow and an interactable component with
 * Blueprint events and functions, and DataTable row structs. The generated
 * side is story.json, VcgsStoryKeys.h with every key, DataTable CSVs for
 * characters, items, locations, cinematics, shots and lines, and an editor
 * Python script that imports them as DataTable assets.
 */

const VERSION = 'unreal-1';
const PLUGIN = 'Plugins/VCGS';
const SOURCE = `${PLUGIN}/Source/VCGS`;
const HEADER = '// Generated by VC Game Studio. Edit the story, not this file.';
const RUNTIME_HEAD = '// VCGS Runtime for Unreal. The same for every project; safe to commit.';

export const PLUGIN_FILES: Record<string, string> = {
  'VCGS.uplugin': `${JSON.stringify(
    {
      FileVersion: 3,
      Version: 1,
      VersionName: '1.0',
      FriendlyName: 'VCGS Runtime',
      Description: 'Plays a story written in VC Game Studio: its scenes, choices, rules and state.',
      Category: 'Gameplay',
      CreatedBy: 'VC Game Studio',
      CanContainContent: true,
      Modules: [{ Name: 'VCGS', Type: 'Runtime', LoadingPhase: 'Default' }],
    },
    null,
    2,
  )}\n`,

  'Source/VCGS/VCGS.Build.cs': `${RUNTIME_HEAD}
using UnrealBuildTool;

public class VCGS : ModuleRules
{
    public VCGS(ReadOnlyTargetRules Target) : base(Target)
    {
        PCHUsage = PCHUsageMode.UseExplicitOrSharedPCHs;
        PublicDependencyModuleNames.AddRange(new string[] { "Core", "CoreUObject", "Engine" });
    }
}
`,

  'Source/VCGS/Public/VcgsCore.h': VCGS_CORE_H,

  'Source/VCGS/Public/VcgsConvert.h': `${RUNTIME_HEAD}
#pragma once

#include "CoreMinimal.h"
#include <string>

/** Between Unreal's strings and the core's UTF-8. */
namespace VcgsConvert
{
    inline std::string ToStd(const FString& S) { return std::string(TCHAR_TO_UTF8(*S)); }
    inline FString ToF(const std::string& S) { return FString(UTF8_TO_TCHAR(S.c_str())); }
}
`,

  'Source/VCGS/Public/VcgsTypes.h': `${RUNTIME_HEAD}
#pragma once

#include "CoreMinimal.h"
#include "Engine/DataTable.h"
#include "VcgsTypes.generated.h"

/** One option of a choice, for a menu: whether it can be picked, and why not. */
USTRUCT(BlueprintType)
struct VCGS_API FVcgsOption
{
    GENERATED_BODY()

    UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "VCGS") int32 Index = 0;
    UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "VCGS") FString Label;
    UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "VCGS") bool bAvailable = true;
    UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "VCGS") FString Why;
};

/** A row of DT_Characters. */
USTRUCT(BlueprintType)
struct VCGS_API FVcgsCharacterRow : public FTableRowBase
{
    GENERATED_BODY()

    UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "VCGS") FString Key;
    UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "VCGS") FString Code;
    UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "VCGS") FString DisplayName;
    UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "VCGS", meta = (MultiLine = true)) FString Description;
    UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "VCGS") FString Role;
    UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "VCGS") FString Arc;
    UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "VCGS") FLinearColor Color = FLinearColor::White;
};

/** A row of DT_Items or DT_Locations: its fields as "name: value" lines in Details. */
USTRUCT(BlueprintType)
struct VCGS_API FVcgsElementRow : public FTableRowBase
{
    GENERATED_BODY()

    UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "VCGS") FString Key;
    UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "VCGS") FString Code;
    UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "VCGS") FString DisplayName;
    UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "VCGS", meta = (MultiLine = true)) FString Description;
    UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "VCGS", meta = (MultiLine = true)) FString Details;
};

/** A row of DT_Cinematics. */
USTRUCT(BlueprintType)
struct VCGS_API FVcgsCinematicRow : public FTableRowBase
{
    GENERATED_BODY()

    UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "VCGS") FString Key;
    UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "VCGS") FString Code;
    UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "VCGS") FString DisplayName;
    UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "VCGS", meta = (MultiLine = true)) FString Description;
    UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "VCGS") float Seconds = 0.f;
    UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "VCGS") int32 Shots = 1;
    UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "VCGS") bool bSkippable = true;
};

/** A row of DT_Shots: one shot of a cinematic, in order. */
USTRUCT(BlueprintType)
struct VCGS_API FVcgsShotRow : public FTableRowBase
{
    GENERATED_BODY()

    UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "VCGS") FString Cinematic;
    UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "VCGS") int32 Index = 0;
    UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "VCGS") FString Framing;
    UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "VCGS") FString Move;
    UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "VCGS") FString Lens;
    UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "VCGS") FString Characters;
    UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "VCGS", meta = (MultiLine = true)) FString Action;
    UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "VCGS") FString Line;
    UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "VCGS") FString Audio;
    UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "VCGS") FString Vfx;
    UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "VCGS") float Seconds = 0.f;
    UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "VCGS") FString Transition;
    UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "VCGS", meta = (MultiLine = true)) FString Notes;
};

/** A row of DT_Lines: one line of dialogue, for subtitles and the VO team. */
USTRUCT(BlueprintType)
struct VCGS_API FVcgsLineRow : public FTableRowBase
{
    GENERATED_BODY()

    UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "VCGS") FString Scene;
    UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "VCGS") FString Speaker;
    UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "VCGS", meta = (MultiLine = true)) FString Text;
    UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "VCGS") FString Direction;
    UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "VCGS") FString Vo;
};
`,

  'Source/VCGS/Public/VcgsSubsystem.h': `${RUNTIME_HEAD}
#pragma once

#include "CoreMinimal.h"
#include "Subsystems/GameInstanceSubsystem.h"
#include "VcgsCore.h"
#include "VcgsTypes.h"
#include <memory>
#include "VcgsSubsystem.generated.h"

/**
 * The one playthrough of the story: reads story.json when the game starts and
 * keeps its state across levels. Everything here is callable from Blueprints.
 */
UCLASS()
class VCGS_API UVcgsSubsystem : public UGameInstanceSubsystem
{
    GENERATED_BODY()

public:
    virtual void Initialize(FSubsystemCollectionBase& Collection) override;
    virtual void Deinitialize() override;

    /** story.json, relative to the project's Content folder. */
    static FString StoryPath();

    /** Load a story from its JSON (done for you at start). */
    UFUNCTION(BlueprintCallable, Category = "VCGS") bool LoadStory(const FString& Json);
    /** Put everything where it starts. */
    UFUNCTION(BlueprintCallable, Category = "VCGS") void NewGame();
    UFUNCTION(BlueprintPure, Category = "VCGS") bool IsLoaded() const;
    UFUNCTION(BlueprintPure, Category = "VCGS") FString GetStoryName() const;
    /** The graph node the story starts at. */
    UFUNCTION(BlueprintPure, Category = "VCGS") FString GetStart() const;

    UFUNCTION(BlueprintPure, Category = "VCGS|State") FString GetFlag(const FString& Flag) const;
    UFUNCTION(BlueprintCallable, Category = "VCGS|State") void SetFlag(const FString& Flag, const FString& Value);
    UFUNCTION(BlueprintPure, Category = "VCGS|State") FString GetObjectState(const FString& Object) const;
    UFUNCTION(BlueprintPure, Category = "VCGS|State") bool HasItem(const FString& Item) const;
    UFUNCTION(BlueprintCallable, Category = "VCGS|State") void GiveItem(const FString& Item);
    UFUNCTION(BlueprintCallable, Category = "VCGS|State") void TakeItem(const FString& Item);
    UFUNCTION(BlueprintPure, Category = "VCGS|State") int32 GetArc(const FString& Character) const;
    UFUNCTION(BlueprintPure, Category = "VCGS|State") bool IsSolved(const FString& Puzzle) const;
    UFUNCTION(BlueprintPure, Category = "VCGS|State") bool WasVisited(const FString& Scene) const;
    UFUNCTION(BlueprintPure, Category = "VCGS|State") bool GateOpen(const FString& Gate) const;

    /** Where a graph node goes next: its first route whose conditions hold, else on along the spine. */
    UFUNCTION(BlueprintCallable, Category = "VCGS|Story") FString Onward(const FString& Node);
    /** "scene", "choice", "plotPoint", "cinematic", "begin", "end"... */
    UFUNCTION(BlueprintPure, Category = "VCGS|Story") FString NodeKind(const FString& Node) const;
    /** "ending", "gameOver", or empty when the node goes on. */
    UFUNCTION(BlueprintPure, Category = "VCGS|Story") FString NodeOutcome(const FString& Node) const;
    /** A choice on the graph: every option that can be picked now. */
    UFUNCTION(BlueprintCallable, Category = "VCGS|Story") TArray<FVcgsOption> ChoiceOptions(const FString& Choice) const;
    /** Pick an option of a choice on the graph; returns the node it leads to (empty if it can't be picked). */
    UFUNCTION(BlueprintCallable, Category = "VCGS|Story") FString ChooseOnGraph(const FString& Choice, int32 Option);
    UFUNCTION(BlueprintPure, Category = "VCGS|Story") void GetLine(const FString& LineId, FString& Speaker, FString& Text, FString& Direction) const;

    /** The core's playthrough, for C++ (null until a story is loaded). */
    vcgs::GameState* State() const { return Game.get(); }

private:
    std::unique_ptr<vcgs::Story> StoryData;
    std::unique_ptr<vcgs::GameState> Game;
};
`,

  'Source/VCGS/Private/VcgsSubsystem.cpp': `${RUNTIME_HEAD}
#include "VcgsSubsystem.h"
#include "VcgsConvert.h"
#include "Misc/FileHelper.h"
#include "Misc/Paths.h"

using VcgsConvert::ToF;
using VcgsConvert::ToStd;

FString UVcgsSubsystem::StoryPath()
{
    return TEXT("VCGS/Generated/story.json");
}

void UVcgsSubsystem::Initialize(FSubsystemCollectionBase& Collection)
{
    Super::Initialize(Collection);
    FString Json;
    const FString Path = FPaths::ProjectContentDir() / StoryPath();
    if (FFileHelper::LoadFileToString(Json, *Path))
    {
        LoadStory(Json);
    }
    else
    {
        UE_LOG(LogTemp, Warning, TEXT("VCGS: no story at %s. Export it from VC Game Studio."), *Path);
    }
}

void UVcgsSubsystem::Deinitialize()
{
    Game.reset();
    StoryData.reset();
    Super::Deinitialize();
}

bool UVcgsSubsystem::LoadStory(const FString& Json)
{
    std::string Error;
    vcgs::Value Root = vcgs::JsonReader::Parse(ToStd(Json), &Error);
    if (!Root.IsObject())
    {
        UE_LOG(LogTemp, Error, TEXT("VCGS: story.json could not be read (%s)."), *ToF(Error));
        return false;
    }
    Game.reset();
    StoryData = std::make_unique<vcgs::Story>(std::move(Root));
    Game = std::make_unique<vcgs::GameState>(*StoryData);
    return true;
}

void UVcgsSubsystem::NewGame()
{
    if (Game) Game->Reset();
}

bool UVcgsSubsystem::IsLoaded() const { return Game != nullptr; }
FString UVcgsSubsystem::GetStoryName() const { return StoryData ? ToF(StoryData->Name) : FString(); }
FString UVcgsSubsystem::GetStart() const { return StoryData ? ToF(StoryData->Start) : FString(); }

FString UVcgsSubsystem::GetFlag(const FString& Flag) const { return Game ? ToF(Game->GetFlag(ToStd(Flag))) : FString(); }
void UVcgsSubsystem::SetFlag(const FString& Flag, const FString& Value) { if (Game) Game->SetFlag(ToStd(Flag), ToStd(Value)); }
FString UVcgsSubsystem::GetObjectState(const FString& Object) const { return Game ? ToF(Game->GetObjectState(ToStd(Object))) : FString(); }
bool UVcgsSubsystem::HasItem(const FString& Item) const { return Game && Game->HasItem(ToStd(Item)); }
void UVcgsSubsystem::GiveItem(const FString& Item) { if (Game) Game->GiveItem(ToStd(Item)); }
void UVcgsSubsystem::TakeItem(const FString& Item) { if (Game) Game->TakeItem(ToStd(Item)); }
int32 UVcgsSubsystem::GetArc(const FString& Character) const { return Game ? Game->Arc(ToStd(Character)) : 0; }
bool UVcgsSubsystem::IsSolved(const FString& Puzzle) const { return Game && Game->Solved.count(ToStd(Puzzle)) > 0; }
bool UVcgsSubsystem::WasVisited(const FString& Scene) const { return Game && Game->Visited.count(ToStd(Scene)) > 0; }
bool UVcgsSubsystem::GateOpen(const FString& Gate) const { return !Game || vcgs::Rules::GateOpen(ToStd(Gate), *Game); }

FString UVcgsSubsystem::Onward(const FString& Node) { return Game ? ToF(vcgs::StoryWalker::Onward(*Game, ToStd(Node))) : FString(); }
FString UVcgsSubsystem::NodeKind(const FString& Node) const { return Game ? ToF(vcgs::StoryWalker::KindOf(*Game, ToStd(Node))) : FString(); }
FString UVcgsSubsystem::NodeOutcome(const FString& Node) const { return Game ? ToF(vcgs::StoryWalker::OutcomeOf(*Game, ToStd(Node))) : FString(); }

TArray<FVcgsOption> UVcgsSubsystem::ChoiceOptions(const FString& Choice) const
{
    TArray<FVcgsOption> Options;
    if (!Game) return Options;
    for (int Index : vcgs::StoryWalker::Offered(*Game, ToStd(Choice)))
    {
        FVcgsOption Option;
        Option.Index = Index;
        Option.Label = ToF(vcgs::StoryWalker::OptionLabel(*Game, ToStd(Choice), Index));
        Options.Add(Option);
    }
    return Options;
}

FString UVcgsSubsystem::ChooseOnGraph(const FString& Choice, int32 Option)
{
    return Game ? ToF(vcgs::StoryWalker::Choose(*Game, ToStd(Choice), Option)) : FString();
}

void UVcgsSubsystem::GetLine(const FString& LineId, FString& Speaker, FString& Text, FString& Direction) const
{
    if (!Game) return;
    const vcgs::StoryWalker::Line Line = vcgs::StoryWalker::GetLine(*Game, ToStd(LineId));
    Speaker = ToF(Line.Speaker);
    Text = ToF(Line.Text);
    Direction = ToF(Line.Direction);
}
`,

  'Source/VCGS/Public/VcgsSceneFlowComponent.h': `${RUNTIME_HEAD}
#pragma once

#include "CoreMinimal.h"
#include "Components/ActorComponent.h"
#include "VcgsCore.h"
#include "VcgsTypes.h"
#include <memory>
#include "VcgsSceneFlowComponent.generated.h"

DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams(FVcgsEventSignature, const FString&, Kind, const FString&, Label);
DECLARE_DYNAMIC_MULTICAST_DELEGATE_FourParams(FVcgsDialogueSignature, const FString&, LineId, const FString&, Speaker, const FString&, Text, const FString&, Direction);
DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam(FVcgsKeySignature, const FString&, Key);
DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams(FVcgsChoiceSignature, const FString&, Choice, const TArray<FString>&, Options);

class UVcgsSubsystem;

/**
 * Plays a story scene in a level: set SceneKey (VcgsKeys::Scenes), bind its
 * events to your dialogue box, cinematic player and choice menu, and call
 * Advance() or Choose() when the player is done.
 */
UCLASS(ClassGroup = (VCGS), meta = (BlueprintSpawnableComponent))
class VCGS_API UVcgsSceneFlowComponent : public UActorComponent
{
    GENERATED_BODY()

public:
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "VCGS") FString SceneKey;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "VCGS") bool bStartOnBeginPlay = true;

    /** Every event as it starts: its kind and label. */
    UPROPERTY(BlueprintAssignable, Category = "VCGS") FVcgsEventSignature OnEventStarted;
    UPROPERTY(BlueprintAssignable, Category = "VCGS") FVcgsDialogueSignature OnDialogue;
    UPROPERTY(BlueprintAssignable, Category = "VCGS") FVcgsKeySignature OnCinematic;
    /** Free play: how it ends, in words. It ends by itself when its rule holds. */
    UPROPERTY(BlueprintAssignable, Category = "VCGS") FVcgsKeySignature OnFreePlay;
    UPROPERTY(BlueprintAssignable, Category = "VCGS") FVcgsChoiceSignature OnChoice;
    /** The scene is over: the graph node that comes next. */
    UPROPERTY(BlueprintAssignable, Category = "VCGS") FVcgsKeySignature OnFinished;

    UFUNCTION(BlueprintCallable, Category = "VCGS") void StartScene();
    UFUNCTION(BlueprintCallable, Category = "VCGS") void Advance();
    UFUNCTION(BlueprintCallable, Category = "VCGS") void Choose(int32 Option);
    /** Every option of the choice on offer, including ones that can't be picked now. */
    UFUNCTION(BlueprintPure, Category = "VCGS") TArray<FVcgsOption> GetOptionsDetail() const;

protected:
    virtual void BeginPlay() override;
    virtual void EndPlay(const EEndPlayReason::Type Reason) override;

private:
    UVcgsSubsystem* Subsystem() const;
    std::unique_ptr<vcgs::ScenePlayer> Player;
};
`,

  'Source/VCGS/Private/VcgsSceneFlowComponent.cpp': `${RUNTIME_HEAD}
#include "VcgsSceneFlowComponent.h"
#include "VcgsConvert.h"
#include "VcgsSubsystem.h"
#include "Engine/GameInstance.h"
#include "Engine/World.h"

using VcgsConvert::ToF;
using VcgsConvert::ToStd;

UVcgsSubsystem* UVcgsSceneFlowComponent::Subsystem() const
{
    UWorld* World = GetWorld();
    UGameInstance* GameInstance = World ? World->GetGameInstance() : nullptr;
    return GameInstance ? GameInstance->GetSubsystem<UVcgsSubsystem>() : nullptr;
}

void UVcgsSceneFlowComponent::BeginPlay()
{
    Super::BeginPlay();
    if (bStartOnBeginPlay) StartScene();
}

void UVcgsSceneFlowComponent::EndPlay(const EEndPlayReason::Type Reason)
{
    Player.reset();
    Super::EndPlay(Reason);
}

void UVcgsSceneFlowComponent::StartScene()
{
    UVcgsSubsystem* Story = Subsystem();
    vcgs::GameState* Game = Story ? Story->State() : nullptr;
    if (!Game)
    {
        UE_LOG(LogTemp, Warning, TEXT("VCGS: no story loaded; export it from VC Game Studio."));
        return;
    }
    Player = std::make_unique<vcgs::ScenePlayer>(*Game, ToStd(SceneKey));
    if (!Player->Exists())
    {
        UE_LOG(LogTemp, Warning, TEXT("VCGS: the story has no scene %s."), *SceneKey);
        Player.reset();
        return;
    }
    Player->OnEvent = [this](const vcgs::Value& Event) { OnEventStarted.Broadcast(ToF(Event["kind"].Str()), ToF(Event["label"].Str())); };
    Player->OnDialogue = [this, Game](const std::string& LineId)
    {
        const vcgs::StoryWalker::Line Line = vcgs::StoryWalker::GetLine(*Game, LineId);
        OnDialogue.Broadcast(ToF(LineId), ToF(Line.Speaker), ToF(Line.Text), ToF(Line.Direction));
    };
    Player->OnCinematic = [this](const std::string& Key) { OnCinematic.Broadcast(ToF(Key)); };
    Player->OnFreePlay = [this](const std::string& EndsWhen) { OnFreePlay.Broadcast(ToF(EndsWhen)); };
    Player->OnChoice = [this](const std::string& Choice, const std::vector<std::string>& Options)
    {
        TArray<FString> Labels;
        for (const std::string& Option : Options) Labels.Add(ToF(Option));
        OnChoice.Broadcast(ToF(Choice), Labels);
    };
    Player->OnFinished = [this](const std::string& Next) { OnFinished.Broadcast(ToF(Next)); };
    Player->Start();
}

void UVcgsSceneFlowComponent::Advance()
{
    if (Player) Player->Advance();
}

void UVcgsSceneFlowComponent::Choose(int32 Option)
{
    if (Player) Player->Choose(Option);
}

TArray<FVcgsOption> UVcgsSceneFlowComponent::GetOptionsDetail() const
{
    TArray<FVcgsOption> Options;
    if (!Player) return Options;
    int32 Index = 0;
    for (const vcgs::ScenePlayer::Option& O : Player->OptionsDetail)
    {
        FVcgsOption Option;
        Option.Index = Index++;
        Option.Label = ToF(O.Label);
        Option.bAvailable = O.Available;
        Option.Why = ToF(O.Why);
        Options.Add(Option);
    }
    return Options;
}
`,

  'Source/VCGS/Public/VcgsInteractableComponent.h': `${RUNTIME_HEAD}
#pragma once

#include "CoreMinimal.h"
#include "Components/ActorComponent.h"
#include "VcgsInteractableComponent.generated.h"

class UVcgsSubsystem;

/** An object the player can use: set ObjectKey (VcgsKeys::Objects) and call Interact from your input code. */
UCLASS(ClassGroup = (VCGS), meta = (BlueprintSpawnableComponent))
class VCGS_API UVcgsInteractableComponent : public UActorComponent
{
    GENERATED_BODY()

public:
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "VCGS") FString ObjectKey;

    UFUNCTION(BlueprintPure, Category = "VCGS") TArray<FString> AvailableVerbs() const;
    UFUNCTION(BlueprintCallable, Category = "VCGS") bool Interact(const FString& Verb);
    UFUNCTION(BlueprintPure, Category = "VCGS") FString GetState() const;

private:
    UVcgsSubsystem* Subsystem() const;
};
`,

  'Source/VCGS/Private/VcgsInteractableComponent.cpp': `${RUNTIME_HEAD}
#include "VcgsInteractableComponent.h"
#include "VcgsConvert.h"
#include "VcgsSubsystem.h"
#include "Engine/GameInstance.h"
#include "Engine/World.h"

using VcgsConvert::ToF;
using VcgsConvert::ToStd;

UVcgsSubsystem* UVcgsInteractableComponent::Subsystem() const
{
    UWorld* World = GetWorld();
    UGameInstance* GameInstance = World ? World->GetGameInstance() : nullptr;
    return GameInstance ? GameInstance->GetSubsystem<UVcgsSubsystem>() : nullptr;
}

TArray<FString> UVcgsInteractableComponent::AvailableVerbs() const
{
    TArray<FString> Verbs;
    UVcgsSubsystem* Story = Subsystem();
    if (!Story || !Story->State()) return Verbs;
    for (const std::string& Verb : vcgs::Interactions::AvailableVerbs(*Story->State(), ToStd(ObjectKey))) Verbs.Add(ToF(Verb));
    return Verbs;
}

bool UVcgsInteractableComponent::Interact(const FString& Verb)
{
    UVcgsSubsystem* Story = Subsystem();
    return Story && Story->State() && vcgs::Interactions::Interact(*Story->State(), ToStd(ObjectKey), ToStd(Verb));
}

FString UVcgsInteractableComponent::GetState() const
{
    UVcgsSubsystem* Story = Subsystem();
    return Story && Story->State() ? ToF(Story->State()->GetObjectState(ToStd(ObjectKey))) : FString();
}
`,

  'Source/VCGS/Private/VcgsModule.cpp': `${RUNTIME_HEAD}
#include "Modules/ModuleManager.h"

IMPLEMENT_MODULE(FDefaultModuleImpl, VCGS)
`,
};

// ---------------------------------------------------------------- generated

const cppString = (s: string) => JSON.stringify(s);

const keySection = (name: string, summary: string, list: { ident: Ident }[]): string[] =>
  list.length
    ? [`    /** ${summary} */`, `    namespace ${name}`, '    {', ...list.map((x) => `        constexpr const TCHAR* ${x.ident.type} = TEXT(${cppString(x.ident.key)});`), '    }', '']
    : [];

export const storyKeysHeader = (ir: HandoffIR): string =>
  [
    HEADER,
    '#pragma once',
    '',
    '#include "CoreMinimal.h"',
    '',
    `/** Every key in ${ir.project.name.replace(/\*\//g, '')}, for game code: VcgsKeys::Scenes::Sc03TheVaultDoor. */`,
    'namespace VcgsKeys',
    '{',
    ...keySection('Scenes', 'Story scenes, for UVcgsSceneFlowComponent.', ir.scenes),
    ...keySection('Choices', 'Choices, on the graph and in scenes.', ir.choices),
    ...keySection('Characters', 'Characters and NPCs.', ir.characters),
    ...keySection('Objects', 'Interactive objects, for UVcgsInteractableComponent.', ir.objects.filter((o) => o.kind === 'object')),
    ...keySection('Puzzles', 'Puzzles.', ir.objects.filter((o) => o.kind === 'puzzle')),
    ...keySection('Items', 'Inventory items.', ir.items),
    ...keySection('Locations', 'Locations.', ir.locations),
    ...keySection('Cinematics', 'Cinematics.', ir.cinematics),
    ...keySection('Flags', 'States the game remembers.', ir.flags),
    ...keySection('Triggers', 'Triggers.', ir.triggers.filter((t) => t.kind === 'trigger')),
    ...keySection('Gates', 'Gates.', ir.triggers.filter((t) => t.kind === 'gate')),
    '}',
    '',
  ].join('\n');

/** A CSV cell as Unreal's DataTable importer reads it. */
const cell = (v: string | number | boolean) => {
  const s = typeof v === 'boolean' ? (v ? 'True' : 'False') : String(v);
  return /[",\n\r]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s;
};
const csv = (header: string[], rows: (string | number | boolean)[][]) => [header, ...rows].map((r) => r.map(cell).join(',')).join('\n');

const linearColor = (hex: string) => {
  const m = /^#?([0-9a-f]{6})$/i.exec(hex.trim());
  const n = m ? parseInt(m[1]!, 16) : 0xffffff;
  const c = (shift: number) => (((n >> shift) & 255) / 255).toFixed(3);
  return `(R=${c(16)},G=${c(8)},B=${c(0)},A=1.000)`;
};

/** name → [row struct, CSV]: the DataTables the import script makes. */
export const dataTables = (ir: HandoffIR): Record<string, { struct: string; csv: string }> => {
  const details = (fields: Record<string, string>) =>
    Object.entries(fields)
      .filter(([k]) => k !== 'seconds' && k !== 'shots')
      .map(([k, v]) => `${k}: ${v}`)
      .join('\n');
  return {
    Characters: {
      struct: 'VcgsCharacterRow',
      csv: csv(['---', 'Key', 'Code', 'DisplayName', 'Description', 'Role', 'Arc', 'Color'], ir.characters.map((c) => [c.ident.key, c.ident.key, c.code, c.name, c.description, c.role, c.arc, linearColor(c.color)])),
    },
    Items: { struct: 'VcgsElementRow', csv: csv(['---', 'Key', 'Code', 'DisplayName', 'Description', 'Details'], ir.items.map((t) => [t.ident.key, t.ident.key, t.code, t.name, t.notes, details(t.fields)])) },
    Locations: { struct: 'VcgsElementRow', csv: csv(['---', 'Key', 'Code', 'DisplayName', 'Description', 'Details'], ir.locations.map((t) => [t.ident.key, t.ident.key, t.code, t.name, t.notes, details(t.fields)])) },
    Cinematics: {
      struct: 'VcgsCinematicRow',
      csv: csv(
        ['---', 'Key', 'Code', 'DisplayName', 'Description', 'Seconds', 'Shots', 'bSkippable'],
        ir.cinematics.map((c) => [c.ident.key, c.ident.key, c.code, c.name, c.notes, Number(c.fields.seconds ?? 0), Number(c.fields.shots ?? 1), c.fields.skippable !== 'Not skippable']),
      ),
    },
    Shots: {
      struct: 'VcgsShotRow',
      csv: csv(
        ['---', 'Cinematic', 'Index', 'Framing', 'Move', 'Lens', 'Characters', 'Action', 'Line', 'Audio', 'Vfx', 'Seconds', 'Transition', 'Notes'],
        ir.cinematics.flatMap((c) =>
          (c.shots ?? []).map((s, i) => [`${c.ident.key}_${i + 1}`, c.ident.key, i + 1, s.framing, s.move, s.lens, s.characters.join(' '), s.action, s.line ?? '', s.audio, s.vfx, s.seconds, s.transition, s.notes]),
        ),
      ),
    },
    Lines: { struct: 'VcgsLineRow', csv: csv(['---', 'Scene', 'Speaker', 'Text', 'Direction', 'Vo'], ir.lines.map((l) => [l.id, l.scene, l.speaker ?? '', l.text, l.direction, l.vo])) },
  };
};

const importScript = (root: string, structs: Record<string, string>) => `# Generated by VC Game Studio. Run it in the Unreal Editor (Tools > Execute
# Python Script, with the Python Editor Script Plugin on) after each export:
# it imports the CSVs next to it as DataTable assets, replacing the old ones.
import os
import unreal

HERE = os.path.dirname(os.path.abspath(__file__))
DESTINATION = "/Game/${root.replace(/^Content\/?/, '')}/DataTables"
# Each table's CSV and the row struct it is read into.
STRUCTS = {
${Object.entries(structs)
  .map(([name, struct]) => `    ${JSON.stringify(name)}: "/Script/VCGS.${struct}",`)
  .join('\n')}
}


def import_table(name, struct_path):
    task = unreal.AssetImportTask()
    task.filename = os.path.join(HERE, "DataTables", name + ".csv")
    task.destination_path = DESTINATION
    task.destination_name = "DT_" + name
    task.replace_existing = True
    task.automated = True
    task.save = True
    factory = unreal.CSVImportFactory()
    factory.automated_import_settings.import_type = unreal.CSVImportType.ECSV_DATA_TABLE
    factory.automated_import_settings.import_row_struct = unreal.load_object(None, struct_path)
    task.factory = factory
    unreal.AssetToolsHelpers.get_asset_tools().import_asset_tasks([task])


for table, struct in STRUCTS.items():
    import_table(table, struct)
unreal.log("VCGS: imported %d DataTables into %s" % (len(STRUCTS), DESTINATION))
`;

const README = (ir: HandoffIR, root: string) => `# ${ir.project.name} — generated by VC Game Studio

Everything in \`${root}\` and \`${SOURCE}/Public/Generated\` is rewritten on each
export. Change the story in VC Game Studio, not these files. The plugin
(\`${PLUGIN}\`) is the same for every project.

1. **Enable the plugin**: it builds with your project (Core, CoreUObject, Engine).
2. **Package the story**: add \`${root.replace(/^Content\/?/, '')}\` to *Project Settings >
   Packaging > Additional Non-Asset Directories to Package*. The
   \`UVcgsSubsystem\` reads \`story.json\` from there when the game starts.
3. **A story scene**: add \`UVcgsSceneFlowComponent\` to an actor in the level,
   set \`SceneKey\` (\`VcgsKeys::Scenes\`), bind \`OnDialogue\`, \`OnCinematic\`,
   \`OnFreePlay\`, \`OnChoice\` and \`OnFinished\`, and call \`Advance\` / \`Choose\`.
4. **An object**: add \`UVcgsInteractableComponent\` with its \`ObjectKey\` and call
   \`Interact("Pull")\`.
5. **DataTables** (optional, for designers and subtitles): run
   \`${root}/import_datatables.py\` in the editor to make DT_Characters, DT_Items,
   DT_Locations, DT_Cinematics, DT_Shots and DT_Lines.

The game state lives in the \`UVcgsSubsystem\` (flags, items, arcs and the rest,
all Blueprint-callable). Triggers fire and puzzles solve themselves as their
conditions come true; \`Onward\` and \`ChooseOnGraph\` follow the graph between
scenes.
`;

export const generateUnreal = (ir: HandoffIR, outputPath: string): EngineOutput => {
  const root = outputPath.replace(/\/+$/, '') || 'Content/VCGS/Generated';
  const files: GeneratedFile[] = [];
  const put = (path: string, content: string, kind: GeneratedFile['kind']) => {
    files.push({ path, content: content.endsWith('\n') ? content : `${content}\n`, kind });
    return path;
  };
  for (const [name, content] of Object.entries(PLUGIN_FILES)) put(`${PLUGIN}/${name}`, content, 'runtime');
  if (ir.levels.length) for (const [name, content] of Object.entries(LEVEL_PLUGIN_FILES)) put(`${PLUGIN}/${name}`, content, 'runtime');

  const storyPath = put(`${root}/story.json`, JSON.stringify({ ...JSON_FORMAT, generator: 'VC Game Studio', ...ir }, null, 2), 'generated');
  const keysPath = put(`${SOURCE}/Public/Generated/VcgsStoryKeys.h`, storyKeysHeader(ir), 'generated');
  const tables = dataTables(ir);
  const tablePaths: Record<string, string> = {};
  for (const [name, t] of Object.entries(tables)) tablePaths[name] = put(`${root}/DataTables/${name}.csv`, t.csv, 'generated');
  const scriptPath = put(`${root}/import_datatables.py`, importScript(root, Object.fromEntries(Object.entries(tables).map(([name, t]) => [name, t.struct]))), 'generated');
  put(`${root}/README.md`, README(ir, root), 'generated');

  const elements: ElementOutput[] = [];
  const row = (e: Omit<ElementOutput, 'fingerprint'>, data: unknown) => elements.push({ ...e, fingerprint: fingerprint(`${VERSION}:${JSON.stringify(data)}`) });
  row({ id: 'story', label: 'Story graph', symbol: 'plotPoint', group: 'Story', generates: `story.json · VcgsStoryKeys.h · ${ir.graph.length} nodes`, files: [storyPath, keysPath, scriptPath] }, { graph: ir.graph, keys: storyKeysHeader(ir) });
  for (const s of ir.scenes) row({ id: s.id, label: `${s.code} ${s.name}`.trim(), symbol: 'scene', group: 'Story', generates: `UVcgsSceneFlowComponent · ${s.main.length} events · VcgsKeys::Scenes::${s.ident.type}`, files: [storyPath] }, s);
  for (const c of ir.cinematics) row({ id: c.id, label: `${c.code} ${c.name}`.trim(), symbol: 'cinematic', group: 'Story', generates: `DT_Cinematics row${c.shots ? ` · ${c.shots.length} DT_Shots rows` : ''}`, files: [tablePaths.Cinematics!, tablePaths.Shots!] }, c);
  for (const c of ir.choices) row({ id: c.id, label: `${c.code} ${c.name}`.trim(), symbol: 'choice', group: 'Story', generates: `Choice · ${c.options.length} options`, files: [storyPath] }, c);
  for (const c of ir.characters) row({ id: c.id, label: c.name, symbol: 'character', group: 'People + words', generates: 'DT_Characters row', files: [tablePaths.Characters!] }, c);
  row({ id: 'dialogue', label: `Dialogue (${ir.lines.length} lines)`, symbol: 'dialogue', group: 'People + words', generates: 'DT_Lines · story.json', files: [tablePaths.Lines!, storyPath] }, ir.lines);
  for (const o of ir.objects) row({ id: o.id, label: o.name, symbol: o.kind, group: 'World', generates: o.kind === 'puzzle' ? 'Puzzle · solved by rule' : `UVcgsInteractableComponent · ${o.interactions.length} interaction${o.interactions.length === 1 ? '' : 's'}`, files: [storyPath] }, o);
  for (const t of ir.items) row({ id: t.id, label: t.name, symbol: 'inventory', group: 'World', generates: 'DT_Items row', files: [tablePaths.Items!] }, t);
  for (const t of ir.locations) row({ id: t.id, label: t.name, symbol: 'environment', group: 'World', generates: 'DT_Locations row', files: [tablePaths.Locations!] }, t);
  for (const f of ir.flags) row({ id: f.id, label: f.name, symbol: 'state', group: 'Logic', generates: `Game state flag · ${f.values.join(' / ')}`, files: [storyPath] }, f);
  for (const t of ir.triggers) row({ id: t.id, label: t.name, symbol: t.kind, group: 'Logic', generates: t.kind === 'gate' ? 'GateOpen' : 'Trigger · fires by rule', files: [storyPath] }, t);

  // Levels: their data, and the editor script that places and updates their actors.
  if (ir.levels.length) {
    const names: Record<string, string> = Object.fromEntries(
      [...ir.characters, ...ir.objects, ...ir.items, ...ir.locations, ...ir.cinematics, ...ir.flags, ...ir.triggers, ...ir.choices, ...ir.scenes].map((x) => [x.ident.key, x.name]),
    );
    const builder = put(`${root}/Levels/build_level.py`, buildLevelScript(root), 'generated');
    for (const level of ir.levels) {
      const path = put(`${root}/Levels/${level.key}.json`, levelJsonUnreal(level, names), 'generated');
      row({ id: level.guid, label: level.name, symbol: 'environment', group: 'World', generates: `Level data · ${level.items.length} items → build_level.py places AVcgsLevelItem actors (${level.export_name})`, files: [path, builder] }, level);
    }
  }
  put(
    `${root}/vcgs_manifest.json`,
    JSON.stringify(
      {
        generator: 'VC Game Studio',
        adapter: VERSION,
        engine: 'unreal',
        project: ir.project,
        elements: elements.map((e) => ({ id: e.id, label: e.label, files: e.files, fingerprint: e.fingerprint })),
        levels: ir.levels.map((l) => ({
          guid: l.guid,
          name: l.name,
          data: `${root}/Levels/${l.key}.json`,
          revision: l.revision,
          items: l.items.map((i) => ({ guid: i.guid, export_name: i.export_name, source: `${l.name} / ${i.name}`, engine_ref: `AVcgsLevelItem ${i.export_name} (tag vcgs:${i.guid})`, revision: i.revision, replacement_locked: i.replacement_locked })),
        })),
      },
      null,
      2,
    ),
    'generated',
  );
  return { files, elements };
};

export const unreal: EngineAdapter = {
  id: 'unreal',
  name: 'Unreal Engine 5',
  language: 'C++ plugin · DataTables',
  available: true,
  defaultOutputPath: 'Content/VCGS/Generated',
  runtimeName: 'VCGS Runtime plugin for Unreal',
  setup: [
    'Enable the VCGS plugin, and add Content/VCGS/Generated to Additional Non-Asset Directories to Package.',
    'Add a UVcgsSceneFlowComponent (with its scene key) to each story level; run import_datatables.py for the DataTables.',
    'For a level, open the map it belongs in and run Levels/build_level.py (Tools > Execute Python Script); run it again after each export.',
  ],
  generate: generateUnreal,
};
